// Generated by jextract

package com.tiji.silcef.natives;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct _cef_request_t {
 *     cef_base_ref_counted_t base;
 *     int (*is_read_only)(struct _cef_request_t *) __attribute__((stdcall));
 *     cef_string_userfree_t (*get_url)(struct _cef_request_t *) __attribute__((stdcall));
 *     void (*set_url)(struct _cef_request_t *, const cef_string_t *) __attribute__((stdcall));
 *     cef_string_userfree_t (*get_method)(struct _cef_request_t *) __attribute__((stdcall));
 *     void (*set_method)(struct _cef_request_t *, const cef_string_t *) __attribute__((stdcall));
 *     void (*set_referrer)(struct _cef_request_t *, const cef_string_t *, cef_referrer_policy_t) __attribute__((stdcall));
 *     cef_string_userfree_t (*get_referrer_url)(struct _cef_request_t *) __attribute__((stdcall));
 *     cef_referrer_policy_t (*get_referrer_policy)(struct _cef_request_t *) __attribute__((stdcall));
 *     struct _cef_post_data_t *(*get_post_data)(struct _cef_request_t *) __attribute__((stdcall));
 *     void (*set_post_data)(struct _cef_request_t *, struct _cef_post_data_t *) __attribute__((stdcall));
 *     void (*get_header_map)(struct _cef_request_t *, cef_string_multimap_t) __attribute__((stdcall));
 *     void (*set_header_map)(struct _cef_request_t *, cef_string_multimap_t) __attribute__((stdcall));
 *     cef_string_userfree_t (*get_header_by_name)(struct _cef_request_t *, const cef_string_t *) __attribute__((stdcall));
 *     void (*set_header_by_name)(struct _cef_request_t *, const cef_string_t *, const cef_string_t *, int) __attribute__((stdcall));
 *     void (*set)(struct _cef_request_t *, const cef_string_t *, const cef_string_t *, struct _cef_post_data_t *, cef_string_multimap_t) __attribute__((stdcall));
 *     int (*get_flags)(struct _cef_request_t *) __attribute__((stdcall));
 *     void (*set_flags)(struct _cef_request_t *, int) __attribute__((stdcall));
 *     cef_string_userfree_t (*get_first_party_for_cookies)(struct _cef_request_t *) __attribute__((stdcall));
 *     void (*set_first_party_for_cookies)(struct _cef_request_t *, const cef_string_t *) __attribute__((stdcall));
 *     cef_resource_type_t (*get_resource_type)(struct _cef_request_t *) __attribute__((stdcall));
 *     cef_transition_type_t (*get_transition_type)(struct _cef_request_t *) __attribute__((stdcall));
 *     uint64_t (*get_identifier)(struct _cef_request_t *) __attribute__((stdcall));
 * }
 * }
 */
public class _cef_request_t {

    _cef_request_t() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        _cef_base_ref_counted_t.layout().withName("base"),
        cef_render_handler_capi_h.C_POINTER.withName("is_read_only"),
        cef_render_handler_capi_h.C_POINTER.withName("get_url"),
        cef_render_handler_capi_h.C_POINTER.withName("set_url"),
        cef_render_handler_capi_h.C_POINTER.withName("get_method"),
        cef_render_handler_capi_h.C_POINTER.withName("set_method"),
        cef_render_handler_capi_h.C_POINTER.withName("set_referrer"),
        cef_render_handler_capi_h.C_POINTER.withName("get_referrer_url"),
        cef_render_handler_capi_h.C_POINTER.withName("get_referrer_policy"),
        cef_render_handler_capi_h.C_POINTER.withName("get_post_data"),
        cef_render_handler_capi_h.C_POINTER.withName("set_post_data"),
        cef_render_handler_capi_h.C_POINTER.withName("get_header_map"),
        cef_render_handler_capi_h.C_POINTER.withName("set_header_map"),
        cef_render_handler_capi_h.C_POINTER.withName("get_header_by_name"),
        cef_render_handler_capi_h.C_POINTER.withName("set_header_by_name"),
        cef_render_handler_capi_h.C_POINTER.withName("set"),
        cef_render_handler_capi_h.C_POINTER.withName("get_flags"),
        cef_render_handler_capi_h.C_POINTER.withName("set_flags"),
        cef_render_handler_capi_h.C_POINTER.withName("get_first_party_for_cookies"),
        cef_render_handler_capi_h.C_POINTER.withName("set_first_party_for_cookies"),
        cef_render_handler_capi_h.C_POINTER.withName("get_resource_type"),
        cef_render_handler_capi_h.C_POINTER.withName("get_transition_type"),
        cef_render_handler_capi_h.C_POINTER.withName("get_identifier")
    ).withName("_cef_request_t");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final GroupLayout base$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("base"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * cef_base_ref_counted_t base
     * }
     */
    public static final GroupLayout base$layout() {
        return base$LAYOUT;
    }

    private static final long base$OFFSET = $LAYOUT.byteOffset(groupElement("base"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * cef_base_ref_counted_t base
     * }
     */
    public static final long base$offset() {
        return base$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * cef_base_ref_counted_t base
     * }
     */
    public static MemorySegment base(MemorySegment struct) {
        return struct.asSlice(base$OFFSET, base$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * cef_base_ref_counted_t base
     * }
     */
    public static void base(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, base$OFFSET, base$LAYOUT.byteSize());
    }

    /**
     * {@snippet lang=c :
     * int (*is_read_only)(struct _cef_request_t *) __attribute__((stdcall))
     * }
     */
    public final static class is_read_only {

        private is_read_only() {
            // Should not be called directly
        }

        /**
         * The function pointer signature, expressed as a functional interface
         */
        public interface Function {
            int apply(MemorySegment _x0);
        }

        private static final FunctionDescriptor $DESC = FunctionDescriptor.of(
            cef_render_handler_capi_h.C_INT,
            cef_render_handler_capi_h.C_POINTER
        );

        /**
         * The descriptor of this function pointer
         */
        public static FunctionDescriptor descriptor() {
            return $DESC;
        }

        private static final MethodHandle UP$MH = cef_render_handler_capi_h.upcallHandle(is_read_only.Function.class, "apply", $DESC);

        /**
         * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
         * The lifetime of the returned segment is managed by {@code arena}
         */
        public static MemorySegment allocate(is_read_only.Function fi, Arena arena) {
            return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
        }

        private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

        /**
         * Invoke the upcall stub {@code funcPtr}, with given parameters
         */
        public static int invoke(MemorySegment funcPtr, MemorySegment _x0) {
            try {
                return (int) DOWN$MH.invokeExact(funcPtr, _x0);
            } catch (Error | RuntimeException ex) {
                throw ex;
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        }
    }

    private static final AddressLayout is_read_only$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("is_read_only"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int (*is_read_only)(struct _cef_request_t *) __attribute__((stdcall))
     * }
     */
    public static final AddressLayout is_read_only$layout() {
        return is_read_only$LAYOUT;
    }

    private static final long is_read_only$OFFSET = $LAYOUT.byteOffset(groupElement("is_read_only"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int (*is_read_only)(struct _cef_request_t *) __attribute__((stdcall))
     * }
     */
    public static final long is_read_only$offset() {
        return is_read_only$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int (*is_read_only)(struct _cef_request_t *) __attribute__((stdcall))
     * }
     */
    public static MemorySegment is_read_only(MemorySegment struct) {
        return struct.get(is_read_only$LAYOUT, is_read_only$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int (*is_read_only)(struct _cef_request_t *) __attribute__((stdcall))
     * }
     */
    public static void is_read_only(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(is_read_only$LAYOUT, is_read_only$OFFSET, fieldValue);
    }

    /**
     * {@snippet lang=c :
     * cef_string_userfree_t (*get_url)(struct _cef_request_t *) __attribute__((stdcall))
     * }
     */
    public final static class get_url {

        private get_url() {
            // Should not be called directly
        }

        /**
         * The function pointer signature, expressed as a functional interface
         */
        public interface Function {
            MemorySegment apply(MemorySegment _x0);
        }

        private static final FunctionDescriptor $DESC = FunctionDescriptor.of(
            cef_render_handler_capi_h.C_POINTER,
            cef_render_handler_capi_h.C_POINTER
        );

        /**
         * The descriptor of this function pointer
         */
        public static FunctionDescriptor descriptor() {
            return $DESC;
        }

        private static final MethodHandle UP$MH = cef_render_handler_capi_h.upcallHandle(get_url.Function.class, "apply", $DESC);

        /**
         * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
         * The lifetime of the returned segment is managed by {@code arena}
         */
        public static MemorySegment allocate(get_url.Function fi, Arena arena) {
            return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
        }

        private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

        /**
         * Invoke the upcall stub {@code funcPtr}, with given parameters
         */
        public static MemorySegment invoke(MemorySegment funcPtr, MemorySegment _x0) {
            try {
                return (MemorySegment) DOWN$MH.invokeExact(funcPtr, _x0);
            } catch (Error | RuntimeException ex) {
                throw ex;
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        }
    }

    private static final AddressLayout get_url$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("get_url"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * cef_string_userfree_t (*get_url)(struct _cef_request_t *) __attribute__((stdcall))
     * }
     */
    public static final AddressLayout get_url$layout() {
        return get_url$LAYOUT;
    }

    private static final long get_url$OFFSET = $LAYOUT.byteOffset(groupElement("get_url"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * cef_string_userfree_t (*get_url)(struct _cef_request_t *) __attribute__((stdcall))
     * }
     */
    public static final long get_url$offset() {
        return get_url$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * cef_string_userfree_t (*get_url)(struct _cef_request_t *) __attribute__((stdcall))
     * }
     */
    public static MemorySegment get_url(MemorySegment struct) {
        return struct.get(get_url$LAYOUT, get_url$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * cef_string_userfree_t (*get_url)(struct _cef_request_t *) __attribute__((stdcall))
     * }
     */
    public static void get_url(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(get_url$LAYOUT, get_url$OFFSET, fieldValue);
    }

    /**
     * {@snippet lang=c :
     * void (*set_url)(struct _cef_request_t *, const cef_string_t *) __attribute__((stdcall))
     * }
     */
    public final static class set_url {

        private set_url() {
            // Should not be called directly
        }

        /**
         * The function pointer signature, expressed as a functional interface
         */
        public interface Function {
            void apply(MemorySegment _x0, MemorySegment _x1);
        }

        private static final FunctionDescriptor $DESC = FunctionDescriptor.ofVoid(
            cef_render_handler_capi_h.C_POINTER,
            cef_render_handler_capi_h.C_POINTER
        );

        /**
         * The descriptor of this function pointer
         */
        public static FunctionDescriptor descriptor() {
            return $DESC;
        }

        private static final MethodHandle UP$MH = cef_render_handler_capi_h.upcallHandle(set_url.Function.class, "apply", $DESC);

        /**
         * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
         * The lifetime of the returned segment is managed by {@code arena}
         */
        public static MemorySegment allocate(set_url.Function fi, Arena arena) {
            return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
        }

        private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

        /**
         * Invoke the upcall stub {@code funcPtr}, with given parameters
         */
        public static void invoke(MemorySegment funcPtr, MemorySegment _x0, MemorySegment _x1) {
            try {
                 DOWN$MH.invokeExact(funcPtr, _x0, _x1);
            } catch (Error | RuntimeException ex) {
                throw ex;
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        }
    }

    private static final AddressLayout set_url$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("set_url"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * void (*set_url)(struct _cef_request_t *, const cef_string_t *) __attribute__((stdcall))
     * }
     */
    public static final AddressLayout set_url$layout() {
        return set_url$LAYOUT;
    }

    private static final long set_url$OFFSET = $LAYOUT.byteOffset(groupElement("set_url"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * void (*set_url)(struct _cef_request_t *, const cef_string_t *) __attribute__((stdcall))
     * }
     */
    public static final long set_url$offset() {
        return set_url$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * void (*set_url)(struct _cef_request_t *, const cef_string_t *) __attribute__((stdcall))
     * }
     */
    public static MemorySegment set_url(MemorySegment struct) {
        return struct.get(set_url$LAYOUT, set_url$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * void (*set_url)(struct _cef_request_t *, const cef_string_t *) __attribute__((stdcall))
     * }
     */
    public static void set_url(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(set_url$LAYOUT, set_url$OFFSET, fieldValue);
    }

    /**
     * {@snippet lang=c :
     * cef_string_userfree_t (*get_method)(struct _cef_request_t *) __attribute__((stdcall))
     * }
     */
    public final static class get_method {

        private get_method() {
            // Should not be called directly
        }

        /**
         * The function pointer signature, expressed as a functional interface
         */
        public interface Function {
            MemorySegment apply(MemorySegment _x0);
        }

        private static final FunctionDescriptor $DESC = FunctionDescriptor.of(
            cef_render_handler_capi_h.C_POINTER,
            cef_render_handler_capi_h.C_POINTER
        );

        /**
         * The descriptor of this function pointer
         */
        public static FunctionDescriptor descriptor() {
            return $DESC;
        }

        private static final MethodHandle UP$MH = cef_render_handler_capi_h.upcallHandle(get_method.Function.class, "apply", $DESC);

        /**
         * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
         * The lifetime of the returned segment is managed by {@code arena}
         */
        public static MemorySegment allocate(get_method.Function fi, Arena arena) {
            return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
        }

        private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

        /**
         * Invoke the upcall stub {@code funcPtr}, with given parameters
         */
        public static MemorySegment invoke(MemorySegment funcPtr, MemorySegment _x0) {
            try {
                return (MemorySegment) DOWN$MH.invokeExact(funcPtr, _x0);
            } catch (Error | RuntimeException ex) {
                throw ex;
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        }
    }

    private static final AddressLayout get_method$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("get_method"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * cef_string_userfree_t (*get_method)(struct _cef_request_t *) __attribute__((stdcall))
     * }
     */
    public static final AddressLayout get_method$layout() {
        return get_method$LAYOUT;
    }

    private static final long get_method$OFFSET = $LAYOUT.byteOffset(groupElement("get_method"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * cef_string_userfree_t (*get_method)(struct _cef_request_t *) __attribute__((stdcall))
     * }
     */
    public static final long get_method$offset() {
        return get_method$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * cef_string_userfree_t (*get_method)(struct _cef_request_t *) __attribute__((stdcall))
     * }
     */
    public static MemorySegment get_method(MemorySegment struct) {
        return struct.get(get_method$LAYOUT, get_method$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * cef_string_userfree_t (*get_method)(struct _cef_request_t *) __attribute__((stdcall))
     * }
     */
    public static void get_method(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(get_method$LAYOUT, get_method$OFFSET, fieldValue);
    }

    /**
     * {@snippet lang=c :
     * void (*set_method)(struct _cef_request_t *, const cef_string_t *) __attribute__((stdcall))
     * }
     */
    public final static class set_method {

        private set_method() {
            // Should not be called directly
        }

        /**
         * The function pointer signature, expressed as a functional interface
         */
        public interface Function {
            void apply(MemorySegment _x0, MemorySegment _x1);
        }

        private static final FunctionDescriptor $DESC = FunctionDescriptor.ofVoid(
            cef_render_handler_capi_h.C_POINTER,
            cef_render_handler_capi_h.C_POINTER
        );

        /**
         * The descriptor of this function pointer
         */
        public static FunctionDescriptor descriptor() {
            return $DESC;
        }

        private static final MethodHandle UP$MH = cef_render_handler_capi_h.upcallHandle(set_method.Function.class, "apply", $DESC);

        /**
         * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
         * The lifetime of the returned segment is managed by {@code arena}
         */
        public static MemorySegment allocate(set_method.Function fi, Arena arena) {
            return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
        }

        private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

        /**
         * Invoke the upcall stub {@code funcPtr}, with given parameters
         */
        public static void invoke(MemorySegment funcPtr, MemorySegment _x0, MemorySegment _x1) {
            try {
                 DOWN$MH.invokeExact(funcPtr, _x0, _x1);
            } catch (Error | RuntimeException ex) {
                throw ex;
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        }
    }

    private static final AddressLayout set_method$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("set_method"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * void (*set_method)(struct _cef_request_t *, const cef_string_t *) __attribute__((stdcall))
     * }
     */
    public static final AddressLayout set_method$layout() {
        return set_method$LAYOUT;
    }

    private static final long set_method$OFFSET = $LAYOUT.byteOffset(groupElement("set_method"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * void (*set_method)(struct _cef_request_t *, const cef_string_t *) __attribute__((stdcall))
     * }
     */
    public static final long set_method$offset() {
        return set_method$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * void (*set_method)(struct _cef_request_t *, const cef_string_t *) __attribute__((stdcall))
     * }
     */
    public static MemorySegment set_method(MemorySegment struct) {
        return struct.get(set_method$LAYOUT, set_method$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * void (*set_method)(struct _cef_request_t *, const cef_string_t *) __attribute__((stdcall))
     * }
     */
    public static void set_method(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(set_method$LAYOUT, set_method$OFFSET, fieldValue);
    }

    /**
     * {@snippet lang=c :
     * void (*set_referrer)(struct _cef_request_t *, const cef_string_t *, cef_referrer_policy_t) __attribute__((stdcall))
     * }
     */
    public final static class set_referrer {

        private set_referrer() {
            // Should not be called directly
        }

        /**
         * The function pointer signature, expressed as a functional interface
         */
        public interface Function {
            void apply(MemorySegment _x0, MemorySegment _x1, int _x2);
        }

        private static final FunctionDescriptor $DESC = FunctionDescriptor.ofVoid(
            cef_render_handler_capi_h.C_POINTER,
            cef_render_handler_capi_h.C_POINTER,
            cef_render_handler_capi_h.C_INT
        );

        /**
         * The descriptor of this function pointer
         */
        public static FunctionDescriptor descriptor() {
            return $DESC;
        }

        private static final MethodHandle UP$MH = cef_render_handler_capi_h.upcallHandle(set_referrer.Function.class, "apply", $DESC);

        /**
         * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
         * The lifetime of the returned segment is managed by {@code arena}
         */
        public static MemorySegment allocate(set_referrer.Function fi, Arena arena) {
            return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
        }

        private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

        /**
         * Invoke the upcall stub {@code funcPtr}, with given parameters
         */
        public static void invoke(MemorySegment funcPtr, MemorySegment _x0, MemorySegment _x1, int _x2) {
            try {
                 DOWN$MH.invokeExact(funcPtr, _x0, _x1, _x2);
            } catch (Error | RuntimeException ex) {
                throw ex;
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        }
    }

    private static final AddressLayout set_referrer$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("set_referrer"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * void (*set_referrer)(struct _cef_request_t *, const cef_string_t *, cef_referrer_policy_t) __attribute__((stdcall))
     * }
     */
    public static final AddressLayout set_referrer$layout() {
        return set_referrer$LAYOUT;
    }

    private static final long set_referrer$OFFSET = $LAYOUT.byteOffset(groupElement("set_referrer"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * void (*set_referrer)(struct _cef_request_t *, const cef_string_t *, cef_referrer_policy_t) __attribute__((stdcall))
     * }
     */
    public static final long set_referrer$offset() {
        return set_referrer$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * void (*set_referrer)(struct _cef_request_t *, const cef_string_t *, cef_referrer_policy_t) __attribute__((stdcall))
     * }
     */
    public static MemorySegment set_referrer(MemorySegment struct) {
        return struct.get(set_referrer$LAYOUT, set_referrer$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * void (*set_referrer)(struct _cef_request_t *, const cef_string_t *, cef_referrer_policy_t) __attribute__((stdcall))
     * }
     */
    public static void set_referrer(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(set_referrer$LAYOUT, set_referrer$OFFSET, fieldValue);
    }

    /**
     * {@snippet lang=c :
     * cef_string_userfree_t (*get_referrer_url)(struct _cef_request_t *) __attribute__((stdcall))
     * }
     */
    public final static class get_referrer_url {

        private get_referrer_url() {
            // Should not be called directly
        }

        /**
         * The function pointer signature, expressed as a functional interface
         */
        public interface Function {
            MemorySegment apply(MemorySegment _x0);
        }

        private static final FunctionDescriptor $DESC = FunctionDescriptor.of(
            cef_render_handler_capi_h.C_POINTER,
            cef_render_handler_capi_h.C_POINTER
        );

        /**
         * The descriptor of this function pointer
         */
        public static FunctionDescriptor descriptor() {
            return $DESC;
        }

        private static final MethodHandle UP$MH = cef_render_handler_capi_h.upcallHandle(get_referrer_url.Function.class, "apply", $DESC);

        /**
         * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
         * The lifetime of the returned segment is managed by {@code arena}
         */
        public static MemorySegment allocate(get_referrer_url.Function fi, Arena arena) {
            return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
        }

        private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

        /**
         * Invoke the upcall stub {@code funcPtr}, with given parameters
         */
        public static MemorySegment invoke(MemorySegment funcPtr, MemorySegment _x0) {
            try {
                return (MemorySegment) DOWN$MH.invokeExact(funcPtr, _x0);
            } catch (Error | RuntimeException ex) {
                throw ex;
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        }
    }

    private static final AddressLayout get_referrer_url$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("get_referrer_url"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * cef_string_userfree_t (*get_referrer_url)(struct _cef_request_t *) __attribute__((stdcall))
     * }
     */
    public static final AddressLayout get_referrer_url$layout() {
        return get_referrer_url$LAYOUT;
    }

    private static final long get_referrer_url$OFFSET = $LAYOUT.byteOffset(groupElement("get_referrer_url"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * cef_string_userfree_t (*get_referrer_url)(struct _cef_request_t *) __attribute__((stdcall))
     * }
     */
    public static final long get_referrer_url$offset() {
        return get_referrer_url$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * cef_string_userfree_t (*get_referrer_url)(struct _cef_request_t *) __attribute__((stdcall))
     * }
     */
    public static MemorySegment get_referrer_url(MemorySegment struct) {
        return struct.get(get_referrer_url$LAYOUT, get_referrer_url$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * cef_string_userfree_t (*get_referrer_url)(struct _cef_request_t *) __attribute__((stdcall))
     * }
     */
    public static void get_referrer_url(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(get_referrer_url$LAYOUT, get_referrer_url$OFFSET, fieldValue);
    }

    /**
     * {@snippet lang=c :
     * cef_referrer_policy_t (*get_referrer_policy)(struct _cef_request_t *) __attribute__((stdcall))
     * }
     */
    public final static class get_referrer_policy {

        private get_referrer_policy() {
            // Should not be called directly
        }

        /**
         * The function pointer signature, expressed as a functional interface
         */
        public interface Function {
            int apply(MemorySegment _x0);
        }

        private static final FunctionDescriptor $DESC = FunctionDescriptor.of(
            cef_render_handler_capi_h.C_INT,
            cef_render_handler_capi_h.C_POINTER
        );

        /**
         * The descriptor of this function pointer
         */
        public static FunctionDescriptor descriptor() {
            return $DESC;
        }

        private static final MethodHandle UP$MH = cef_render_handler_capi_h.upcallHandle(get_referrer_policy.Function.class, "apply", $DESC);

        /**
         * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
         * The lifetime of the returned segment is managed by {@code arena}
         */
        public static MemorySegment allocate(get_referrer_policy.Function fi, Arena arena) {
            return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
        }

        private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

        /**
         * Invoke the upcall stub {@code funcPtr}, with given parameters
         */
        public static int invoke(MemorySegment funcPtr, MemorySegment _x0) {
            try {
                return (int) DOWN$MH.invokeExact(funcPtr, _x0);
            } catch (Error | RuntimeException ex) {
                throw ex;
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        }
    }

    private static final AddressLayout get_referrer_policy$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("get_referrer_policy"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * cef_referrer_policy_t (*get_referrer_policy)(struct _cef_request_t *) __attribute__((stdcall))
     * }
     */
    public static final AddressLayout get_referrer_policy$layout() {
        return get_referrer_policy$LAYOUT;
    }

    private static final long get_referrer_policy$OFFSET = $LAYOUT.byteOffset(groupElement("get_referrer_policy"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * cef_referrer_policy_t (*get_referrer_policy)(struct _cef_request_t *) __attribute__((stdcall))
     * }
     */
    public static final long get_referrer_policy$offset() {
        return get_referrer_policy$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * cef_referrer_policy_t (*get_referrer_policy)(struct _cef_request_t *) __attribute__((stdcall))
     * }
     */
    public static MemorySegment get_referrer_policy(MemorySegment struct) {
        return struct.get(get_referrer_policy$LAYOUT, get_referrer_policy$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * cef_referrer_policy_t (*get_referrer_policy)(struct _cef_request_t *) __attribute__((stdcall))
     * }
     */
    public static void get_referrer_policy(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(get_referrer_policy$LAYOUT, get_referrer_policy$OFFSET, fieldValue);
    }

    /**
     * {@snippet lang=c :
     * struct _cef_post_data_t *(*get_post_data)(struct _cef_request_t *) __attribute__((stdcall))
     * }
     */
    public final static class get_post_data {

        private get_post_data() {
            // Should not be called directly
        }

        /**
         * The function pointer signature, expressed as a functional interface
         */
        public interface Function {
            MemorySegment apply(MemorySegment _x0);
        }

        private static final FunctionDescriptor $DESC = FunctionDescriptor.of(
            cef_render_handler_capi_h.C_POINTER,
            cef_render_handler_capi_h.C_POINTER
        );

        /**
         * The descriptor of this function pointer
         */
        public static FunctionDescriptor descriptor() {
            return $DESC;
        }

        private static final MethodHandle UP$MH = cef_render_handler_capi_h.upcallHandle(get_post_data.Function.class, "apply", $DESC);

        /**
         * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
         * The lifetime of the returned segment is managed by {@code arena}
         */
        public static MemorySegment allocate(get_post_data.Function fi, Arena arena) {
            return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
        }

        private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

        /**
         * Invoke the upcall stub {@code funcPtr}, with given parameters
         */
        public static MemorySegment invoke(MemorySegment funcPtr, MemorySegment _x0) {
            try {
                return (MemorySegment) DOWN$MH.invokeExact(funcPtr, _x0);
            } catch (Error | RuntimeException ex) {
                throw ex;
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        }
    }

    private static final AddressLayout get_post_data$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("get_post_data"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * struct _cef_post_data_t *(*get_post_data)(struct _cef_request_t *) __attribute__((stdcall))
     * }
     */
    public static final AddressLayout get_post_data$layout() {
        return get_post_data$LAYOUT;
    }

    private static final long get_post_data$OFFSET = $LAYOUT.byteOffset(groupElement("get_post_data"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * struct _cef_post_data_t *(*get_post_data)(struct _cef_request_t *) __attribute__((stdcall))
     * }
     */
    public static final long get_post_data$offset() {
        return get_post_data$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * struct _cef_post_data_t *(*get_post_data)(struct _cef_request_t *) __attribute__((stdcall))
     * }
     */
    public static MemorySegment get_post_data(MemorySegment struct) {
        return struct.get(get_post_data$LAYOUT, get_post_data$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * struct _cef_post_data_t *(*get_post_data)(struct _cef_request_t *) __attribute__((stdcall))
     * }
     */
    public static void get_post_data(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(get_post_data$LAYOUT, get_post_data$OFFSET, fieldValue);
    }

    /**
     * {@snippet lang=c :
     * void (*set_post_data)(struct _cef_request_t *, struct _cef_post_data_t *) __attribute__((stdcall))
     * }
     */
    public final static class set_post_data {

        private set_post_data() {
            // Should not be called directly
        }

        /**
         * The function pointer signature, expressed as a functional interface
         */
        public interface Function {
            void apply(MemorySegment _x0, MemorySegment _x1);
        }

        private static final FunctionDescriptor $DESC = FunctionDescriptor.ofVoid(
            cef_render_handler_capi_h.C_POINTER,
            cef_render_handler_capi_h.C_POINTER
        );

        /**
         * The descriptor of this function pointer
         */
        public static FunctionDescriptor descriptor() {
            return $DESC;
        }

        private static final MethodHandle UP$MH = cef_render_handler_capi_h.upcallHandle(set_post_data.Function.class, "apply", $DESC);

        /**
         * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
         * The lifetime of the returned segment is managed by {@code arena}
         */
        public static MemorySegment allocate(set_post_data.Function fi, Arena arena) {
            return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
        }

        private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

        /**
         * Invoke the upcall stub {@code funcPtr}, with given parameters
         */
        public static void invoke(MemorySegment funcPtr, MemorySegment _x0, MemorySegment _x1) {
            try {
                 DOWN$MH.invokeExact(funcPtr, _x0, _x1);
            } catch (Error | RuntimeException ex) {
                throw ex;
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        }
    }

    private static final AddressLayout set_post_data$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("set_post_data"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * void (*set_post_data)(struct _cef_request_t *, struct _cef_post_data_t *) __attribute__((stdcall))
     * }
     */
    public static final AddressLayout set_post_data$layout() {
        return set_post_data$LAYOUT;
    }

    private static final long set_post_data$OFFSET = $LAYOUT.byteOffset(groupElement("set_post_data"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * void (*set_post_data)(struct _cef_request_t *, struct _cef_post_data_t *) __attribute__((stdcall))
     * }
     */
    public static final long set_post_data$offset() {
        return set_post_data$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * void (*set_post_data)(struct _cef_request_t *, struct _cef_post_data_t *) __attribute__((stdcall))
     * }
     */
    public static MemorySegment set_post_data(MemorySegment struct) {
        return struct.get(set_post_data$LAYOUT, set_post_data$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * void (*set_post_data)(struct _cef_request_t *, struct _cef_post_data_t *) __attribute__((stdcall))
     * }
     */
    public static void set_post_data(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(set_post_data$LAYOUT, set_post_data$OFFSET, fieldValue);
    }

    /**
     * {@snippet lang=c :
     * void (*get_header_map)(struct _cef_request_t *, cef_string_multimap_t) __attribute__((stdcall))
     * }
     */
    public final static class get_header_map {

        private get_header_map() {
            // Should not be called directly
        }

        /**
         * The function pointer signature, expressed as a functional interface
         */
        public interface Function {
            void apply(MemorySegment _x0, MemorySegment _x1);
        }

        private static final FunctionDescriptor $DESC = FunctionDescriptor.ofVoid(
            cef_render_handler_capi_h.C_POINTER,
            cef_render_handler_capi_h.C_POINTER
        );

        /**
         * The descriptor of this function pointer
         */
        public static FunctionDescriptor descriptor() {
            return $DESC;
        }

        private static final MethodHandle UP$MH = cef_render_handler_capi_h.upcallHandle(get_header_map.Function.class, "apply", $DESC);

        /**
         * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
         * The lifetime of the returned segment is managed by {@code arena}
         */
        public static MemorySegment allocate(get_header_map.Function fi, Arena arena) {
            return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
        }

        private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

        /**
         * Invoke the upcall stub {@code funcPtr}, with given parameters
         */
        public static void invoke(MemorySegment funcPtr, MemorySegment _x0, MemorySegment _x1) {
            try {
                 DOWN$MH.invokeExact(funcPtr, _x0, _x1);
            } catch (Error | RuntimeException ex) {
                throw ex;
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        }
    }

    private static final AddressLayout get_header_map$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("get_header_map"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * void (*get_header_map)(struct _cef_request_t *, cef_string_multimap_t) __attribute__((stdcall))
     * }
     */
    public static final AddressLayout get_header_map$layout() {
        return get_header_map$LAYOUT;
    }

    private static final long get_header_map$OFFSET = $LAYOUT.byteOffset(groupElement("get_header_map"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * void (*get_header_map)(struct _cef_request_t *, cef_string_multimap_t) __attribute__((stdcall))
     * }
     */
    public static final long get_header_map$offset() {
        return get_header_map$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * void (*get_header_map)(struct _cef_request_t *, cef_string_multimap_t) __attribute__((stdcall))
     * }
     */
    public static MemorySegment get_header_map(MemorySegment struct) {
        return struct.get(get_header_map$LAYOUT, get_header_map$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * void (*get_header_map)(struct _cef_request_t *, cef_string_multimap_t) __attribute__((stdcall))
     * }
     */
    public static void get_header_map(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(get_header_map$LAYOUT, get_header_map$OFFSET, fieldValue);
    }

    /**
     * {@snippet lang=c :
     * void (*set_header_map)(struct _cef_request_t *, cef_string_multimap_t) __attribute__((stdcall))
     * }
     */
    public final static class set_header_map {

        private set_header_map() {
            // Should not be called directly
        }

        /**
         * The function pointer signature, expressed as a functional interface
         */
        public interface Function {
            void apply(MemorySegment _x0, MemorySegment _x1);
        }

        private static final FunctionDescriptor $DESC = FunctionDescriptor.ofVoid(
            cef_render_handler_capi_h.C_POINTER,
            cef_render_handler_capi_h.C_POINTER
        );

        /**
         * The descriptor of this function pointer
         */
        public static FunctionDescriptor descriptor() {
            return $DESC;
        }

        private static final MethodHandle UP$MH = cef_render_handler_capi_h.upcallHandle(set_header_map.Function.class, "apply", $DESC);

        /**
         * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
         * The lifetime of the returned segment is managed by {@code arena}
         */
        public static MemorySegment allocate(set_header_map.Function fi, Arena arena) {
            return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
        }

        private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

        /**
         * Invoke the upcall stub {@code funcPtr}, with given parameters
         */
        public static void invoke(MemorySegment funcPtr, MemorySegment _x0, MemorySegment _x1) {
            try {
                 DOWN$MH.invokeExact(funcPtr, _x0, _x1);
            } catch (Error | RuntimeException ex) {
                throw ex;
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        }
    }

    private static final AddressLayout set_header_map$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("set_header_map"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * void (*set_header_map)(struct _cef_request_t *, cef_string_multimap_t) __attribute__((stdcall))
     * }
     */
    public static final AddressLayout set_header_map$layout() {
        return set_header_map$LAYOUT;
    }

    private static final long set_header_map$OFFSET = $LAYOUT.byteOffset(groupElement("set_header_map"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * void (*set_header_map)(struct _cef_request_t *, cef_string_multimap_t) __attribute__((stdcall))
     * }
     */
    public static final long set_header_map$offset() {
        return set_header_map$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * void (*set_header_map)(struct _cef_request_t *, cef_string_multimap_t) __attribute__((stdcall))
     * }
     */
    public static MemorySegment set_header_map(MemorySegment struct) {
        return struct.get(set_header_map$LAYOUT, set_header_map$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * void (*set_header_map)(struct _cef_request_t *, cef_string_multimap_t) __attribute__((stdcall))
     * }
     */
    public static void set_header_map(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(set_header_map$LAYOUT, set_header_map$OFFSET, fieldValue);
    }

    /**
     * {@snippet lang=c :
     * cef_string_userfree_t (*get_header_by_name)(struct _cef_request_t *, const cef_string_t *) __attribute__((stdcall))
     * }
     */
    public final static class get_header_by_name {

        private get_header_by_name() {
            // Should not be called directly
        }

        /**
         * The function pointer signature, expressed as a functional interface
         */
        public interface Function {
            MemorySegment apply(MemorySegment _x0, MemorySegment _x1);
        }

        private static final FunctionDescriptor $DESC = FunctionDescriptor.of(
            cef_render_handler_capi_h.C_POINTER,
            cef_render_handler_capi_h.C_POINTER,
            cef_render_handler_capi_h.C_POINTER
        );

        /**
         * The descriptor of this function pointer
         */
        public static FunctionDescriptor descriptor() {
            return $DESC;
        }

        private static final MethodHandle UP$MH = cef_render_handler_capi_h.upcallHandle(get_header_by_name.Function.class, "apply", $DESC);

        /**
         * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
         * The lifetime of the returned segment is managed by {@code arena}
         */
        public static MemorySegment allocate(get_header_by_name.Function fi, Arena arena) {
            return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
        }

        private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

        /**
         * Invoke the upcall stub {@code funcPtr}, with given parameters
         */
        public static MemorySegment invoke(MemorySegment funcPtr, MemorySegment _x0, MemorySegment _x1) {
            try {
                return (MemorySegment) DOWN$MH.invokeExact(funcPtr, _x0, _x1);
            } catch (Error | RuntimeException ex) {
                throw ex;
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        }
    }

    private static final AddressLayout get_header_by_name$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("get_header_by_name"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * cef_string_userfree_t (*get_header_by_name)(struct _cef_request_t *, const cef_string_t *) __attribute__((stdcall))
     * }
     */
    public static final AddressLayout get_header_by_name$layout() {
        return get_header_by_name$LAYOUT;
    }

    private static final long get_header_by_name$OFFSET = $LAYOUT.byteOffset(groupElement("get_header_by_name"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * cef_string_userfree_t (*get_header_by_name)(struct _cef_request_t *, const cef_string_t *) __attribute__((stdcall))
     * }
     */
    public static final long get_header_by_name$offset() {
        return get_header_by_name$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * cef_string_userfree_t (*get_header_by_name)(struct _cef_request_t *, const cef_string_t *) __attribute__((stdcall))
     * }
     */
    public static MemorySegment get_header_by_name(MemorySegment struct) {
        return struct.get(get_header_by_name$LAYOUT, get_header_by_name$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * cef_string_userfree_t (*get_header_by_name)(struct _cef_request_t *, const cef_string_t *) __attribute__((stdcall))
     * }
     */
    public static void get_header_by_name(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(get_header_by_name$LAYOUT, get_header_by_name$OFFSET, fieldValue);
    }

    /**
     * {@snippet lang=c :
     * void (*set_header_by_name)(struct _cef_request_t *, const cef_string_t *, const cef_string_t *, int) __attribute__((stdcall))
     * }
     */
    public final static class set_header_by_name {

        private set_header_by_name() {
            // Should not be called directly
        }

        /**
         * The function pointer signature, expressed as a functional interface
         */
        public interface Function {
            void apply(MemorySegment _x0, MemorySegment _x1, MemorySegment _x2, int _x3);
        }

        private static final FunctionDescriptor $DESC = FunctionDescriptor.ofVoid(
            cef_render_handler_capi_h.C_POINTER,
            cef_render_handler_capi_h.C_POINTER,
            cef_render_handler_capi_h.C_POINTER,
            cef_render_handler_capi_h.C_INT
        );

        /**
         * The descriptor of this function pointer
         */
        public static FunctionDescriptor descriptor() {
            return $DESC;
        }

        private static final MethodHandle UP$MH = cef_render_handler_capi_h.upcallHandle(set_header_by_name.Function.class, "apply", $DESC);

        /**
         * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
         * The lifetime of the returned segment is managed by {@code arena}
         */
        public static MemorySegment allocate(set_header_by_name.Function fi, Arena arena) {
            return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
        }

        private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

        /**
         * Invoke the upcall stub {@code funcPtr}, with given parameters
         */
        public static void invoke(MemorySegment funcPtr, MemorySegment _x0, MemorySegment _x1, MemorySegment _x2, int _x3) {
            try {
                 DOWN$MH.invokeExact(funcPtr, _x0, _x1, _x2, _x3);
            } catch (Error | RuntimeException ex) {
                throw ex;
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        }
    }

    private static final AddressLayout set_header_by_name$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("set_header_by_name"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * void (*set_header_by_name)(struct _cef_request_t *, const cef_string_t *, const cef_string_t *, int) __attribute__((stdcall))
     * }
     */
    public static final AddressLayout set_header_by_name$layout() {
        return set_header_by_name$LAYOUT;
    }

    private static final long set_header_by_name$OFFSET = $LAYOUT.byteOffset(groupElement("set_header_by_name"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * void (*set_header_by_name)(struct _cef_request_t *, const cef_string_t *, const cef_string_t *, int) __attribute__((stdcall))
     * }
     */
    public static final long set_header_by_name$offset() {
        return set_header_by_name$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * void (*set_header_by_name)(struct _cef_request_t *, const cef_string_t *, const cef_string_t *, int) __attribute__((stdcall))
     * }
     */
    public static MemorySegment set_header_by_name(MemorySegment struct) {
        return struct.get(set_header_by_name$LAYOUT, set_header_by_name$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * void (*set_header_by_name)(struct _cef_request_t *, const cef_string_t *, const cef_string_t *, int) __attribute__((stdcall))
     * }
     */
    public static void set_header_by_name(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(set_header_by_name$LAYOUT, set_header_by_name$OFFSET, fieldValue);
    }

    /**
     * {@snippet lang=c :
     * void (*set)(struct _cef_request_t *, const cef_string_t *, const cef_string_t *, struct _cef_post_data_t *, cef_string_multimap_t) __attribute__((stdcall))
     * }
     */
    public final static class set {

        private set() {
            // Should not be called directly
        }

        /**
         * The function pointer signature, expressed as a functional interface
         */
        public interface Function {
            void apply(MemorySegment _x0, MemorySegment _x1, MemorySegment _x2, MemorySegment _x3, MemorySegment _x4);
        }

        private static final FunctionDescriptor $DESC = FunctionDescriptor.ofVoid(
            cef_render_handler_capi_h.C_POINTER,
            cef_render_handler_capi_h.C_POINTER,
            cef_render_handler_capi_h.C_POINTER,
            cef_render_handler_capi_h.C_POINTER,
            cef_render_handler_capi_h.C_POINTER
        );

        /**
         * The descriptor of this function pointer
         */
        public static FunctionDescriptor descriptor() {
            return $DESC;
        }

        private static final MethodHandle UP$MH = cef_render_handler_capi_h.upcallHandle(set.Function.class, "apply", $DESC);

        /**
         * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
         * The lifetime of the returned segment is managed by {@code arena}
         */
        public static MemorySegment allocate(set.Function fi, Arena arena) {
            return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
        }

        private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

        /**
         * Invoke the upcall stub {@code funcPtr}, with given parameters
         */
        public static void invoke(MemorySegment funcPtr, MemorySegment _x0, MemorySegment _x1, MemorySegment _x2, MemorySegment _x3, MemorySegment _x4) {
            try {
                 DOWN$MH.invokeExact(funcPtr, _x0, _x1, _x2, _x3, _x4);
            } catch (Error | RuntimeException ex) {
                throw ex;
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        }
    }

    private static final AddressLayout set$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("set"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * void (*set)(struct _cef_request_t *, const cef_string_t *, const cef_string_t *, struct _cef_post_data_t *, cef_string_multimap_t) __attribute__((stdcall))
     * }
     */
    public static final AddressLayout set$layout() {
        return set$LAYOUT;
    }

    private static final long set$OFFSET = $LAYOUT.byteOffset(groupElement("set"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * void (*set)(struct _cef_request_t *, const cef_string_t *, const cef_string_t *, struct _cef_post_data_t *, cef_string_multimap_t) __attribute__((stdcall))
     * }
     */
    public static final long set$offset() {
        return set$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * void (*set)(struct _cef_request_t *, const cef_string_t *, const cef_string_t *, struct _cef_post_data_t *, cef_string_multimap_t) __attribute__((stdcall))
     * }
     */
    public static MemorySegment set(MemorySegment struct) {
        return struct.get(set$LAYOUT, set$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * void (*set)(struct _cef_request_t *, const cef_string_t *, const cef_string_t *, struct _cef_post_data_t *, cef_string_multimap_t) __attribute__((stdcall))
     * }
     */
    public static void set(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(set$LAYOUT, set$OFFSET, fieldValue);
    }

    /**
     * {@snippet lang=c :
     * int (*get_flags)(struct _cef_request_t *) __attribute__((stdcall))
     * }
     */
    public final static class get_flags {

        private get_flags() {
            // Should not be called directly
        }

        /**
         * The function pointer signature, expressed as a functional interface
         */
        public interface Function {
            int apply(MemorySegment _x0);
        }

        private static final FunctionDescriptor $DESC = FunctionDescriptor.of(
            cef_render_handler_capi_h.C_INT,
            cef_render_handler_capi_h.C_POINTER
        );

        /**
         * The descriptor of this function pointer
         */
        public static FunctionDescriptor descriptor() {
            return $DESC;
        }

        private static final MethodHandle UP$MH = cef_render_handler_capi_h.upcallHandle(get_flags.Function.class, "apply", $DESC);

        /**
         * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
         * The lifetime of the returned segment is managed by {@code arena}
         */
        public static MemorySegment allocate(get_flags.Function fi, Arena arena) {
            return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
        }

        private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

        /**
         * Invoke the upcall stub {@code funcPtr}, with given parameters
         */
        public static int invoke(MemorySegment funcPtr, MemorySegment _x0) {
            try {
                return (int) DOWN$MH.invokeExact(funcPtr, _x0);
            } catch (Error | RuntimeException ex) {
                throw ex;
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        }
    }

    private static final AddressLayout get_flags$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("get_flags"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int (*get_flags)(struct _cef_request_t *) __attribute__((stdcall))
     * }
     */
    public static final AddressLayout get_flags$layout() {
        return get_flags$LAYOUT;
    }

    private static final long get_flags$OFFSET = $LAYOUT.byteOffset(groupElement("get_flags"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int (*get_flags)(struct _cef_request_t *) __attribute__((stdcall))
     * }
     */
    public static final long get_flags$offset() {
        return get_flags$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int (*get_flags)(struct _cef_request_t *) __attribute__((stdcall))
     * }
     */
    public static MemorySegment get_flags(MemorySegment struct) {
        return struct.get(get_flags$LAYOUT, get_flags$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int (*get_flags)(struct _cef_request_t *) __attribute__((stdcall))
     * }
     */
    public static void get_flags(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(get_flags$LAYOUT, get_flags$OFFSET, fieldValue);
    }

    /**
     * {@snippet lang=c :
     * void (*set_flags)(struct _cef_request_t *, int) __attribute__((stdcall))
     * }
     */
    public final static class set_flags {

        private set_flags() {
            // Should not be called directly
        }

        /**
         * The function pointer signature, expressed as a functional interface
         */
        public interface Function {
            void apply(MemorySegment _x0, int _x1);
        }

        private static final FunctionDescriptor $DESC = FunctionDescriptor.ofVoid(
            cef_render_handler_capi_h.C_POINTER,
            cef_render_handler_capi_h.C_INT
        );

        /**
         * The descriptor of this function pointer
         */
        public static FunctionDescriptor descriptor() {
            return $DESC;
        }

        private static final MethodHandle UP$MH = cef_render_handler_capi_h.upcallHandle(set_flags.Function.class, "apply", $DESC);

        /**
         * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
         * The lifetime of the returned segment is managed by {@code arena}
         */
        public static MemorySegment allocate(set_flags.Function fi, Arena arena) {
            return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
        }

        private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

        /**
         * Invoke the upcall stub {@code funcPtr}, with given parameters
         */
        public static void invoke(MemorySegment funcPtr, MemorySegment _x0, int _x1) {
            try {
                 DOWN$MH.invokeExact(funcPtr, _x0, _x1);
            } catch (Error | RuntimeException ex) {
                throw ex;
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        }
    }

    private static final AddressLayout set_flags$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("set_flags"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * void (*set_flags)(struct _cef_request_t *, int) __attribute__((stdcall))
     * }
     */
    public static final AddressLayout set_flags$layout() {
        return set_flags$LAYOUT;
    }

    private static final long set_flags$OFFSET = $LAYOUT.byteOffset(groupElement("set_flags"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * void (*set_flags)(struct _cef_request_t *, int) __attribute__((stdcall))
     * }
     */
    public static final long set_flags$offset() {
        return set_flags$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * void (*set_flags)(struct _cef_request_t *, int) __attribute__((stdcall))
     * }
     */
    public static MemorySegment set_flags(MemorySegment struct) {
        return struct.get(set_flags$LAYOUT, set_flags$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * void (*set_flags)(struct _cef_request_t *, int) __attribute__((stdcall))
     * }
     */
    public static void set_flags(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(set_flags$LAYOUT, set_flags$OFFSET, fieldValue);
    }

    /**
     * {@snippet lang=c :
     * cef_string_userfree_t (*get_first_party_for_cookies)(struct _cef_request_t *) __attribute__((stdcall))
     * }
     */
    public final static class get_first_party_for_cookies {

        private get_first_party_for_cookies() {
            // Should not be called directly
        }

        /**
         * The function pointer signature, expressed as a functional interface
         */
        public interface Function {
            MemorySegment apply(MemorySegment _x0);
        }

        private static final FunctionDescriptor $DESC = FunctionDescriptor.of(
            cef_render_handler_capi_h.C_POINTER,
            cef_render_handler_capi_h.C_POINTER
        );

        /**
         * The descriptor of this function pointer
         */
        public static FunctionDescriptor descriptor() {
            return $DESC;
        }

        private static final MethodHandle UP$MH = cef_render_handler_capi_h.upcallHandle(get_first_party_for_cookies.Function.class, "apply", $DESC);

        /**
         * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
         * The lifetime of the returned segment is managed by {@code arena}
         */
        public static MemorySegment allocate(get_first_party_for_cookies.Function fi, Arena arena) {
            return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
        }

        private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

        /**
         * Invoke the upcall stub {@code funcPtr}, with given parameters
         */
        public static MemorySegment invoke(MemorySegment funcPtr, MemorySegment _x0) {
            try {
                return (MemorySegment) DOWN$MH.invokeExact(funcPtr, _x0);
            } catch (Error | RuntimeException ex) {
                throw ex;
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        }
    }

    private static final AddressLayout get_first_party_for_cookies$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("get_first_party_for_cookies"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * cef_string_userfree_t (*get_first_party_for_cookies)(struct _cef_request_t *) __attribute__((stdcall))
     * }
     */
    public static final AddressLayout get_first_party_for_cookies$layout() {
        return get_first_party_for_cookies$LAYOUT;
    }

    private static final long get_first_party_for_cookies$OFFSET = $LAYOUT.byteOffset(groupElement("get_first_party_for_cookies"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * cef_string_userfree_t (*get_first_party_for_cookies)(struct _cef_request_t *) __attribute__((stdcall))
     * }
     */
    public static final long get_first_party_for_cookies$offset() {
        return get_first_party_for_cookies$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * cef_string_userfree_t (*get_first_party_for_cookies)(struct _cef_request_t *) __attribute__((stdcall))
     * }
     */
    public static MemorySegment get_first_party_for_cookies(MemorySegment struct) {
        return struct.get(get_first_party_for_cookies$LAYOUT, get_first_party_for_cookies$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * cef_string_userfree_t (*get_first_party_for_cookies)(struct _cef_request_t *) __attribute__((stdcall))
     * }
     */
    public static void get_first_party_for_cookies(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(get_first_party_for_cookies$LAYOUT, get_first_party_for_cookies$OFFSET, fieldValue);
    }

    /**
     * {@snippet lang=c :
     * void (*set_first_party_for_cookies)(struct _cef_request_t *, const cef_string_t *) __attribute__((stdcall))
     * }
     */
    public final static class set_first_party_for_cookies {

        private set_first_party_for_cookies() {
            // Should not be called directly
        }

        /**
         * The function pointer signature, expressed as a functional interface
         */
        public interface Function {
            void apply(MemorySegment _x0, MemorySegment _x1);
        }

        private static final FunctionDescriptor $DESC = FunctionDescriptor.ofVoid(
            cef_render_handler_capi_h.C_POINTER,
            cef_render_handler_capi_h.C_POINTER
        );

        /**
         * The descriptor of this function pointer
         */
        public static FunctionDescriptor descriptor() {
            return $DESC;
        }

        private static final MethodHandle UP$MH = cef_render_handler_capi_h.upcallHandle(set_first_party_for_cookies.Function.class, "apply", $DESC);

        /**
         * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
         * The lifetime of the returned segment is managed by {@code arena}
         */
        public static MemorySegment allocate(set_first_party_for_cookies.Function fi, Arena arena) {
            return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
        }

        private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

        /**
         * Invoke the upcall stub {@code funcPtr}, with given parameters
         */
        public static void invoke(MemorySegment funcPtr, MemorySegment _x0, MemorySegment _x1) {
            try {
                 DOWN$MH.invokeExact(funcPtr, _x0, _x1);
            } catch (Error | RuntimeException ex) {
                throw ex;
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        }
    }

    private static final AddressLayout set_first_party_for_cookies$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("set_first_party_for_cookies"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * void (*set_first_party_for_cookies)(struct _cef_request_t *, const cef_string_t *) __attribute__((stdcall))
     * }
     */
    public static final AddressLayout set_first_party_for_cookies$layout() {
        return set_first_party_for_cookies$LAYOUT;
    }

    private static final long set_first_party_for_cookies$OFFSET = $LAYOUT.byteOffset(groupElement("set_first_party_for_cookies"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * void (*set_first_party_for_cookies)(struct _cef_request_t *, const cef_string_t *) __attribute__((stdcall))
     * }
     */
    public static final long set_first_party_for_cookies$offset() {
        return set_first_party_for_cookies$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * void (*set_first_party_for_cookies)(struct _cef_request_t *, const cef_string_t *) __attribute__((stdcall))
     * }
     */
    public static MemorySegment set_first_party_for_cookies(MemorySegment struct) {
        return struct.get(set_first_party_for_cookies$LAYOUT, set_first_party_for_cookies$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * void (*set_first_party_for_cookies)(struct _cef_request_t *, const cef_string_t *) __attribute__((stdcall))
     * }
     */
    public static void set_first_party_for_cookies(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(set_first_party_for_cookies$LAYOUT, set_first_party_for_cookies$OFFSET, fieldValue);
    }

    /**
     * {@snippet lang=c :
     * cef_resource_type_t (*get_resource_type)(struct _cef_request_t *) __attribute__((stdcall))
     * }
     */
    public final static class get_resource_type {

        private get_resource_type() {
            // Should not be called directly
        }

        /**
         * The function pointer signature, expressed as a functional interface
         */
        public interface Function {
            int apply(MemorySegment _x0);
        }

        private static final FunctionDescriptor $DESC = FunctionDescriptor.of(
            cef_render_handler_capi_h.C_INT,
            cef_render_handler_capi_h.C_POINTER
        );

        /**
         * The descriptor of this function pointer
         */
        public static FunctionDescriptor descriptor() {
            return $DESC;
        }

        private static final MethodHandle UP$MH = cef_render_handler_capi_h.upcallHandle(get_resource_type.Function.class, "apply", $DESC);

        /**
         * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
         * The lifetime of the returned segment is managed by {@code arena}
         */
        public static MemorySegment allocate(get_resource_type.Function fi, Arena arena) {
            return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
        }

        private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

        /**
         * Invoke the upcall stub {@code funcPtr}, with given parameters
         */
        public static int invoke(MemorySegment funcPtr, MemorySegment _x0) {
            try {
                return (int) DOWN$MH.invokeExact(funcPtr, _x0);
            } catch (Error | RuntimeException ex) {
                throw ex;
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        }
    }

    private static final AddressLayout get_resource_type$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("get_resource_type"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * cef_resource_type_t (*get_resource_type)(struct _cef_request_t *) __attribute__((stdcall))
     * }
     */
    public static final AddressLayout get_resource_type$layout() {
        return get_resource_type$LAYOUT;
    }

    private static final long get_resource_type$OFFSET = $LAYOUT.byteOffset(groupElement("get_resource_type"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * cef_resource_type_t (*get_resource_type)(struct _cef_request_t *) __attribute__((stdcall))
     * }
     */
    public static final long get_resource_type$offset() {
        return get_resource_type$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * cef_resource_type_t (*get_resource_type)(struct _cef_request_t *) __attribute__((stdcall))
     * }
     */
    public static MemorySegment get_resource_type(MemorySegment struct) {
        return struct.get(get_resource_type$LAYOUT, get_resource_type$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * cef_resource_type_t (*get_resource_type)(struct _cef_request_t *) __attribute__((stdcall))
     * }
     */
    public static void get_resource_type(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(get_resource_type$LAYOUT, get_resource_type$OFFSET, fieldValue);
    }

    /**
     * {@snippet lang=c :
     * cef_transition_type_t (*get_transition_type)(struct _cef_request_t *) __attribute__((stdcall))
     * }
     */
    public final static class get_transition_type {

        private get_transition_type() {
            // Should not be called directly
        }

        /**
         * The function pointer signature, expressed as a functional interface
         */
        public interface Function {
            int apply(MemorySegment _x0);
        }

        private static final FunctionDescriptor $DESC = FunctionDescriptor.of(
            cef_render_handler_capi_h.C_INT,
            cef_render_handler_capi_h.C_POINTER
        );

        /**
         * The descriptor of this function pointer
         */
        public static FunctionDescriptor descriptor() {
            return $DESC;
        }

        private static final MethodHandle UP$MH = cef_render_handler_capi_h.upcallHandle(get_transition_type.Function.class, "apply", $DESC);

        /**
         * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
         * The lifetime of the returned segment is managed by {@code arena}
         */
        public static MemorySegment allocate(get_transition_type.Function fi, Arena arena) {
            return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
        }

        private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

        /**
         * Invoke the upcall stub {@code funcPtr}, with given parameters
         */
        public static int invoke(MemorySegment funcPtr, MemorySegment _x0) {
            try {
                return (int) DOWN$MH.invokeExact(funcPtr, _x0);
            } catch (Error | RuntimeException ex) {
                throw ex;
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        }
    }

    private static final AddressLayout get_transition_type$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("get_transition_type"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * cef_transition_type_t (*get_transition_type)(struct _cef_request_t *) __attribute__((stdcall))
     * }
     */
    public static final AddressLayout get_transition_type$layout() {
        return get_transition_type$LAYOUT;
    }

    private static final long get_transition_type$OFFSET = $LAYOUT.byteOffset(groupElement("get_transition_type"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * cef_transition_type_t (*get_transition_type)(struct _cef_request_t *) __attribute__((stdcall))
     * }
     */
    public static final long get_transition_type$offset() {
        return get_transition_type$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * cef_transition_type_t (*get_transition_type)(struct _cef_request_t *) __attribute__((stdcall))
     * }
     */
    public static MemorySegment get_transition_type(MemorySegment struct) {
        return struct.get(get_transition_type$LAYOUT, get_transition_type$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * cef_transition_type_t (*get_transition_type)(struct _cef_request_t *) __attribute__((stdcall))
     * }
     */
    public static void get_transition_type(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(get_transition_type$LAYOUT, get_transition_type$OFFSET, fieldValue);
    }

    /**
     * {@snippet lang=c :
     * uint64_t (*get_identifier)(struct _cef_request_t *) __attribute__((stdcall))
     * }
     */
    public final static class get_identifier {

        private get_identifier() {
            // Should not be called directly
        }

        /**
         * The function pointer signature, expressed as a functional interface
         */
        public interface Function {
            long apply(MemorySegment _x0);
        }

        private static final FunctionDescriptor $DESC = FunctionDescriptor.of(
            cef_render_handler_capi_h.C_LONG_LONG,
            cef_render_handler_capi_h.C_POINTER
        );

        /**
         * The descriptor of this function pointer
         */
        public static FunctionDescriptor descriptor() {
            return $DESC;
        }

        private static final MethodHandle UP$MH = cef_render_handler_capi_h.upcallHandle(get_identifier.Function.class, "apply", $DESC);

        /**
         * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
         * The lifetime of the returned segment is managed by {@code arena}
         */
        public static MemorySegment allocate(get_identifier.Function fi, Arena arena) {
            return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
        }

        private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

        /**
         * Invoke the upcall stub {@code funcPtr}, with given parameters
         */
        public static long invoke(MemorySegment funcPtr, MemorySegment _x0) {
            try {
                return (long) DOWN$MH.invokeExact(funcPtr, _x0);
            } catch (Error | RuntimeException ex) {
                throw ex;
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        }
    }

    private static final AddressLayout get_identifier$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("get_identifier"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint64_t (*get_identifier)(struct _cef_request_t *) __attribute__((stdcall))
     * }
     */
    public static final AddressLayout get_identifier$layout() {
        return get_identifier$LAYOUT;
    }

    private static final long get_identifier$OFFSET = $LAYOUT.byteOffset(groupElement("get_identifier"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint64_t (*get_identifier)(struct _cef_request_t *) __attribute__((stdcall))
     * }
     */
    public static final long get_identifier$offset() {
        return get_identifier$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint64_t (*get_identifier)(struct _cef_request_t *) __attribute__((stdcall))
     * }
     */
    public static MemorySegment get_identifier(MemorySegment struct) {
        return struct.get(get_identifier$LAYOUT, get_identifier$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint64_t (*get_identifier)(struct _cef_request_t *) __attribute__((stdcall))
     * }
     */
    public static void get_identifier(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(get_identifier$LAYOUT, get_identifier$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

