// Generated by jextract

package com.tiji.silcef.natives;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct _cef_accelerated_paint_info_common_t {
 *     size_t size;
 *     uint64_t timestamp;
 *     cef_size_t coded_size;
 *     cef_rect_t visible_rect;
 *     cef_rect_t content_rect;
 *     cef_size_t source_size;
 *     cef_rect_t capture_update_rect;
 *     cef_rect_t region_capture_rect;
 *     uint64_t capture_counter;
 *     uint8_t has_capture_update_rect;
 *     uint8_t has_region_capture_rect;
 *     uint8_t has_source_size;
 *     uint8_t has_capture_counter;
 * }
 * }
 */
public class _cef_accelerated_paint_info_common_t {

    _cef_accelerated_paint_info_common_t() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        cef_master_h.C_LONG_LONG.withName("size"),
        cef_master_h.C_LONG_LONG.withName("timestamp"),
        _cef_size_t.layout().withName("coded_size"),
        _cef_rect_t.layout().withName("visible_rect"),
        _cef_rect_t.layout().withName("content_rect"),
        _cef_size_t.layout().withName("source_size"),
        _cef_rect_t.layout().withName("capture_update_rect"),
        _cef_rect_t.layout().withName("region_capture_rect"),
        cef_master_h.C_LONG_LONG.withName("capture_counter"),
        cef_master_h.C_CHAR.withName("has_capture_update_rect"),
        cef_master_h.C_CHAR.withName("has_region_capture_rect"),
        cef_master_h.C_CHAR.withName("has_source_size"),
        cef_master_h.C_CHAR.withName("has_capture_counter"),
        MemoryLayout.paddingLayout(4)
    ).withName("_cef_accelerated_paint_info_common_t");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final OfLong size$LAYOUT = (OfLong)$LAYOUT.select(groupElement("size"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * size_t size
     * }
     */
    public static final OfLong size$layout() {
        return size$LAYOUT;
    }

    private static final long size$OFFSET = $LAYOUT.byteOffset(groupElement("size"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * size_t size
     * }
     */
    public static final long size$offset() {
        return size$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * size_t size
     * }
     */
    public static long size(MemorySegment struct) {
        return struct.get(size$LAYOUT, size$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * size_t size
     * }
     */
    public static void size(MemorySegment struct, long fieldValue) {
        struct.set(size$LAYOUT, size$OFFSET, fieldValue);
    }

    private static final OfLong timestamp$LAYOUT = (OfLong)$LAYOUT.select(groupElement("timestamp"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint64_t timestamp
     * }
     */
    public static final OfLong timestamp$layout() {
        return timestamp$LAYOUT;
    }

    private static final long timestamp$OFFSET = $LAYOUT.byteOffset(groupElement("timestamp"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint64_t timestamp
     * }
     */
    public static final long timestamp$offset() {
        return timestamp$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint64_t timestamp
     * }
     */
    public static long timestamp(MemorySegment struct) {
        return struct.get(timestamp$LAYOUT, timestamp$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint64_t timestamp
     * }
     */
    public static void timestamp(MemorySegment struct, long fieldValue) {
        struct.set(timestamp$LAYOUT, timestamp$OFFSET, fieldValue);
    }

    private static final GroupLayout coded_size$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("coded_size"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * cef_size_t coded_size
     * }
     */
    public static final GroupLayout coded_size$layout() {
        return coded_size$LAYOUT;
    }

    private static final long coded_size$OFFSET = $LAYOUT.byteOffset(groupElement("coded_size"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * cef_size_t coded_size
     * }
     */
    public static final long coded_size$offset() {
        return coded_size$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * cef_size_t coded_size
     * }
     */
    public static MemorySegment coded_size(MemorySegment struct) {
        return struct.asSlice(coded_size$OFFSET, coded_size$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * cef_size_t coded_size
     * }
     */
    public static void coded_size(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, coded_size$OFFSET, coded_size$LAYOUT.byteSize());
    }

    private static final GroupLayout visible_rect$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("visible_rect"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * cef_rect_t visible_rect
     * }
     */
    public static final GroupLayout visible_rect$layout() {
        return visible_rect$LAYOUT;
    }

    private static final long visible_rect$OFFSET = $LAYOUT.byteOffset(groupElement("visible_rect"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * cef_rect_t visible_rect
     * }
     */
    public static final long visible_rect$offset() {
        return visible_rect$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * cef_rect_t visible_rect
     * }
     */
    public static MemorySegment visible_rect(MemorySegment struct) {
        return struct.asSlice(visible_rect$OFFSET, visible_rect$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * cef_rect_t visible_rect
     * }
     */
    public static void visible_rect(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, visible_rect$OFFSET, visible_rect$LAYOUT.byteSize());
    }

    private static final GroupLayout content_rect$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("content_rect"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * cef_rect_t content_rect
     * }
     */
    public static final GroupLayout content_rect$layout() {
        return content_rect$LAYOUT;
    }

    private static final long content_rect$OFFSET = $LAYOUT.byteOffset(groupElement("content_rect"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * cef_rect_t content_rect
     * }
     */
    public static final long content_rect$offset() {
        return content_rect$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * cef_rect_t content_rect
     * }
     */
    public static MemorySegment content_rect(MemorySegment struct) {
        return struct.asSlice(content_rect$OFFSET, content_rect$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * cef_rect_t content_rect
     * }
     */
    public static void content_rect(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, content_rect$OFFSET, content_rect$LAYOUT.byteSize());
    }

    private static final GroupLayout source_size$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("source_size"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * cef_size_t source_size
     * }
     */
    public static final GroupLayout source_size$layout() {
        return source_size$LAYOUT;
    }

    private static final long source_size$OFFSET = $LAYOUT.byteOffset(groupElement("source_size"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * cef_size_t source_size
     * }
     */
    public static final long source_size$offset() {
        return source_size$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * cef_size_t source_size
     * }
     */
    public static MemorySegment source_size(MemorySegment struct) {
        return struct.asSlice(source_size$OFFSET, source_size$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * cef_size_t source_size
     * }
     */
    public static void source_size(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, source_size$OFFSET, source_size$LAYOUT.byteSize());
    }

    private static final GroupLayout capture_update_rect$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("capture_update_rect"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * cef_rect_t capture_update_rect
     * }
     */
    public static final GroupLayout capture_update_rect$layout() {
        return capture_update_rect$LAYOUT;
    }

    private static final long capture_update_rect$OFFSET = $LAYOUT.byteOffset(groupElement("capture_update_rect"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * cef_rect_t capture_update_rect
     * }
     */
    public static final long capture_update_rect$offset() {
        return capture_update_rect$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * cef_rect_t capture_update_rect
     * }
     */
    public static MemorySegment capture_update_rect(MemorySegment struct) {
        return struct.asSlice(capture_update_rect$OFFSET, capture_update_rect$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * cef_rect_t capture_update_rect
     * }
     */
    public static void capture_update_rect(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, capture_update_rect$OFFSET, capture_update_rect$LAYOUT.byteSize());
    }

    private static final GroupLayout region_capture_rect$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("region_capture_rect"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * cef_rect_t region_capture_rect
     * }
     */
    public static final GroupLayout region_capture_rect$layout() {
        return region_capture_rect$LAYOUT;
    }

    private static final long region_capture_rect$OFFSET = $LAYOUT.byteOffset(groupElement("region_capture_rect"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * cef_rect_t region_capture_rect
     * }
     */
    public static final long region_capture_rect$offset() {
        return region_capture_rect$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * cef_rect_t region_capture_rect
     * }
     */
    public static MemorySegment region_capture_rect(MemorySegment struct) {
        return struct.asSlice(region_capture_rect$OFFSET, region_capture_rect$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * cef_rect_t region_capture_rect
     * }
     */
    public static void region_capture_rect(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, region_capture_rect$OFFSET, region_capture_rect$LAYOUT.byteSize());
    }

    private static final OfLong capture_counter$LAYOUT = (OfLong)$LAYOUT.select(groupElement("capture_counter"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint64_t capture_counter
     * }
     */
    public static final OfLong capture_counter$layout() {
        return capture_counter$LAYOUT;
    }

    private static final long capture_counter$OFFSET = $LAYOUT.byteOffset(groupElement("capture_counter"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint64_t capture_counter
     * }
     */
    public static final long capture_counter$offset() {
        return capture_counter$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint64_t capture_counter
     * }
     */
    public static long capture_counter(MemorySegment struct) {
        return struct.get(capture_counter$LAYOUT, capture_counter$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint64_t capture_counter
     * }
     */
    public static void capture_counter(MemorySegment struct, long fieldValue) {
        struct.set(capture_counter$LAYOUT, capture_counter$OFFSET, fieldValue);
    }

    private static final OfByte has_capture_update_rect$LAYOUT = (OfByte)$LAYOUT.select(groupElement("has_capture_update_rect"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint8_t has_capture_update_rect
     * }
     */
    public static final OfByte has_capture_update_rect$layout() {
        return has_capture_update_rect$LAYOUT;
    }

    private static final long has_capture_update_rect$OFFSET = $LAYOUT.byteOffset(groupElement("has_capture_update_rect"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint8_t has_capture_update_rect
     * }
     */
    public static final long has_capture_update_rect$offset() {
        return has_capture_update_rect$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint8_t has_capture_update_rect
     * }
     */
    public static byte has_capture_update_rect(MemorySegment struct) {
        return struct.get(has_capture_update_rect$LAYOUT, has_capture_update_rect$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint8_t has_capture_update_rect
     * }
     */
    public static void has_capture_update_rect(MemorySegment struct, byte fieldValue) {
        struct.set(has_capture_update_rect$LAYOUT, has_capture_update_rect$OFFSET, fieldValue);
    }

    private static final OfByte has_region_capture_rect$LAYOUT = (OfByte)$LAYOUT.select(groupElement("has_region_capture_rect"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint8_t has_region_capture_rect
     * }
     */
    public static final OfByte has_region_capture_rect$layout() {
        return has_region_capture_rect$LAYOUT;
    }

    private static final long has_region_capture_rect$OFFSET = $LAYOUT.byteOffset(groupElement("has_region_capture_rect"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint8_t has_region_capture_rect
     * }
     */
    public static final long has_region_capture_rect$offset() {
        return has_region_capture_rect$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint8_t has_region_capture_rect
     * }
     */
    public static byte has_region_capture_rect(MemorySegment struct) {
        return struct.get(has_region_capture_rect$LAYOUT, has_region_capture_rect$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint8_t has_region_capture_rect
     * }
     */
    public static void has_region_capture_rect(MemorySegment struct, byte fieldValue) {
        struct.set(has_region_capture_rect$LAYOUT, has_region_capture_rect$OFFSET, fieldValue);
    }

    private static final OfByte has_source_size$LAYOUT = (OfByte)$LAYOUT.select(groupElement("has_source_size"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint8_t has_source_size
     * }
     */
    public static final OfByte has_source_size$layout() {
        return has_source_size$LAYOUT;
    }

    private static final long has_source_size$OFFSET = $LAYOUT.byteOffset(groupElement("has_source_size"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint8_t has_source_size
     * }
     */
    public static final long has_source_size$offset() {
        return has_source_size$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint8_t has_source_size
     * }
     */
    public static byte has_source_size(MemorySegment struct) {
        return struct.get(has_source_size$LAYOUT, has_source_size$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint8_t has_source_size
     * }
     */
    public static void has_source_size(MemorySegment struct, byte fieldValue) {
        struct.set(has_source_size$LAYOUT, has_source_size$OFFSET, fieldValue);
    }

    private static final OfByte has_capture_counter$LAYOUT = (OfByte)$LAYOUT.select(groupElement("has_capture_counter"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint8_t has_capture_counter
     * }
     */
    public static final OfByte has_capture_counter$layout() {
        return has_capture_counter$LAYOUT;
    }

    private static final long has_capture_counter$OFFSET = $LAYOUT.byteOffset(groupElement("has_capture_counter"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint8_t has_capture_counter
     * }
     */
    public static final long has_capture_counter$offset() {
        return has_capture_counter$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint8_t has_capture_counter
     * }
     */
    public static byte has_capture_counter(MemorySegment struct) {
        return struct.get(has_capture_counter$LAYOUT, has_capture_counter$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint8_t has_capture_counter
     * }
     */
    public static void has_capture_counter(MemorySegment struct, byte fieldValue) {
        struct.set(has_capture_counter$LAYOUT, has_capture_counter$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

