// Generated by jextract

package com.tiji.silcef.natives;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct _cef_display_handler_t {
 *     cef_base_ref_counted_t base;
 *     void (*on_address_change)(struct _cef_display_handler_t *, struct _cef_browser_t *, struct _cef_frame_t *, const cef_string_t *) __attribute__((stdcall));
 *     void (*on_title_change)(struct _cef_display_handler_t *, struct _cef_browser_t *, const cef_string_t *) __attribute__((stdcall));
 *     void (*on_favicon_urlchange)(struct _cef_display_handler_t *, struct _cef_browser_t *, cef_string_list_t) __attribute__((stdcall));
 *     void (*on_fullscreen_mode_change)(struct _cef_display_handler_t *, struct _cef_browser_t *, int) __attribute__((stdcall));
 *     int (*on_tooltip)(struct _cef_display_handler_t *, struct _cef_browser_t *, cef_string_t *) __attribute__((stdcall));
 *     void (*on_status_message)(struct _cef_display_handler_t *, struct _cef_browser_t *, const cef_string_t *) __attribute__((stdcall));
 *     int (*on_console_message)(struct _cef_display_handler_t *, struct _cef_browser_t *, cef_log_severity_t, const cef_string_t *, const cef_string_t *, int) __attribute__((stdcall));
 *     int (*on_auto_resize)(struct _cef_display_handler_t *, struct _cef_browser_t *, const cef_size_t *) __attribute__((stdcall));
 *     void (*on_loading_progress_change)(struct _cef_display_handler_t *, struct _cef_browser_t *, double) __attribute__((stdcall));
 *     int (*on_cursor_change)(struct _cef_display_handler_t *, struct _cef_browser_t *, cef_cursor_handle_t, cef_cursor_type_t, const cef_cursor_info_t *) __attribute__((stdcall));
 *     void (*on_media_access_change)(struct _cef_display_handler_t *, struct _cef_browser_t *, int, int) __attribute__((stdcall));
 *     int (*on_contents_bounds_change)(struct _cef_display_handler_t *, struct _cef_browser_t *, const cef_rect_t *) __attribute__((stdcall));
 *     int (*get_root_window_screen_rect)(struct _cef_display_handler_t *, struct _cef_browser_t *, cef_rect_t *) __attribute__((stdcall));
 * }
 * }
 */
public class _cef_display_handler_t {

    _cef_display_handler_t() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        _cef_base_ref_counted_t.layout().withName("base"),
        cef_master_h.C_POINTER.withName("on_address_change"),
        cef_master_h.C_POINTER.withName("on_title_change"),
        cef_master_h.C_POINTER.withName("on_favicon_urlchange"),
        cef_master_h.C_POINTER.withName("on_fullscreen_mode_change"),
        cef_master_h.C_POINTER.withName("on_tooltip"),
        cef_master_h.C_POINTER.withName("on_status_message"),
        cef_master_h.C_POINTER.withName("on_console_message"),
        cef_master_h.C_POINTER.withName("on_auto_resize"),
        cef_master_h.C_POINTER.withName("on_loading_progress_change"),
        cef_master_h.C_POINTER.withName("on_cursor_change"),
        cef_master_h.C_POINTER.withName("on_media_access_change"),
        cef_master_h.C_POINTER.withName("on_contents_bounds_change"),
        cef_master_h.C_POINTER.withName("get_root_window_screen_rect")
    ).withName("_cef_display_handler_t");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final GroupLayout base$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("base"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * cef_base_ref_counted_t base
     * }
     */
    public static final GroupLayout base$layout() {
        return base$LAYOUT;
    }

    private static final long base$OFFSET = $LAYOUT.byteOffset(groupElement("base"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * cef_base_ref_counted_t base
     * }
     */
    public static final long base$offset() {
        return base$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * cef_base_ref_counted_t base
     * }
     */
    public static MemorySegment base(MemorySegment struct) {
        return struct.asSlice(base$OFFSET, base$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * cef_base_ref_counted_t base
     * }
     */
    public static void base(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, base$OFFSET, base$LAYOUT.byteSize());
    }

    /**
     * {@snippet lang=c :
     * void (*on_address_change)(struct _cef_display_handler_t *, struct _cef_browser_t *, struct _cef_frame_t *, const cef_string_t *) __attribute__((stdcall))
     * }
     */
    public final static class on_address_change {

        private on_address_change() {
            // Should not be called directly
        }

        /**
         * The function pointer signature, expressed as a functional interface
         */
        public interface Function {
            void apply(MemorySegment _x0, MemorySegment _x1, MemorySegment _x2, MemorySegment _x3);
        }

        private static final FunctionDescriptor $DESC = FunctionDescriptor.ofVoid(
            cef_master_h.C_POINTER,
            cef_master_h.C_POINTER,
            cef_master_h.C_POINTER,
            cef_master_h.C_POINTER
        );

        /**
         * The descriptor of this function pointer
         */
        public static FunctionDescriptor descriptor() {
            return $DESC;
        }

        private static final MethodHandle UP$MH = cef_master_h.upcallHandle(on_address_change.Function.class, "apply", $DESC);

        /**
         * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
         * The lifetime of the returned segment is managed by {@code arena}
         */
        public static MemorySegment allocate(on_address_change.Function fi, Arena arena) {
            return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
        }

        private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

        /**
         * Invoke the upcall stub {@code funcPtr}, with given parameters
         */
        public static void invoke(MemorySegment funcPtr, MemorySegment _x0, MemorySegment _x1, MemorySegment _x2, MemorySegment _x3) {
            try {
                 DOWN$MH.invokeExact(funcPtr, _x0, _x1, _x2, _x3);
            } catch (Error | RuntimeException ex) {
                throw ex;
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        }
    }

    private static final AddressLayout on_address_change$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("on_address_change"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * void (*on_address_change)(struct _cef_display_handler_t *, struct _cef_browser_t *, struct _cef_frame_t *, const cef_string_t *) __attribute__((stdcall))
     * }
     */
    public static final AddressLayout on_address_change$layout() {
        return on_address_change$LAYOUT;
    }

    private static final long on_address_change$OFFSET = $LAYOUT.byteOffset(groupElement("on_address_change"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * void (*on_address_change)(struct _cef_display_handler_t *, struct _cef_browser_t *, struct _cef_frame_t *, const cef_string_t *) __attribute__((stdcall))
     * }
     */
    public static final long on_address_change$offset() {
        return on_address_change$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * void (*on_address_change)(struct _cef_display_handler_t *, struct _cef_browser_t *, struct _cef_frame_t *, const cef_string_t *) __attribute__((stdcall))
     * }
     */
    public static MemorySegment on_address_change(MemorySegment struct) {
        return struct.get(on_address_change$LAYOUT, on_address_change$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * void (*on_address_change)(struct _cef_display_handler_t *, struct _cef_browser_t *, struct _cef_frame_t *, const cef_string_t *) __attribute__((stdcall))
     * }
     */
    public static void on_address_change(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(on_address_change$LAYOUT, on_address_change$OFFSET, fieldValue);
    }

    /**
     * {@snippet lang=c :
     * void (*on_title_change)(struct _cef_display_handler_t *, struct _cef_browser_t *, const cef_string_t *) __attribute__((stdcall))
     * }
     */
    public final static class on_title_change {

        private on_title_change() {
            // Should not be called directly
        }

        /**
         * The function pointer signature, expressed as a functional interface
         */
        public interface Function {
            void apply(MemorySegment _x0, MemorySegment _x1, MemorySegment _x2);
        }

        private static final FunctionDescriptor $DESC = FunctionDescriptor.ofVoid(
            cef_master_h.C_POINTER,
            cef_master_h.C_POINTER,
            cef_master_h.C_POINTER
        );

        /**
         * The descriptor of this function pointer
         */
        public static FunctionDescriptor descriptor() {
            return $DESC;
        }

        private static final MethodHandle UP$MH = cef_master_h.upcallHandle(on_title_change.Function.class, "apply", $DESC);

        /**
         * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
         * The lifetime of the returned segment is managed by {@code arena}
         */
        public static MemorySegment allocate(on_title_change.Function fi, Arena arena) {
            return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
        }

        private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

        /**
         * Invoke the upcall stub {@code funcPtr}, with given parameters
         */
        public static void invoke(MemorySegment funcPtr, MemorySegment _x0, MemorySegment _x1, MemorySegment _x2) {
            try {
                 DOWN$MH.invokeExact(funcPtr, _x0, _x1, _x2);
            } catch (Error | RuntimeException ex) {
                throw ex;
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        }
    }

    private static final AddressLayout on_title_change$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("on_title_change"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * void (*on_title_change)(struct _cef_display_handler_t *, struct _cef_browser_t *, const cef_string_t *) __attribute__((stdcall))
     * }
     */
    public static final AddressLayout on_title_change$layout() {
        return on_title_change$LAYOUT;
    }

    private static final long on_title_change$OFFSET = $LAYOUT.byteOffset(groupElement("on_title_change"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * void (*on_title_change)(struct _cef_display_handler_t *, struct _cef_browser_t *, const cef_string_t *) __attribute__((stdcall))
     * }
     */
    public static final long on_title_change$offset() {
        return on_title_change$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * void (*on_title_change)(struct _cef_display_handler_t *, struct _cef_browser_t *, const cef_string_t *) __attribute__((stdcall))
     * }
     */
    public static MemorySegment on_title_change(MemorySegment struct) {
        return struct.get(on_title_change$LAYOUT, on_title_change$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * void (*on_title_change)(struct _cef_display_handler_t *, struct _cef_browser_t *, const cef_string_t *) __attribute__((stdcall))
     * }
     */
    public static void on_title_change(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(on_title_change$LAYOUT, on_title_change$OFFSET, fieldValue);
    }

    /**
     * {@snippet lang=c :
     * void (*on_favicon_urlchange)(struct _cef_display_handler_t *, struct _cef_browser_t *, cef_string_list_t) __attribute__((stdcall))
     * }
     */
    public final static class on_favicon_urlchange {

        private on_favicon_urlchange() {
            // Should not be called directly
        }

        /**
         * The function pointer signature, expressed as a functional interface
         */
        public interface Function {
            void apply(MemorySegment _x0, MemorySegment _x1, MemorySegment _x2);
        }

        private static final FunctionDescriptor $DESC = FunctionDescriptor.ofVoid(
            cef_master_h.C_POINTER,
            cef_master_h.C_POINTER,
            cef_master_h.C_POINTER
        );

        /**
         * The descriptor of this function pointer
         */
        public static FunctionDescriptor descriptor() {
            return $DESC;
        }

        private static final MethodHandle UP$MH = cef_master_h.upcallHandle(on_favicon_urlchange.Function.class, "apply", $DESC);

        /**
         * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
         * The lifetime of the returned segment is managed by {@code arena}
         */
        public static MemorySegment allocate(on_favicon_urlchange.Function fi, Arena arena) {
            return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
        }

        private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

        /**
         * Invoke the upcall stub {@code funcPtr}, with given parameters
         */
        public static void invoke(MemorySegment funcPtr, MemorySegment _x0, MemorySegment _x1, MemorySegment _x2) {
            try {
                 DOWN$MH.invokeExact(funcPtr, _x0, _x1, _x2);
            } catch (Error | RuntimeException ex) {
                throw ex;
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        }
    }

    private static final AddressLayout on_favicon_urlchange$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("on_favicon_urlchange"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * void (*on_favicon_urlchange)(struct _cef_display_handler_t *, struct _cef_browser_t *, cef_string_list_t) __attribute__((stdcall))
     * }
     */
    public static final AddressLayout on_favicon_urlchange$layout() {
        return on_favicon_urlchange$LAYOUT;
    }

    private static final long on_favicon_urlchange$OFFSET = $LAYOUT.byteOffset(groupElement("on_favicon_urlchange"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * void (*on_favicon_urlchange)(struct _cef_display_handler_t *, struct _cef_browser_t *, cef_string_list_t) __attribute__((stdcall))
     * }
     */
    public static final long on_favicon_urlchange$offset() {
        return on_favicon_urlchange$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * void (*on_favicon_urlchange)(struct _cef_display_handler_t *, struct _cef_browser_t *, cef_string_list_t) __attribute__((stdcall))
     * }
     */
    public static MemorySegment on_favicon_urlchange(MemorySegment struct) {
        return struct.get(on_favicon_urlchange$LAYOUT, on_favicon_urlchange$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * void (*on_favicon_urlchange)(struct _cef_display_handler_t *, struct _cef_browser_t *, cef_string_list_t) __attribute__((stdcall))
     * }
     */
    public static void on_favicon_urlchange(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(on_favicon_urlchange$LAYOUT, on_favicon_urlchange$OFFSET, fieldValue);
    }

    /**
     * {@snippet lang=c :
     * void (*on_fullscreen_mode_change)(struct _cef_display_handler_t *, struct _cef_browser_t *, int) __attribute__((stdcall))
     * }
     */
    public final static class on_fullscreen_mode_change {

        private on_fullscreen_mode_change() {
            // Should not be called directly
        }

        /**
         * The function pointer signature, expressed as a functional interface
         */
        public interface Function {
            void apply(MemorySegment _x0, MemorySegment _x1, int _x2);
        }

        private static final FunctionDescriptor $DESC = FunctionDescriptor.ofVoid(
            cef_master_h.C_POINTER,
            cef_master_h.C_POINTER,
            cef_master_h.C_INT
        );

        /**
         * The descriptor of this function pointer
         */
        public static FunctionDescriptor descriptor() {
            return $DESC;
        }

        private static final MethodHandle UP$MH = cef_master_h.upcallHandle(on_fullscreen_mode_change.Function.class, "apply", $DESC);

        /**
         * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
         * The lifetime of the returned segment is managed by {@code arena}
         */
        public static MemorySegment allocate(on_fullscreen_mode_change.Function fi, Arena arena) {
            return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
        }

        private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

        /**
         * Invoke the upcall stub {@code funcPtr}, with given parameters
         */
        public static void invoke(MemorySegment funcPtr, MemorySegment _x0, MemorySegment _x1, int _x2) {
            try {
                 DOWN$MH.invokeExact(funcPtr, _x0, _x1, _x2);
            } catch (Error | RuntimeException ex) {
                throw ex;
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        }
    }

    private static final AddressLayout on_fullscreen_mode_change$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("on_fullscreen_mode_change"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * void (*on_fullscreen_mode_change)(struct _cef_display_handler_t *, struct _cef_browser_t *, int) __attribute__((stdcall))
     * }
     */
    public static final AddressLayout on_fullscreen_mode_change$layout() {
        return on_fullscreen_mode_change$LAYOUT;
    }

    private static final long on_fullscreen_mode_change$OFFSET = $LAYOUT.byteOffset(groupElement("on_fullscreen_mode_change"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * void (*on_fullscreen_mode_change)(struct _cef_display_handler_t *, struct _cef_browser_t *, int) __attribute__((stdcall))
     * }
     */
    public static final long on_fullscreen_mode_change$offset() {
        return on_fullscreen_mode_change$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * void (*on_fullscreen_mode_change)(struct _cef_display_handler_t *, struct _cef_browser_t *, int) __attribute__((stdcall))
     * }
     */
    public static MemorySegment on_fullscreen_mode_change(MemorySegment struct) {
        return struct.get(on_fullscreen_mode_change$LAYOUT, on_fullscreen_mode_change$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * void (*on_fullscreen_mode_change)(struct _cef_display_handler_t *, struct _cef_browser_t *, int) __attribute__((stdcall))
     * }
     */
    public static void on_fullscreen_mode_change(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(on_fullscreen_mode_change$LAYOUT, on_fullscreen_mode_change$OFFSET, fieldValue);
    }

    /**
     * {@snippet lang=c :
     * int (*on_tooltip)(struct _cef_display_handler_t *, struct _cef_browser_t *, cef_string_t *) __attribute__((stdcall))
     * }
     */
    public final static class on_tooltip {

        private on_tooltip() {
            // Should not be called directly
        }

        /**
         * The function pointer signature, expressed as a functional interface
         */
        public interface Function {
            int apply(MemorySegment _x0, MemorySegment _x1, MemorySegment _x2);
        }

        private static final FunctionDescriptor $DESC = FunctionDescriptor.of(
            cef_master_h.C_INT,
            cef_master_h.C_POINTER,
            cef_master_h.C_POINTER,
            cef_master_h.C_POINTER
        );

        /**
         * The descriptor of this function pointer
         */
        public static FunctionDescriptor descriptor() {
            return $DESC;
        }

        private static final MethodHandle UP$MH = cef_master_h.upcallHandle(on_tooltip.Function.class, "apply", $DESC);

        /**
         * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
         * The lifetime of the returned segment is managed by {@code arena}
         */
        public static MemorySegment allocate(on_tooltip.Function fi, Arena arena) {
            return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
        }

        private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

        /**
         * Invoke the upcall stub {@code funcPtr}, with given parameters
         */
        public static int invoke(MemorySegment funcPtr, MemorySegment _x0, MemorySegment _x1, MemorySegment _x2) {
            try {
                return (int) DOWN$MH.invokeExact(funcPtr, _x0, _x1, _x2);
            } catch (Error | RuntimeException ex) {
                throw ex;
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        }
    }

    private static final AddressLayout on_tooltip$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("on_tooltip"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int (*on_tooltip)(struct _cef_display_handler_t *, struct _cef_browser_t *, cef_string_t *) __attribute__((stdcall))
     * }
     */
    public static final AddressLayout on_tooltip$layout() {
        return on_tooltip$LAYOUT;
    }

    private static final long on_tooltip$OFFSET = $LAYOUT.byteOffset(groupElement("on_tooltip"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int (*on_tooltip)(struct _cef_display_handler_t *, struct _cef_browser_t *, cef_string_t *) __attribute__((stdcall))
     * }
     */
    public static final long on_tooltip$offset() {
        return on_tooltip$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int (*on_tooltip)(struct _cef_display_handler_t *, struct _cef_browser_t *, cef_string_t *) __attribute__((stdcall))
     * }
     */
    public static MemorySegment on_tooltip(MemorySegment struct) {
        return struct.get(on_tooltip$LAYOUT, on_tooltip$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int (*on_tooltip)(struct _cef_display_handler_t *, struct _cef_browser_t *, cef_string_t *) __attribute__((stdcall))
     * }
     */
    public static void on_tooltip(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(on_tooltip$LAYOUT, on_tooltip$OFFSET, fieldValue);
    }

    /**
     * {@snippet lang=c :
     * void (*on_status_message)(struct _cef_display_handler_t *, struct _cef_browser_t *, const cef_string_t *) __attribute__((stdcall))
     * }
     */
    public final static class on_status_message {

        private on_status_message() {
            // Should not be called directly
        }

        /**
         * The function pointer signature, expressed as a functional interface
         */
        public interface Function {
            void apply(MemorySegment _x0, MemorySegment _x1, MemorySegment _x2);
        }

        private static final FunctionDescriptor $DESC = FunctionDescriptor.ofVoid(
            cef_master_h.C_POINTER,
            cef_master_h.C_POINTER,
            cef_master_h.C_POINTER
        );

        /**
         * The descriptor of this function pointer
         */
        public static FunctionDescriptor descriptor() {
            return $DESC;
        }

        private static final MethodHandle UP$MH = cef_master_h.upcallHandle(on_status_message.Function.class, "apply", $DESC);

        /**
         * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
         * The lifetime of the returned segment is managed by {@code arena}
         */
        public static MemorySegment allocate(on_status_message.Function fi, Arena arena) {
            return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
        }

        private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

        /**
         * Invoke the upcall stub {@code funcPtr}, with given parameters
         */
        public static void invoke(MemorySegment funcPtr, MemorySegment _x0, MemorySegment _x1, MemorySegment _x2) {
            try {
                 DOWN$MH.invokeExact(funcPtr, _x0, _x1, _x2);
            } catch (Error | RuntimeException ex) {
                throw ex;
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        }
    }

    private static final AddressLayout on_status_message$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("on_status_message"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * void (*on_status_message)(struct _cef_display_handler_t *, struct _cef_browser_t *, const cef_string_t *) __attribute__((stdcall))
     * }
     */
    public static final AddressLayout on_status_message$layout() {
        return on_status_message$LAYOUT;
    }

    private static final long on_status_message$OFFSET = $LAYOUT.byteOffset(groupElement("on_status_message"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * void (*on_status_message)(struct _cef_display_handler_t *, struct _cef_browser_t *, const cef_string_t *) __attribute__((stdcall))
     * }
     */
    public static final long on_status_message$offset() {
        return on_status_message$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * void (*on_status_message)(struct _cef_display_handler_t *, struct _cef_browser_t *, const cef_string_t *) __attribute__((stdcall))
     * }
     */
    public static MemorySegment on_status_message(MemorySegment struct) {
        return struct.get(on_status_message$LAYOUT, on_status_message$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * void (*on_status_message)(struct _cef_display_handler_t *, struct _cef_browser_t *, const cef_string_t *) __attribute__((stdcall))
     * }
     */
    public static void on_status_message(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(on_status_message$LAYOUT, on_status_message$OFFSET, fieldValue);
    }

    /**
     * {@snippet lang=c :
     * int (*on_console_message)(struct _cef_display_handler_t *, struct _cef_browser_t *, cef_log_severity_t, const cef_string_t *, const cef_string_t *, int) __attribute__((stdcall))
     * }
     */
    public final static class on_console_message {

        private on_console_message() {
            // Should not be called directly
        }

        /**
         * The function pointer signature, expressed as a functional interface
         */
        public interface Function {
            int apply(MemorySegment _x0, MemorySegment _x1, int _x2, MemorySegment _x3, MemorySegment _x4, int _x5);
        }

        private static final FunctionDescriptor $DESC = FunctionDescriptor.of(
            cef_master_h.C_INT,
            cef_master_h.C_POINTER,
            cef_master_h.C_POINTER,
            cef_master_h.C_INT,
            cef_master_h.C_POINTER,
            cef_master_h.C_POINTER,
            cef_master_h.C_INT
        );

        /**
         * The descriptor of this function pointer
         */
        public static FunctionDescriptor descriptor() {
            return $DESC;
        }

        private static final MethodHandle UP$MH = cef_master_h.upcallHandle(on_console_message.Function.class, "apply", $DESC);

        /**
         * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
         * The lifetime of the returned segment is managed by {@code arena}
         */
        public static MemorySegment allocate(on_console_message.Function fi, Arena arena) {
            return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
        }

        private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

        /**
         * Invoke the upcall stub {@code funcPtr}, with given parameters
         */
        public static int invoke(MemorySegment funcPtr, MemorySegment _x0, MemorySegment _x1, int _x2, MemorySegment _x3, MemorySegment _x4, int _x5) {
            try {
                return (int) DOWN$MH.invokeExact(funcPtr, _x0, _x1, _x2, _x3, _x4, _x5);
            } catch (Error | RuntimeException ex) {
                throw ex;
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        }
    }

    private static final AddressLayout on_console_message$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("on_console_message"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int (*on_console_message)(struct _cef_display_handler_t *, struct _cef_browser_t *, cef_log_severity_t, const cef_string_t *, const cef_string_t *, int) __attribute__((stdcall))
     * }
     */
    public static final AddressLayout on_console_message$layout() {
        return on_console_message$LAYOUT;
    }

    private static final long on_console_message$OFFSET = $LAYOUT.byteOffset(groupElement("on_console_message"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int (*on_console_message)(struct _cef_display_handler_t *, struct _cef_browser_t *, cef_log_severity_t, const cef_string_t *, const cef_string_t *, int) __attribute__((stdcall))
     * }
     */
    public static final long on_console_message$offset() {
        return on_console_message$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int (*on_console_message)(struct _cef_display_handler_t *, struct _cef_browser_t *, cef_log_severity_t, const cef_string_t *, const cef_string_t *, int) __attribute__((stdcall))
     * }
     */
    public static MemorySegment on_console_message(MemorySegment struct) {
        return struct.get(on_console_message$LAYOUT, on_console_message$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int (*on_console_message)(struct _cef_display_handler_t *, struct _cef_browser_t *, cef_log_severity_t, const cef_string_t *, const cef_string_t *, int) __attribute__((stdcall))
     * }
     */
    public static void on_console_message(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(on_console_message$LAYOUT, on_console_message$OFFSET, fieldValue);
    }

    /**
     * {@snippet lang=c :
     * int (*on_auto_resize)(struct _cef_display_handler_t *, struct _cef_browser_t *, const cef_size_t *) __attribute__((stdcall))
     * }
     */
    public final static class on_auto_resize {

        private on_auto_resize() {
            // Should not be called directly
        }

        /**
         * The function pointer signature, expressed as a functional interface
         */
        public interface Function {
            int apply(MemorySegment _x0, MemorySegment _x1, MemorySegment _x2);
        }

        private static final FunctionDescriptor $DESC = FunctionDescriptor.of(
            cef_master_h.C_INT,
            cef_master_h.C_POINTER,
            cef_master_h.C_POINTER,
            cef_master_h.C_POINTER
        );

        /**
         * The descriptor of this function pointer
         */
        public static FunctionDescriptor descriptor() {
            return $DESC;
        }

        private static final MethodHandle UP$MH = cef_master_h.upcallHandle(on_auto_resize.Function.class, "apply", $DESC);

        /**
         * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
         * The lifetime of the returned segment is managed by {@code arena}
         */
        public static MemorySegment allocate(on_auto_resize.Function fi, Arena arena) {
            return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
        }

        private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

        /**
         * Invoke the upcall stub {@code funcPtr}, with given parameters
         */
        public static int invoke(MemorySegment funcPtr, MemorySegment _x0, MemorySegment _x1, MemorySegment _x2) {
            try {
                return (int) DOWN$MH.invokeExact(funcPtr, _x0, _x1, _x2);
            } catch (Error | RuntimeException ex) {
                throw ex;
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        }
    }

    private static final AddressLayout on_auto_resize$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("on_auto_resize"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int (*on_auto_resize)(struct _cef_display_handler_t *, struct _cef_browser_t *, const cef_size_t *) __attribute__((stdcall))
     * }
     */
    public static final AddressLayout on_auto_resize$layout() {
        return on_auto_resize$LAYOUT;
    }

    private static final long on_auto_resize$OFFSET = $LAYOUT.byteOffset(groupElement("on_auto_resize"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int (*on_auto_resize)(struct _cef_display_handler_t *, struct _cef_browser_t *, const cef_size_t *) __attribute__((stdcall))
     * }
     */
    public static final long on_auto_resize$offset() {
        return on_auto_resize$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int (*on_auto_resize)(struct _cef_display_handler_t *, struct _cef_browser_t *, const cef_size_t *) __attribute__((stdcall))
     * }
     */
    public static MemorySegment on_auto_resize(MemorySegment struct) {
        return struct.get(on_auto_resize$LAYOUT, on_auto_resize$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int (*on_auto_resize)(struct _cef_display_handler_t *, struct _cef_browser_t *, const cef_size_t *) __attribute__((stdcall))
     * }
     */
    public static void on_auto_resize(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(on_auto_resize$LAYOUT, on_auto_resize$OFFSET, fieldValue);
    }

    /**
     * {@snippet lang=c :
     * void (*on_loading_progress_change)(struct _cef_display_handler_t *, struct _cef_browser_t *, double) __attribute__((stdcall))
     * }
     */
    public final static class on_loading_progress_change {

        private on_loading_progress_change() {
            // Should not be called directly
        }

        /**
         * The function pointer signature, expressed as a functional interface
         */
        public interface Function {
            void apply(MemorySegment _x0, MemorySegment _x1, double _x2);
        }

        private static final FunctionDescriptor $DESC = FunctionDescriptor.ofVoid(
            cef_master_h.C_POINTER,
            cef_master_h.C_POINTER,
            cef_master_h.C_DOUBLE
        );

        /**
         * The descriptor of this function pointer
         */
        public static FunctionDescriptor descriptor() {
            return $DESC;
        }

        private static final MethodHandle UP$MH = cef_master_h.upcallHandle(on_loading_progress_change.Function.class, "apply", $DESC);

        /**
         * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
         * The lifetime of the returned segment is managed by {@code arena}
         */
        public static MemorySegment allocate(on_loading_progress_change.Function fi, Arena arena) {
            return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
        }

        private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

        /**
         * Invoke the upcall stub {@code funcPtr}, with given parameters
         */
        public static void invoke(MemorySegment funcPtr, MemorySegment _x0, MemorySegment _x1, double _x2) {
            try {
                 DOWN$MH.invokeExact(funcPtr, _x0, _x1, _x2);
            } catch (Error | RuntimeException ex) {
                throw ex;
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        }
    }

    private static final AddressLayout on_loading_progress_change$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("on_loading_progress_change"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * void (*on_loading_progress_change)(struct _cef_display_handler_t *, struct _cef_browser_t *, double) __attribute__((stdcall))
     * }
     */
    public static final AddressLayout on_loading_progress_change$layout() {
        return on_loading_progress_change$LAYOUT;
    }

    private static final long on_loading_progress_change$OFFSET = $LAYOUT.byteOffset(groupElement("on_loading_progress_change"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * void (*on_loading_progress_change)(struct _cef_display_handler_t *, struct _cef_browser_t *, double) __attribute__((stdcall))
     * }
     */
    public static final long on_loading_progress_change$offset() {
        return on_loading_progress_change$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * void (*on_loading_progress_change)(struct _cef_display_handler_t *, struct _cef_browser_t *, double) __attribute__((stdcall))
     * }
     */
    public static MemorySegment on_loading_progress_change(MemorySegment struct) {
        return struct.get(on_loading_progress_change$LAYOUT, on_loading_progress_change$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * void (*on_loading_progress_change)(struct _cef_display_handler_t *, struct _cef_browser_t *, double) __attribute__((stdcall))
     * }
     */
    public static void on_loading_progress_change(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(on_loading_progress_change$LAYOUT, on_loading_progress_change$OFFSET, fieldValue);
    }

    /**
     * {@snippet lang=c :
     * int (*on_cursor_change)(struct _cef_display_handler_t *, struct _cef_browser_t *, cef_cursor_handle_t, cef_cursor_type_t, const cef_cursor_info_t *) __attribute__((stdcall))
     * }
     */
    public final static class on_cursor_change {

        private on_cursor_change() {
            // Should not be called directly
        }

        /**
         * The function pointer signature, expressed as a functional interface
         */
        public interface Function {
            int apply(MemorySegment _x0, MemorySegment _x1, MemorySegment _x2, int _x3, MemorySegment _x4);
        }

        private static final FunctionDescriptor $DESC = FunctionDescriptor.of(
            cef_master_h.C_INT,
            cef_master_h.C_POINTER,
            cef_master_h.C_POINTER,
            cef_master_h.C_POINTER,
            cef_master_h.C_INT,
            cef_master_h.C_POINTER
        );

        /**
         * The descriptor of this function pointer
         */
        public static FunctionDescriptor descriptor() {
            return $DESC;
        }

        private static final MethodHandle UP$MH = cef_master_h.upcallHandle(on_cursor_change.Function.class, "apply", $DESC);

        /**
         * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
         * The lifetime of the returned segment is managed by {@code arena}
         */
        public static MemorySegment allocate(on_cursor_change.Function fi, Arena arena) {
            return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
        }

        private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

        /**
         * Invoke the upcall stub {@code funcPtr}, with given parameters
         */
        public static int invoke(MemorySegment funcPtr, MemorySegment _x0, MemorySegment _x1, MemorySegment _x2, int _x3, MemorySegment _x4) {
            try {
                return (int) DOWN$MH.invokeExact(funcPtr, _x0, _x1, _x2, _x3, _x4);
            } catch (Error | RuntimeException ex) {
                throw ex;
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        }
    }

    private static final AddressLayout on_cursor_change$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("on_cursor_change"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int (*on_cursor_change)(struct _cef_display_handler_t *, struct _cef_browser_t *, cef_cursor_handle_t, cef_cursor_type_t, const cef_cursor_info_t *) __attribute__((stdcall))
     * }
     */
    public static final AddressLayout on_cursor_change$layout() {
        return on_cursor_change$LAYOUT;
    }

    private static final long on_cursor_change$OFFSET = $LAYOUT.byteOffset(groupElement("on_cursor_change"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int (*on_cursor_change)(struct _cef_display_handler_t *, struct _cef_browser_t *, cef_cursor_handle_t, cef_cursor_type_t, const cef_cursor_info_t *) __attribute__((stdcall))
     * }
     */
    public static final long on_cursor_change$offset() {
        return on_cursor_change$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int (*on_cursor_change)(struct _cef_display_handler_t *, struct _cef_browser_t *, cef_cursor_handle_t, cef_cursor_type_t, const cef_cursor_info_t *) __attribute__((stdcall))
     * }
     */
    public static MemorySegment on_cursor_change(MemorySegment struct) {
        return struct.get(on_cursor_change$LAYOUT, on_cursor_change$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int (*on_cursor_change)(struct _cef_display_handler_t *, struct _cef_browser_t *, cef_cursor_handle_t, cef_cursor_type_t, const cef_cursor_info_t *) __attribute__((stdcall))
     * }
     */
    public static void on_cursor_change(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(on_cursor_change$LAYOUT, on_cursor_change$OFFSET, fieldValue);
    }

    /**
     * {@snippet lang=c :
     * void (*on_media_access_change)(struct _cef_display_handler_t *, struct _cef_browser_t *, int, int) __attribute__((stdcall))
     * }
     */
    public final static class on_media_access_change {

        private on_media_access_change() {
            // Should not be called directly
        }

        /**
         * The function pointer signature, expressed as a functional interface
         */
        public interface Function {
            void apply(MemorySegment _x0, MemorySegment _x1, int _x2, int _x3);
        }

        private static final FunctionDescriptor $DESC = FunctionDescriptor.ofVoid(
            cef_master_h.C_POINTER,
            cef_master_h.C_POINTER,
            cef_master_h.C_INT,
            cef_master_h.C_INT
        );

        /**
         * The descriptor of this function pointer
         */
        public static FunctionDescriptor descriptor() {
            return $DESC;
        }

        private static final MethodHandle UP$MH = cef_master_h.upcallHandle(on_media_access_change.Function.class, "apply", $DESC);

        /**
         * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
         * The lifetime of the returned segment is managed by {@code arena}
         */
        public static MemorySegment allocate(on_media_access_change.Function fi, Arena arena) {
            return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
        }

        private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

        /**
         * Invoke the upcall stub {@code funcPtr}, with given parameters
         */
        public static void invoke(MemorySegment funcPtr, MemorySegment _x0, MemorySegment _x1, int _x2, int _x3) {
            try {
                 DOWN$MH.invokeExact(funcPtr, _x0, _x1, _x2, _x3);
            } catch (Error | RuntimeException ex) {
                throw ex;
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        }
    }

    private static final AddressLayout on_media_access_change$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("on_media_access_change"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * void (*on_media_access_change)(struct _cef_display_handler_t *, struct _cef_browser_t *, int, int) __attribute__((stdcall))
     * }
     */
    public static final AddressLayout on_media_access_change$layout() {
        return on_media_access_change$LAYOUT;
    }

    private static final long on_media_access_change$OFFSET = $LAYOUT.byteOffset(groupElement("on_media_access_change"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * void (*on_media_access_change)(struct _cef_display_handler_t *, struct _cef_browser_t *, int, int) __attribute__((stdcall))
     * }
     */
    public static final long on_media_access_change$offset() {
        return on_media_access_change$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * void (*on_media_access_change)(struct _cef_display_handler_t *, struct _cef_browser_t *, int, int) __attribute__((stdcall))
     * }
     */
    public static MemorySegment on_media_access_change(MemorySegment struct) {
        return struct.get(on_media_access_change$LAYOUT, on_media_access_change$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * void (*on_media_access_change)(struct _cef_display_handler_t *, struct _cef_browser_t *, int, int) __attribute__((stdcall))
     * }
     */
    public static void on_media_access_change(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(on_media_access_change$LAYOUT, on_media_access_change$OFFSET, fieldValue);
    }

    /**
     * {@snippet lang=c :
     * int (*on_contents_bounds_change)(struct _cef_display_handler_t *, struct _cef_browser_t *, const cef_rect_t *) __attribute__((stdcall))
     * }
     */
    public final static class on_contents_bounds_change {

        private on_contents_bounds_change() {
            // Should not be called directly
        }

        /**
         * The function pointer signature, expressed as a functional interface
         */
        public interface Function {
            int apply(MemorySegment _x0, MemorySegment _x1, MemorySegment _x2);
        }

        private static final FunctionDescriptor $DESC = FunctionDescriptor.of(
            cef_master_h.C_INT,
            cef_master_h.C_POINTER,
            cef_master_h.C_POINTER,
            cef_master_h.C_POINTER
        );

        /**
         * The descriptor of this function pointer
         */
        public static FunctionDescriptor descriptor() {
            return $DESC;
        }

        private static final MethodHandle UP$MH = cef_master_h.upcallHandle(on_contents_bounds_change.Function.class, "apply", $DESC);

        /**
         * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
         * The lifetime of the returned segment is managed by {@code arena}
         */
        public static MemorySegment allocate(on_contents_bounds_change.Function fi, Arena arena) {
            return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
        }

        private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

        /**
         * Invoke the upcall stub {@code funcPtr}, with given parameters
         */
        public static int invoke(MemorySegment funcPtr, MemorySegment _x0, MemorySegment _x1, MemorySegment _x2) {
            try {
                return (int) DOWN$MH.invokeExact(funcPtr, _x0, _x1, _x2);
            } catch (Error | RuntimeException ex) {
                throw ex;
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        }
    }

    private static final AddressLayout on_contents_bounds_change$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("on_contents_bounds_change"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int (*on_contents_bounds_change)(struct _cef_display_handler_t *, struct _cef_browser_t *, const cef_rect_t *) __attribute__((stdcall))
     * }
     */
    public static final AddressLayout on_contents_bounds_change$layout() {
        return on_contents_bounds_change$LAYOUT;
    }

    private static final long on_contents_bounds_change$OFFSET = $LAYOUT.byteOffset(groupElement("on_contents_bounds_change"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int (*on_contents_bounds_change)(struct _cef_display_handler_t *, struct _cef_browser_t *, const cef_rect_t *) __attribute__((stdcall))
     * }
     */
    public static final long on_contents_bounds_change$offset() {
        return on_contents_bounds_change$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int (*on_contents_bounds_change)(struct _cef_display_handler_t *, struct _cef_browser_t *, const cef_rect_t *) __attribute__((stdcall))
     * }
     */
    public static MemorySegment on_contents_bounds_change(MemorySegment struct) {
        return struct.get(on_contents_bounds_change$LAYOUT, on_contents_bounds_change$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int (*on_contents_bounds_change)(struct _cef_display_handler_t *, struct _cef_browser_t *, const cef_rect_t *) __attribute__((stdcall))
     * }
     */
    public static void on_contents_bounds_change(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(on_contents_bounds_change$LAYOUT, on_contents_bounds_change$OFFSET, fieldValue);
    }

    /**
     * {@snippet lang=c :
     * int (*get_root_window_screen_rect)(struct _cef_display_handler_t *, struct _cef_browser_t *, cef_rect_t *) __attribute__((stdcall))
     * }
     */
    public final static class get_root_window_screen_rect {

        private get_root_window_screen_rect() {
            // Should not be called directly
        }

        /**
         * The function pointer signature, expressed as a functional interface
         */
        public interface Function {
            int apply(MemorySegment _x0, MemorySegment _x1, MemorySegment _x2);
        }

        private static final FunctionDescriptor $DESC = FunctionDescriptor.of(
            cef_master_h.C_INT,
            cef_master_h.C_POINTER,
            cef_master_h.C_POINTER,
            cef_master_h.C_POINTER
        );

        /**
         * The descriptor of this function pointer
         */
        public static FunctionDescriptor descriptor() {
            return $DESC;
        }

        private static final MethodHandle UP$MH = cef_master_h.upcallHandle(get_root_window_screen_rect.Function.class, "apply", $DESC);

        /**
         * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
         * The lifetime of the returned segment is managed by {@code arena}
         */
        public static MemorySegment allocate(get_root_window_screen_rect.Function fi, Arena arena) {
            return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
        }

        private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

        /**
         * Invoke the upcall stub {@code funcPtr}, with given parameters
         */
        public static int invoke(MemorySegment funcPtr, MemorySegment _x0, MemorySegment _x1, MemorySegment _x2) {
            try {
                return (int) DOWN$MH.invokeExact(funcPtr, _x0, _x1, _x2);
            } catch (Error | RuntimeException ex) {
                throw ex;
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        }
    }

    private static final AddressLayout get_root_window_screen_rect$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("get_root_window_screen_rect"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int (*get_root_window_screen_rect)(struct _cef_display_handler_t *, struct _cef_browser_t *, cef_rect_t *) __attribute__((stdcall))
     * }
     */
    public static final AddressLayout get_root_window_screen_rect$layout() {
        return get_root_window_screen_rect$LAYOUT;
    }

    private static final long get_root_window_screen_rect$OFFSET = $LAYOUT.byteOffset(groupElement("get_root_window_screen_rect"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int (*get_root_window_screen_rect)(struct _cef_display_handler_t *, struct _cef_browser_t *, cef_rect_t *) __attribute__((stdcall))
     * }
     */
    public static final long get_root_window_screen_rect$offset() {
        return get_root_window_screen_rect$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int (*get_root_window_screen_rect)(struct _cef_display_handler_t *, struct _cef_browser_t *, cef_rect_t *) __attribute__((stdcall))
     * }
     */
    public static MemorySegment get_root_window_screen_rect(MemorySegment struct) {
        return struct.get(get_root_window_screen_rect$LAYOUT, get_root_window_screen_rect$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int (*get_root_window_screen_rect)(struct _cef_display_handler_t *, struct _cef_browser_t *, cef_rect_t *) __attribute__((stdcall))
     * }
     */
    public static void get_root_window_screen_rect(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(get_root_window_screen_rect$LAYOUT, get_root_window_screen_rect$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

