// Generated by jextract

package com.tiji.silcef.natives;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct _cef_response_filter_t {
 *     cef_base_ref_counted_t base;
 *     int (*init_filter)(struct _cef_response_filter_t *) __attribute__((stdcall));
 *     cef_response_filter_status_t (*filter)(struct _cef_response_filter_t *, void *, size_t, size_t *, void *, size_t, size_t *) __attribute__((stdcall));
 * }
 * }
 */
public class _cef_response_filter_t {

    _cef_response_filter_t() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        _cef_base_ref_counted_t.layout().withName("base"),
        cef_app_capi_h.C_POINTER.withName("init_filter"),
        cef_app_capi_h.C_POINTER.withName("filter")
    ).withName("_cef_response_filter_t");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final GroupLayout base$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("base"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * cef_base_ref_counted_t base
     * }
     */
    public static final GroupLayout base$layout() {
        return base$LAYOUT;
    }

    private static final long base$OFFSET = $LAYOUT.byteOffset(groupElement("base"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * cef_base_ref_counted_t base
     * }
     */
    public static final long base$offset() {
        return base$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * cef_base_ref_counted_t base
     * }
     */
    public static MemorySegment base(MemorySegment struct) {
        return struct.asSlice(base$OFFSET, base$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * cef_base_ref_counted_t base
     * }
     */
    public static void base(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, base$OFFSET, base$LAYOUT.byteSize());
    }

    /**
     * {@snippet lang=c :
     * int (*init_filter)(struct _cef_response_filter_t *) __attribute__((stdcall))
     * }
     */
    public final static class init_filter {

        private init_filter() {
            // Should not be called directly
        }

        /**
         * The function pointer signature, expressed as a functional interface
         */
        public interface Function {
            int apply(MemorySegment _x0);
        }

        private static final FunctionDescriptor $DESC = FunctionDescriptor.of(
            cef_app_capi_h.C_INT,
            cef_app_capi_h.C_POINTER
        );

        /**
         * The descriptor of this function pointer
         */
        public static FunctionDescriptor descriptor() {
            return $DESC;
        }

        private static final MethodHandle UP$MH = cef_app_capi_h.upcallHandle(init_filter.Function.class, "apply", $DESC);

        /**
         * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
         * The lifetime of the returned segment is managed by {@code arena}
         */
        public static MemorySegment allocate(init_filter.Function fi, Arena arena) {
            return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
        }

        private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

        /**
         * Invoke the upcall stub {@code funcPtr}, with given parameters
         */
        public static int invoke(MemorySegment funcPtr, MemorySegment _x0) {
            try {
                return (int) DOWN$MH.invokeExact(funcPtr, _x0);
            } catch (Error | RuntimeException ex) {
                throw ex;
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        }
    }

    private static final AddressLayout init_filter$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("init_filter"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int (*init_filter)(struct _cef_response_filter_t *) __attribute__((stdcall))
     * }
     */
    public static final AddressLayout init_filter$layout() {
        return init_filter$LAYOUT;
    }

    private static final long init_filter$OFFSET = $LAYOUT.byteOffset(groupElement("init_filter"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int (*init_filter)(struct _cef_response_filter_t *) __attribute__((stdcall))
     * }
     */
    public static final long init_filter$offset() {
        return init_filter$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int (*init_filter)(struct _cef_response_filter_t *) __attribute__((stdcall))
     * }
     */
    public static MemorySegment init_filter(MemorySegment struct) {
        return struct.get(init_filter$LAYOUT, init_filter$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int (*init_filter)(struct _cef_response_filter_t *) __attribute__((stdcall))
     * }
     */
    public static void init_filter(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(init_filter$LAYOUT, init_filter$OFFSET, fieldValue);
    }

    /**
     * {@snippet lang=c :
     * cef_response_filter_status_t (*filter)(struct _cef_response_filter_t *, void *, size_t, size_t *, void *, size_t, size_t *) __attribute__((stdcall))
     * }
     */
    public final static class filter {

        private filter() {
            // Should not be called directly
        }

        /**
         * The function pointer signature, expressed as a functional interface
         */
        public interface Function {
            int apply(MemorySegment _x0, MemorySegment _x1, long _x2, MemorySegment _x3, MemorySegment _x4, long _x5, MemorySegment _x6);
        }

        private static final FunctionDescriptor $DESC = FunctionDescriptor.of(
            cef_app_capi_h.C_INT,
            cef_app_capi_h.C_POINTER,
            cef_app_capi_h.C_POINTER,
            cef_app_capi_h.C_LONG_LONG,
            cef_app_capi_h.C_POINTER,
            cef_app_capi_h.C_POINTER,
            cef_app_capi_h.C_LONG_LONG,
            cef_app_capi_h.C_POINTER
        );

        /**
         * The descriptor of this function pointer
         */
        public static FunctionDescriptor descriptor() {
            return $DESC;
        }

        private static final MethodHandle UP$MH = cef_app_capi_h.upcallHandle(filter.Function.class, "apply", $DESC);

        /**
         * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
         * The lifetime of the returned segment is managed by {@code arena}
         */
        public static MemorySegment allocate(filter.Function fi, Arena arena) {
            return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
        }

        private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

        /**
         * Invoke the upcall stub {@code funcPtr}, with given parameters
         */
        public static int invoke(MemorySegment funcPtr, MemorySegment _x0, MemorySegment _x1, long _x2, MemorySegment _x3, MemorySegment _x4, long _x5, MemorySegment _x6) {
            try {
                return (int) DOWN$MH.invokeExact(funcPtr, _x0, _x1, _x2, _x3, _x4, _x5, _x6);
            } catch (Error | RuntimeException ex) {
                throw ex;
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        }
    }

    private static final AddressLayout filter$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("filter"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * cef_response_filter_status_t (*filter)(struct _cef_response_filter_t *, void *, size_t, size_t *, void *, size_t, size_t *) __attribute__((stdcall))
     * }
     */
    public static final AddressLayout filter$layout() {
        return filter$LAYOUT;
    }

    private static final long filter$OFFSET = $LAYOUT.byteOffset(groupElement("filter"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * cef_response_filter_status_t (*filter)(struct _cef_response_filter_t *, void *, size_t, size_t *, void *, size_t, size_t *) __attribute__((stdcall))
     * }
     */
    public static final long filter$offset() {
        return filter$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * cef_response_filter_status_t (*filter)(struct _cef_response_filter_t *, void *, size_t, size_t *, void *, size_t, size_t *) __attribute__((stdcall))
     * }
     */
    public static MemorySegment filter(MemorySegment struct) {
        return struct.get(filter$LAYOUT, filter$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * cef_response_filter_status_t (*filter)(struct _cef_response_filter_t *, void *, size_t, size_t *, void *, size_t, size_t *) __attribute__((stdcall))
     * }
     */
    public static void filter(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(filter$LAYOUT, filter$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

