// Generated by jextract

package com.tiji.silcef.natives;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct _cef_cursor_info_t {
 *     cef_point_t hotspot;
 *     float image_scale_factor;
 *     void *buffer;
 *     cef_size_t size;
 * }
 * }
 */
public class _cef_cursor_info_t {

    _cef_cursor_info_t() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        _cef_point_t.layout().withName("hotspot"),
        cef_render_handler_capi_h.C_FLOAT.withName("image_scale_factor"),
        MemoryLayout.paddingLayout(4),
        cef_render_handler_capi_h.C_POINTER.withName("buffer"),
        _cef_size_t.layout().withName("size")
    ).withName("_cef_cursor_info_t");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final GroupLayout hotspot$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("hotspot"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * cef_point_t hotspot
     * }
     */
    public static final GroupLayout hotspot$layout() {
        return hotspot$LAYOUT;
    }

    private static final long hotspot$OFFSET = $LAYOUT.byteOffset(groupElement("hotspot"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * cef_point_t hotspot
     * }
     */
    public static final long hotspot$offset() {
        return hotspot$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * cef_point_t hotspot
     * }
     */
    public static MemorySegment hotspot(MemorySegment struct) {
        return struct.asSlice(hotspot$OFFSET, hotspot$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * cef_point_t hotspot
     * }
     */
    public static void hotspot(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, hotspot$OFFSET, hotspot$LAYOUT.byteSize());
    }

    private static final OfFloat image_scale_factor$LAYOUT = (OfFloat)$LAYOUT.select(groupElement("image_scale_factor"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * float image_scale_factor
     * }
     */
    public static final OfFloat image_scale_factor$layout() {
        return image_scale_factor$LAYOUT;
    }

    private static final long image_scale_factor$OFFSET = $LAYOUT.byteOffset(groupElement("image_scale_factor"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * float image_scale_factor
     * }
     */
    public static final long image_scale_factor$offset() {
        return image_scale_factor$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * float image_scale_factor
     * }
     */
    public static float image_scale_factor(MemorySegment struct) {
        return struct.get(image_scale_factor$LAYOUT, image_scale_factor$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * float image_scale_factor
     * }
     */
    public static void image_scale_factor(MemorySegment struct, float fieldValue) {
        struct.set(image_scale_factor$LAYOUT, image_scale_factor$OFFSET, fieldValue);
    }

    private static final AddressLayout buffer$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("buffer"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * void *buffer
     * }
     */
    public static final AddressLayout buffer$layout() {
        return buffer$LAYOUT;
    }

    private static final long buffer$OFFSET = $LAYOUT.byteOffset(groupElement("buffer"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * void *buffer
     * }
     */
    public static final long buffer$offset() {
        return buffer$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * void *buffer
     * }
     */
    public static MemorySegment buffer(MemorySegment struct) {
        return struct.get(buffer$LAYOUT, buffer$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * void *buffer
     * }
     */
    public static void buffer(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(buffer$LAYOUT, buffer$OFFSET, fieldValue);
    }

    private static final GroupLayout size$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("size"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * cef_size_t size
     * }
     */
    public static final GroupLayout size$layout() {
        return size$LAYOUT;
    }

    private static final long size$OFFSET = $LAYOUT.byteOffset(groupElement("size"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * cef_size_t size
     * }
     */
    public static final long size$offset() {
        return size$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * cef_size_t size
     * }
     */
    public static MemorySegment size(MemorySegment struct) {
        return struct.asSlice(size$OFFSET, size$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * cef_size_t size
     * }
     */
    public static void size(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, size$OFFSET, size$LAYOUT.byteSize());
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

