// Generated by jextract

package com.tiji.silcef.natives;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct _cef_unresponsive_process_callback_t {
 *     cef_base_ref_counted_t base;
 *     void (*wait)(struct _cef_unresponsive_process_callback_t *) __attribute__((stdcall));
 *     void (*terminate)(struct _cef_unresponsive_process_callback_t *) __attribute__((stdcall));
 * }
 * }
 */
public class _cef_unresponsive_process_callback_t {

    _cef_unresponsive_process_callback_t() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        _cef_base_ref_counted_t.layout().withName("base"),
        cef_master_h.C_POINTER.withName("wait"),
        cef_master_h.C_POINTER.withName("terminate")
    ).withName("_cef_unresponsive_process_callback_t");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final GroupLayout base$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("base"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * cef_base_ref_counted_t base
     * }
     */
    public static final GroupLayout base$layout() {
        return base$LAYOUT;
    }

    private static final long base$OFFSET = $LAYOUT.byteOffset(groupElement("base"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * cef_base_ref_counted_t base
     * }
     */
    public static final long base$offset() {
        return base$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * cef_base_ref_counted_t base
     * }
     */
    public static MemorySegment base(MemorySegment struct) {
        return struct.asSlice(base$OFFSET, base$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * cef_base_ref_counted_t base
     * }
     */
    public static void base(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, base$OFFSET, base$LAYOUT.byteSize());
    }

    /**
     * {@snippet lang=c :
     * void (*wait)(struct _cef_unresponsive_process_callback_t *) __attribute__((stdcall))
     * }
     */
    public final static class wait {

        private wait() {
            // Should not be called directly
        }

        /**
         * The function pointer signature, expressed as a functional interface
         */
        public interface Function {
            void apply(MemorySegment _x0);
        }

        private static final FunctionDescriptor $DESC = FunctionDescriptor.ofVoid(
            cef_master_h.C_POINTER
        );

        /**
         * The descriptor of this function pointer
         */
        public static FunctionDescriptor descriptor() {
            return $DESC;
        }

        private static final MethodHandle UP$MH = cef_master_h.upcallHandle(wait.Function.class, "apply", $DESC);

        /**
         * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
         * The lifetime of the returned segment is managed by {@code arena}
         */
        public static MemorySegment allocate(wait.Function fi, Arena arena) {
            return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
        }

        private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

        /**
         * Invoke the upcall stub {@code funcPtr}, with given parameters
         */
        public static void invoke(MemorySegment funcPtr, MemorySegment _x0) {
            try {
                 DOWN$MH.invokeExact(funcPtr, _x0);
            } catch (Error | RuntimeException ex) {
                throw ex;
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        }
    }

    private static final AddressLayout wait$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("wait"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * void (*wait)(struct _cef_unresponsive_process_callback_t *) __attribute__((stdcall))
     * }
     */
    public static final AddressLayout wait$layout() {
        return wait$LAYOUT;
    }

    private static final long wait$OFFSET = $LAYOUT.byteOffset(groupElement("wait"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * void (*wait)(struct _cef_unresponsive_process_callback_t *) __attribute__((stdcall))
     * }
     */
    public static final long wait$offset() {
        return wait$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * void (*wait)(struct _cef_unresponsive_process_callback_t *) __attribute__((stdcall))
     * }
     */
    public static MemorySegment wait(MemorySegment struct) {
        return struct.get(wait$LAYOUT, wait$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * void (*wait)(struct _cef_unresponsive_process_callback_t *) __attribute__((stdcall))
     * }
     */
    public static void wait(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(wait$LAYOUT, wait$OFFSET, fieldValue);
    }

    /**
     * {@snippet lang=c :
     * void (*terminate)(struct _cef_unresponsive_process_callback_t *) __attribute__((stdcall))
     * }
     */
    public final static class terminate {

        private terminate() {
            // Should not be called directly
        }

        /**
         * The function pointer signature, expressed as a functional interface
         */
        public interface Function {
            void apply(MemorySegment _x0);
        }

        private static final FunctionDescriptor $DESC = FunctionDescriptor.ofVoid(
            cef_master_h.C_POINTER
        );

        /**
         * The descriptor of this function pointer
         */
        public static FunctionDescriptor descriptor() {
            return $DESC;
        }

        private static final MethodHandle UP$MH = cef_master_h.upcallHandle(terminate.Function.class, "apply", $DESC);

        /**
         * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
         * The lifetime of the returned segment is managed by {@code arena}
         */
        public static MemorySegment allocate(terminate.Function fi, Arena arena) {
            return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
        }

        private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

        /**
         * Invoke the upcall stub {@code funcPtr}, with given parameters
         */
        public static void invoke(MemorySegment funcPtr, MemorySegment _x0) {
            try {
                 DOWN$MH.invokeExact(funcPtr, _x0);
            } catch (Error | RuntimeException ex) {
                throw ex;
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        }
    }

    private static final AddressLayout terminate$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("terminate"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * void (*terminate)(struct _cef_unresponsive_process_callback_t *) __attribute__((stdcall))
     * }
     */
    public static final AddressLayout terminate$layout() {
        return terminate$LAYOUT;
    }

    private static final long terminate$OFFSET = $LAYOUT.byteOffset(groupElement("terminate"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * void (*terminate)(struct _cef_unresponsive_process_callback_t *) __attribute__((stdcall))
     * }
     */
    public static final long terminate$offset() {
        return terminate$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * void (*terminate)(struct _cef_unresponsive_process_callback_t *) __attribute__((stdcall))
     * }
     */
    public static MemorySegment terminate(MemorySegment struct) {
        return struct.get(terminate$LAYOUT, terminate$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * void (*terminate)(struct _cef_unresponsive_process_callback_t *) __attribute__((stdcall))
     * }
     */
    public static void terminate(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(terminate$LAYOUT, terminate$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

