// Generated by jextract

package com.tiji.silcef.natives;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct _cef_base_ref_counted_t {
 *     size_t size;
 *     void (*add_ref)(struct _cef_base_ref_counted_t *) __attribute__((stdcall));
 *     int (*release)(struct _cef_base_ref_counted_t *) __attribute__((stdcall));
 *     int (*has_one_ref)(struct _cef_base_ref_counted_t *) __attribute__((stdcall));
 *     int (*has_at_least_one_ref)(struct _cef_base_ref_counted_t *) __attribute__((stdcall));
 * }
 * }
 */
public class _cef_base_ref_counted_t {

    _cef_base_ref_counted_t() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        cef_master_h.C_LONG_LONG.withName("size"),
        cef_master_h.C_POINTER.withName("add_ref"),
        cef_master_h.C_POINTER.withName("release"),
        cef_master_h.C_POINTER.withName("has_one_ref"),
        cef_master_h.C_POINTER.withName("has_at_least_one_ref")
    ).withName("_cef_base_ref_counted_t");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final OfLong size$LAYOUT = (OfLong)$LAYOUT.select(groupElement("size"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * size_t size
     * }
     */
    public static final OfLong size$layout() {
        return size$LAYOUT;
    }

    private static final long size$OFFSET = $LAYOUT.byteOffset(groupElement("size"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * size_t size
     * }
     */
    public static final long size$offset() {
        return size$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * size_t size
     * }
     */
    public static long size(MemorySegment struct) {
        return struct.get(size$LAYOUT, size$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * size_t size
     * }
     */
    public static void size(MemorySegment struct, long fieldValue) {
        struct.set(size$LAYOUT, size$OFFSET, fieldValue);
    }

    /**
     * {@snippet lang=c :
     * void (*add_ref)(struct _cef_base_ref_counted_t *) __attribute__((stdcall))
     * }
     */
    public final static class add_ref {

        private add_ref() {
            // Should not be called directly
        }

        /**
         * The function pointer signature, expressed as a functional interface
         */
        public interface Function {
            void apply(MemorySegment _x0);
        }

        private static final FunctionDescriptor $DESC = FunctionDescriptor.ofVoid(
            cef_master_h.C_POINTER
        );

        /**
         * The descriptor of this function pointer
         */
        public static FunctionDescriptor descriptor() {
            return $DESC;
        }

        private static final MethodHandle UP$MH = cef_master_h.upcallHandle(add_ref.Function.class, "apply", $DESC);

        /**
         * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
         * The lifetime of the returned segment is managed by {@code arena}
         */
        public static MemorySegment allocate(add_ref.Function fi, Arena arena) {
            return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
        }

        private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

        /**
         * Invoke the upcall stub {@code funcPtr}, with given parameters
         */
        public static void invoke(MemorySegment funcPtr, MemorySegment _x0) {
            try {
                 DOWN$MH.invokeExact(funcPtr, _x0);
            } catch (Error | RuntimeException ex) {
                throw ex;
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        }
    }

    private static final AddressLayout add_ref$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("add_ref"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * void (*add_ref)(struct _cef_base_ref_counted_t *) __attribute__((stdcall))
     * }
     */
    public static final AddressLayout add_ref$layout() {
        return add_ref$LAYOUT;
    }

    private static final long add_ref$OFFSET = $LAYOUT.byteOffset(groupElement("add_ref"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * void (*add_ref)(struct _cef_base_ref_counted_t *) __attribute__((stdcall))
     * }
     */
    public static final long add_ref$offset() {
        return add_ref$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * void (*add_ref)(struct _cef_base_ref_counted_t *) __attribute__((stdcall))
     * }
     */
    public static MemorySegment add_ref(MemorySegment struct) {
        return struct.get(add_ref$LAYOUT, add_ref$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * void (*add_ref)(struct _cef_base_ref_counted_t *) __attribute__((stdcall))
     * }
     */
    public static void add_ref(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(add_ref$LAYOUT, add_ref$OFFSET, fieldValue);
    }

    /**
     * {@snippet lang=c :
     * int (*release)(struct _cef_base_ref_counted_t *) __attribute__((stdcall))
     * }
     */
    public final static class release {

        private release() {
            // Should not be called directly
        }

        /**
         * The function pointer signature, expressed as a functional interface
         */
        public interface Function {
            int apply(MemorySegment _x0);
        }

        private static final FunctionDescriptor $DESC = FunctionDescriptor.of(
            cef_master_h.C_INT,
            cef_master_h.C_POINTER
        );

        /**
         * The descriptor of this function pointer
         */
        public static FunctionDescriptor descriptor() {
            return $DESC;
        }

        private static final MethodHandle UP$MH = cef_master_h.upcallHandle(release.Function.class, "apply", $DESC);

        /**
         * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
         * The lifetime of the returned segment is managed by {@code arena}
         */
        public static MemorySegment allocate(release.Function fi, Arena arena) {
            return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
        }

        private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

        /**
         * Invoke the upcall stub {@code funcPtr}, with given parameters
         */
        public static int invoke(MemorySegment funcPtr, MemorySegment _x0) {
            try {
                return (int) DOWN$MH.invokeExact(funcPtr, _x0);
            } catch (Error | RuntimeException ex) {
                throw ex;
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        }
    }

    private static final AddressLayout release$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("release"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int (*release)(struct _cef_base_ref_counted_t *) __attribute__((stdcall))
     * }
     */
    public static final AddressLayout release$layout() {
        return release$LAYOUT;
    }

    private static final long release$OFFSET = $LAYOUT.byteOffset(groupElement("release"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int (*release)(struct _cef_base_ref_counted_t *) __attribute__((stdcall))
     * }
     */
    public static final long release$offset() {
        return release$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int (*release)(struct _cef_base_ref_counted_t *) __attribute__((stdcall))
     * }
     */
    public static MemorySegment release(MemorySegment struct) {
        return struct.get(release$LAYOUT, release$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int (*release)(struct _cef_base_ref_counted_t *) __attribute__((stdcall))
     * }
     */
    public static void release(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(release$LAYOUT, release$OFFSET, fieldValue);
    }

    /**
     * {@snippet lang=c :
     * int (*has_one_ref)(struct _cef_base_ref_counted_t *) __attribute__((stdcall))
     * }
     */
    public final static class has_one_ref {

        private has_one_ref() {
            // Should not be called directly
        }

        /**
         * The function pointer signature, expressed as a functional interface
         */
        public interface Function {
            int apply(MemorySegment _x0);
        }

        private static final FunctionDescriptor $DESC = FunctionDescriptor.of(
            cef_master_h.C_INT,
            cef_master_h.C_POINTER
        );

        /**
         * The descriptor of this function pointer
         */
        public static FunctionDescriptor descriptor() {
            return $DESC;
        }

        private static final MethodHandle UP$MH = cef_master_h.upcallHandle(has_one_ref.Function.class, "apply", $DESC);

        /**
         * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
         * The lifetime of the returned segment is managed by {@code arena}
         */
        public static MemorySegment allocate(has_one_ref.Function fi, Arena arena) {
            return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
        }

        private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

        /**
         * Invoke the upcall stub {@code funcPtr}, with given parameters
         */
        public static int invoke(MemorySegment funcPtr, MemorySegment _x0) {
            try {
                return (int) DOWN$MH.invokeExact(funcPtr, _x0);
            } catch (Error | RuntimeException ex) {
                throw ex;
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        }
    }

    private static final AddressLayout has_one_ref$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("has_one_ref"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int (*has_one_ref)(struct _cef_base_ref_counted_t *) __attribute__((stdcall))
     * }
     */
    public static final AddressLayout has_one_ref$layout() {
        return has_one_ref$LAYOUT;
    }

    private static final long has_one_ref$OFFSET = $LAYOUT.byteOffset(groupElement("has_one_ref"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int (*has_one_ref)(struct _cef_base_ref_counted_t *) __attribute__((stdcall))
     * }
     */
    public static final long has_one_ref$offset() {
        return has_one_ref$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int (*has_one_ref)(struct _cef_base_ref_counted_t *) __attribute__((stdcall))
     * }
     */
    public static MemorySegment has_one_ref(MemorySegment struct) {
        return struct.get(has_one_ref$LAYOUT, has_one_ref$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int (*has_one_ref)(struct _cef_base_ref_counted_t *) __attribute__((stdcall))
     * }
     */
    public static void has_one_ref(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(has_one_ref$LAYOUT, has_one_ref$OFFSET, fieldValue);
    }

    /**
     * {@snippet lang=c :
     * int (*has_at_least_one_ref)(struct _cef_base_ref_counted_t *) __attribute__((stdcall))
     * }
     */
    public final static class has_at_least_one_ref {

        private has_at_least_one_ref() {
            // Should not be called directly
        }

        /**
         * The function pointer signature, expressed as a functional interface
         */
        public interface Function {
            int apply(MemorySegment _x0);
        }

        private static final FunctionDescriptor $DESC = FunctionDescriptor.of(
            cef_master_h.C_INT,
            cef_master_h.C_POINTER
        );

        /**
         * The descriptor of this function pointer
         */
        public static FunctionDescriptor descriptor() {
            return $DESC;
        }

        private static final MethodHandle UP$MH = cef_master_h.upcallHandle(has_at_least_one_ref.Function.class, "apply", $DESC);

        /**
         * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
         * The lifetime of the returned segment is managed by {@code arena}
         */
        public static MemorySegment allocate(has_at_least_one_ref.Function fi, Arena arena) {
            return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
        }

        private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

        /**
         * Invoke the upcall stub {@code funcPtr}, with given parameters
         */
        public static int invoke(MemorySegment funcPtr, MemorySegment _x0) {
            try {
                return (int) DOWN$MH.invokeExact(funcPtr, _x0);
            } catch (Error | RuntimeException ex) {
                throw ex;
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        }
    }

    private static final AddressLayout has_at_least_one_ref$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("has_at_least_one_ref"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int (*has_at_least_one_ref)(struct _cef_base_ref_counted_t *) __attribute__((stdcall))
     * }
     */
    public static final AddressLayout has_at_least_one_ref$layout() {
        return has_at_least_one_ref$LAYOUT;
    }

    private static final long has_at_least_one_ref$OFFSET = $LAYOUT.byteOffset(groupElement("has_at_least_one_ref"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int (*has_at_least_one_ref)(struct _cef_base_ref_counted_t *) __attribute__((stdcall))
     * }
     */
    public static final long has_at_least_one_ref$offset() {
        return has_at_least_one_ref$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int (*has_at_least_one_ref)(struct _cef_base_ref_counted_t *) __attribute__((stdcall))
     * }
     */
    public static MemorySegment has_at_least_one_ref(MemorySegment struct) {
        return struct.get(has_at_least_one_ref$LAYOUT, has_at_least_one_ref$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int (*has_at_least_one_ref)(struct _cef_base_ref_counted_t *) __attribute__((stdcall))
     * }
     */
    public static void has_at_least_one_ref(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(has_at_least_one_ref$LAYOUT, has_at_least_one_ref$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

