// Generated by jextract

package com.tiji.silcef.natives;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct _cef_popup_features_t {
 *     size_t size;
 *     int x;
 *     int xSet;
 *     int y;
 *     int ySet;
 *     int width;
 *     int widthSet;
 *     int height;
 *     int heightSet;
 *     int isPopup;
 * }
 * }
 */
public class _cef_popup_features_t {

    _cef_popup_features_t() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        cef_master_h.C_LONG_LONG.withName("size"),
        cef_master_h.C_INT.withName("x"),
        cef_master_h.C_INT.withName("xSet"),
        cef_master_h.C_INT.withName("y"),
        cef_master_h.C_INT.withName("ySet"),
        cef_master_h.C_INT.withName("width"),
        cef_master_h.C_INT.withName("widthSet"),
        cef_master_h.C_INT.withName("height"),
        cef_master_h.C_INT.withName("heightSet"),
        cef_master_h.C_INT.withName("isPopup"),
        MemoryLayout.paddingLayout(4)
    ).withName("_cef_popup_features_t");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final OfLong size$LAYOUT = (OfLong)$LAYOUT.select(groupElement("size"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * size_t size
     * }
     */
    public static final OfLong size$layout() {
        return size$LAYOUT;
    }

    private static final long size$OFFSET = $LAYOUT.byteOffset(groupElement("size"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * size_t size
     * }
     */
    public static final long size$offset() {
        return size$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * size_t size
     * }
     */
    public static long size(MemorySegment struct) {
        return struct.get(size$LAYOUT, size$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * size_t size
     * }
     */
    public static void size(MemorySegment struct, long fieldValue) {
        struct.set(size$LAYOUT, size$OFFSET, fieldValue);
    }

    private static final OfInt x$LAYOUT = (OfInt)$LAYOUT.select(groupElement("x"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int x
     * }
     */
    public static final OfInt x$layout() {
        return x$LAYOUT;
    }

    private static final long x$OFFSET = $LAYOUT.byteOffset(groupElement("x"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int x
     * }
     */
    public static final long x$offset() {
        return x$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int x
     * }
     */
    public static int x(MemorySegment struct) {
        return struct.get(x$LAYOUT, x$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int x
     * }
     */
    public static void x(MemorySegment struct, int fieldValue) {
        struct.set(x$LAYOUT, x$OFFSET, fieldValue);
    }

    private static final OfInt xSet$LAYOUT = (OfInt)$LAYOUT.select(groupElement("xSet"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int xSet
     * }
     */
    public static final OfInt xSet$layout() {
        return xSet$LAYOUT;
    }

    private static final long xSet$OFFSET = $LAYOUT.byteOffset(groupElement("xSet"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int xSet
     * }
     */
    public static final long xSet$offset() {
        return xSet$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int xSet
     * }
     */
    public static int xSet(MemorySegment struct) {
        return struct.get(xSet$LAYOUT, xSet$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int xSet
     * }
     */
    public static void xSet(MemorySegment struct, int fieldValue) {
        struct.set(xSet$LAYOUT, xSet$OFFSET, fieldValue);
    }

    private static final OfInt y$LAYOUT = (OfInt)$LAYOUT.select(groupElement("y"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int y
     * }
     */
    public static final OfInt y$layout() {
        return y$LAYOUT;
    }

    private static final long y$OFFSET = $LAYOUT.byteOffset(groupElement("y"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int y
     * }
     */
    public static final long y$offset() {
        return y$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int y
     * }
     */
    public static int y(MemorySegment struct) {
        return struct.get(y$LAYOUT, y$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int y
     * }
     */
    public static void y(MemorySegment struct, int fieldValue) {
        struct.set(y$LAYOUT, y$OFFSET, fieldValue);
    }

    private static final OfInt ySet$LAYOUT = (OfInt)$LAYOUT.select(groupElement("ySet"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int ySet
     * }
     */
    public static final OfInt ySet$layout() {
        return ySet$LAYOUT;
    }

    private static final long ySet$OFFSET = $LAYOUT.byteOffset(groupElement("ySet"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int ySet
     * }
     */
    public static final long ySet$offset() {
        return ySet$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int ySet
     * }
     */
    public static int ySet(MemorySegment struct) {
        return struct.get(ySet$LAYOUT, ySet$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int ySet
     * }
     */
    public static void ySet(MemorySegment struct, int fieldValue) {
        struct.set(ySet$LAYOUT, ySet$OFFSET, fieldValue);
    }

    private static final OfInt width$LAYOUT = (OfInt)$LAYOUT.select(groupElement("width"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int width
     * }
     */
    public static final OfInt width$layout() {
        return width$LAYOUT;
    }

    private static final long width$OFFSET = $LAYOUT.byteOffset(groupElement("width"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int width
     * }
     */
    public static final long width$offset() {
        return width$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int width
     * }
     */
    public static int width(MemorySegment struct) {
        return struct.get(width$LAYOUT, width$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int width
     * }
     */
    public static void width(MemorySegment struct, int fieldValue) {
        struct.set(width$LAYOUT, width$OFFSET, fieldValue);
    }

    private static final OfInt widthSet$LAYOUT = (OfInt)$LAYOUT.select(groupElement("widthSet"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int widthSet
     * }
     */
    public static final OfInt widthSet$layout() {
        return widthSet$LAYOUT;
    }

    private static final long widthSet$OFFSET = $LAYOUT.byteOffset(groupElement("widthSet"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int widthSet
     * }
     */
    public static final long widthSet$offset() {
        return widthSet$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int widthSet
     * }
     */
    public static int widthSet(MemorySegment struct) {
        return struct.get(widthSet$LAYOUT, widthSet$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int widthSet
     * }
     */
    public static void widthSet(MemorySegment struct, int fieldValue) {
        struct.set(widthSet$LAYOUT, widthSet$OFFSET, fieldValue);
    }

    private static final OfInt height$LAYOUT = (OfInt)$LAYOUT.select(groupElement("height"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int height
     * }
     */
    public static final OfInt height$layout() {
        return height$LAYOUT;
    }

    private static final long height$OFFSET = $LAYOUT.byteOffset(groupElement("height"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int height
     * }
     */
    public static final long height$offset() {
        return height$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int height
     * }
     */
    public static int height(MemorySegment struct) {
        return struct.get(height$LAYOUT, height$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int height
     * }
     */
    public static void height(MemorySegment struct, int fieldValue) {
        struct.set(height$LAYOUT, height$OFFSET, fieldValue);
    }

    private static final OfInt heightSet$LAYOUT = (OfInt)$LAYOUT.select(groupElement("heightSet"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int heightSet
     * }
     */
    public static final OfInt heightSet$layout() {
        return heightSet$LAYOUT;
    }

    private static final long heightSet$OFFSET = $LAYOUT.byteOffset(groupElement("heightSet"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int heightSet
     * }
     */
    public static final long heightSet$offset() {
        return heightSet$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int heightSet
     * }
     */
    public static int heightSet(MemorySegment struct) {
        return struct.get(heightSet$LAYOUT, heightSet$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int heightSet
     * }
     */
    public static void heightSet(MemorySegment struct, int fieldValue) {
        struct.set(heightSet$LAYOUT, heightSet$OFFSET, fieldValue);
    }

    private static final OfInt isPopup$LAYOUT = (OfInt)$LAYOUT.select(groupElement("isPopup"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int isPopup
     * }
     */
    public static final OfInt isPopup$layout() {
        return isPopup$LAYOUT;
    }

    private static final long isPopup$OFFSET = $LAYOUT.byteOffset(groupElement("isPopup"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int isPopup
     * }
     */
    public static final long isPopup$offset() {
        return isPopup$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int isPopup
     * }
     */
    public static int isPopup(MemorySegment struct) {
        return struct.get(isPopup$LAYOUT, isPopup$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int isPopup
     * }
     */
    public static void isPopup(MemorySegment struct, int fieldValue) {
        struct.set(isPopup$LAYOUT, isPopup$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

