// Generated by jextract

package com.tiji.silcef.natives;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct _cef_preference_registrar_t {
 *     cef_base_scoped_t base;
 *     int (*add_preference)(struct _cef_preference_registrar_t *, const cef_string_t *, struct _cef_value_t *) __attribute__((stdcall));
 * }
 * }
 */
public class _cef_preference_registrar_t {

    _cef_preference_registrar_t() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        _cef_base_scoped_t.layout().withName("base"),
        cef_master_h.C_POINTER.withName("add_preference")
    ).withName("_cef_preference_registrar_t");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final GroupLayout base$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("base"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * cef_base_scoped_t base
     * }
     */
    public static final GroupLayout base$layout() {
        return base$LAYOUT;
    }

    private static final long base$OFFSET = $LAYOUT.byteOffset(groupElement("base"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * cef_base_scoped_t base
     * }
     */
    public static final long base$offset() {
        return base$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * cef_base_scoped_t base
     * }
     */
    public static MemorySegment base(MemorySegment struct) {
        return struct.asSlice(base$OFFSET, base$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * cef_base_scoped_t base
     * }
     */
    public static void base(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, base$OFFSET, base$LAYOUT.byteSize());
    }

    /**
     * {@snippet lang=c :
     * int (*add_preference)(struct _cef_preference_registrar_t *, const cef_string_t *, struct _cef_value_t *) __attribute__((stdcall))
     * }
     */
    public final static class add_preference {

        private add_preference() {
            // Should not be called directly
        }

        /**
         * The function pointer signature, expressed as a functional interface
         */
        public interface Function {
            int apply(MemorySegment _x0, MemorySegment _x1, MemorySegment _x2);
        }

        private static final FunctionDescriptor $DESC = FunctionDescriptor.of(
            cef_master_h.C_INT,
            cef_master_h.C_POINTER,
            cef_master_h.C_POINTER,
            cef_master_h.C_POINTER
        );

        /**
         * The descriptor of this function pointer
         */
        public static FunctionDescriptor descriptor() {
            return $DESC;
        }

        private static final MethodHandle UP$MH = cef_master_h.upcallHandle(add_preference.Function.class, "apply", $DESC);

        /**
         * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
         * The lifetime of the returned segment is managed by {@code arena}
         */
        public static MemorySegment allocate(add_preference.Function fi, Arena arena) {
            return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
        }

        private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

        /**
         * Invoke the upcall stub {@code funcPtr}, with given parameters
         */
        public static int invoke(MemorySegment funcPtr, MemorySegment _x0, MemorySegment _x1, MemorySegment _x2) {
            try {
                return (int) DOWN$MH.invokeExact(funcPtr, _x0, _x1, _x2);
            } catch (Error | RuntimeException ex) {
                throw ex;
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        }
    }

    private static final AddressLayout add_preference$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("add_preference"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int (*add_preference)(struct _cef_preference_registrar_t *, const cef_string_t *, struct _cef_value_t *) __attribute__((stdcall))
     * }
     */
    public static final AddressLayout add_preference$layout() {
        return add_preference$LAYOUT;
    }

    private static final long add_preference$OFFSET = $LAYOUT.byteOffset(groupElement("add_preference"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int (*add_preference)(struct _cef_preference_registrar_t *, const cef_string_t *, struct _cef_value_t *) __attribute__((stdcall))
     * }
     */
    public static final long add_preference$offset() {
        return add_preference$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int (*add_preference)(struct _cef_preference_registrar_t *, const cef_string_t *, struct _cef_value_t *) __attribute__((stdcall))
     * }
     */
    public static MemorySegment add_preference(MemorySegment struct) {
        return struct.get(add_preference$LAYOUT, add_preference$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int (*add_preference)(struct _cef_preference_registrar_t *, const cef_string_t *, struct _cef_value_t *) __attribute__((stdcall))
     * }
     */
    public static void add_preference(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(add_preference$LAYOUT, add_preference$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

