// Generated by jextract

package com.tiji.silcef.natives;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * typedef struct _cef_command_line_t {
 *     cef_base_ref_counted_t base;
 *     int (*is_valid)(struct _cef_command_line_t *) __attribute__((stdcall));
 *     int (*is_read_only)(struct _cef_command_line_t *) __attribute__((stdcall));
 *     struct _cef_command_line_t *(*copy)(struct _cef_command_line_t *) __attribute__((stdcall));
 *     void (*init_from_argv)(struct _cef_command_line_t *, int, const char *const *) __attribute__((stdcall));
 *     void (*init_from_string)(struct _cef_command_line_t *, const cef_string_t *) __attribute__((stdcall));
 *     void (*reset)(struct _cef_command_line_t *) __attribute__((stdcall));
 *     void (*get_argv)(struct _cef_command_line_t *, cef_string_list_t) __attribute__((stdcall));
 *     cef_string_userfree_t (*get_command_line_string)(struct _cef_command_line_t *) __attribute__((stdcall));
 *     cef_string_userfree_t (*get_program)(struct _cef_command_line_t *) __attribute__((stdcall));
 *     void (*set_program)(struct _cef_command_line_t *, const cef_string_t *) __attribute__((stdcall));
 *     int (*has_switches)(struct _cef_command_line_t *) __attribute__((stdcall));
 *     int (*has_switch)(struct _cef_command_line_t *, const cef_string_t *) __attribute__((stdcall));
 *     cef_string_userfree_t (*get_switch_value)(struct _cef_command_line_t *, const cef_string_t *) __attribute__((stdcall));
 *     void (*get_switches)(struct _cef_command_line_t *, cef_string_map_t) __attribute__((stdcall));
 *     void (*append_switch)(struct _cef_command_line_t *, const cef_string_t *) __attribute__((stdcall));
 *     void (*append_switch_with_value)(struct _cef_command_line_t *, const cef_string_t *, const cef_string_t *) __attribute__((stdcall));
 *     int (*has_arguments)(struct _cef_command_line_t *) __attribute__((stdcall));
 *     void (*get_arguments)(struct _cef_command_line_t *, cef_string_list_t) __attribute__((stdcall));
 *     void (*append_argument)(struct _cef_command_line_t *, const cef_string_t *) __attribute__((stdcall));
 *     void (*prepend_wrapper)(struct _cef_command_line_t *, const cef_string_t *) __attribute__((stdcall));
 *     void (*remove_switch)(struct _cef_command_line_t *, const cef_string_t *) __attribute__((stdcall));
 * } cef_command_line_t
 * }
 */
public class cef_command_line_t extends _cef_command_line_t {

    cef_command_line_t() {
        // Should not be called directly
    }
}

