// Generated by jextract

package com.tiji.silcef.natives;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * typedef struct _cef_task_t {
 *     cef_base_ref_counted_t base;
 *     void (*execute)(struct _cef_task_t *) __attribute__((stdcall));
 * } cef_task_t
 * }
 */
public class cef_task_t extends _cef_task_t {

    cef_task_t() {
        // Should not be called directly
    }
}

