// Generated by jextract

package com.tiji.silcef.natives;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * typedef struct _cef_download_handler_t {
 *     cef_base_ref_counted_t base;
 *     int (*can_download)(struct _cef_download_handler_t *, struct _cef_browser_t *, const cef_string_t *, const cef_string_t *) __attribute__((stdcall));
 *     int (*on_before_download)(struct _cef_download_handler_t *, struct _cef_browser_t *, struct _cef_download_item_t *, const cef_string_t *, struct _cef_before_download_callback_t *) __attribute__((stdcall));
 *     void (*on_download_updated)(struct _cef_download_handler_t *, struct _cef_browser_t *, struct _cef_download_item_t *, struct _cef_download_item_callback_t *) __attribute__((stdcall));
 * } cef_download_handler_t
 * }
 */
public class cef_download_handler_t extends _cef_download_handler_t {

    cef_download_handler_t() {
        // Should not be called directly
    }
}

