// Generated by jextract

package com.tiji.silcef.natives;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * typedef struct _cef_run_file_dialog_callback_t {
 *     cef_base_ref_counted_t base;
 *     void (*on_file_dialog_dismissed)(struct _cef_run_file_dialog_callback_t *, cef_string_list_t) __attribute__((stdcall));
 * } cef_run_file_dialog_callback_t
 * }
 */
public class cef_run_file_dialog_callback_t extends _cef_run_file_dialog_callback_t {

    cef_run_file_dialog_callback_t() {
        // Should not be called directly
    }
}

