// Generated by jextract

package com.tiji.silcef.natives;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * typedef struct _cef_post_data_element_t {
 *     cef_base_ref_counted_t base;
 *     int (*is_read_only)(struct _cef_post_data_element_t *) __attribute__((stdcall));
 *     void (*set_to_empty)(struct _cef_post_data_element_t *) __attribute__((stdcall));
 *     void (*set_to_file)(struct _cef_post_data_element_t *, const cef_string_t *) __attribute__((stdcall));
 *     void (*set_to_bytes)(struct _cef_post_data_element_t *, size_t, const void *) __attribute__((stdcall));
 *     cef_postdataelement_type_t (*get_type)(struct _cef_post_data_element_t *) __attribute__((stdcall));
 *     cef_string_userfree_t (*get_file)(struct _cef_post_data_element_t *) __attribute__((stdcall));
 *     size_t (*get_bytes_count)(struct _cef_post_data_element_t *) __attribute__((stdcall));
 *     size_t (*get_bytes)(struct _cef_post_data_element_t *, size_t, void *) __attribute__((stdcall));
 * } cef_post_data_element_t
 * }
 */
public class cef_post_data_element_t extends _cef_post_data_element_t {

    cef_post_data_element_t() {
        // Should not be called directly
    }
}

