// Generated by jextract

package com.tiji.silcef.natives;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * typedef struct _cef_domvisitor_t {
 *     cef_base_ref_counted_t base;
 *     void (*visit)(struct _cef_domvisitor_t *, struct _cef_domdocument_t *) __attribute__((stdcall));
 * } cef_domvisitor_t
 * }
 */
public class cef_domvisitor_t extends _cef_domvisitor_t {

    cef_domvisitor_t() {
        // Should not be called directly
    }
}

