// Generated by jextract

package com.tiji.silcef.natives;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * typedef struct _cef_context_menu_handler_t {
 *     cef_base_ref_counted_t base;
 *     void (*on_before_context_menu)(struct _cef_context_menu_handler_t *, struct _cef_browser_t *, struct _cef_frame_t *, struct _cef_context_menu_params_t *, struct _cef_menu_model_t *) __attribute__((stdcall));
 *     int (*run_context_menu)(struct _cef_context_menu_handler_t *, struct _cef_browser_t *, struct _cef_frame_t *, struct _cef_context_menu_params_t *, struct _cef_menu_model_t *, struct _cef_run_context_menu_callback_t *) __attribute__((stdcall));
 *     int (*on_context_menu_command)(struct _cef_context_menu_handler_t *, struct _cef_browser_t *, struct _cef_frame_t *, struct _cef_context_menu_params_t *, int, cef_event_flags_t) __attribute__((stdcall));
 *     void (*on_context_menu_dismissed)(struct _cef_context_menu_handler_t *, struct _cef_browser_t *, struct _cef_frame_t *) __attribute__((stdcall));
 *     int (*run_quick_menu)(struct _cef_context_menu_handler_t *, struct _cef_browser_t *, struct _cef_frame_t *, const cef_point_t *, const cef_size_t *, cef_quick_menu_edit_state_flags_t, struct _cef_run_quick_menu_callback_t *) __attribute__((stdcall));
 *     int (*on_quick_menu_command)(struct _cef_context_menu_handler_t *, struct _cef_browser_t *, struct _cef_frame_t *, int, cef_event_flags_t) __attribute__((stdcall));
 *     void (*on_quick_menu_dismissed)(struct _cef_context_menu_handler_t *, struct _cef_browser_t *, struct _cef_frame_t *) __attribute__((stdcall));
 * } cef_context_menu_handler_t
 * }
 */
public class cef_context_menu_handler_t extends _cef_context_menu_handler_t {

    cef_context_menu_handler_t() {
        // Should not be called directly
    }
}

