// Generated by jextract

package com.tiji.silcef.natives;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * typedef struct _cef_frame_t {
 *     cef_base_ref_counted_t base;
 *     int (*is_valid)(struct _cef_frame_t *) __attribute__((stdcall));
 *     void (*undo)(struct _cef_frame_t *) __attribute__((stdcall));
 *     void (*redo)(struct _cef_frame_t *) __attribute__((stdcall));
 *     void (*cut)(struct _cef_frame_t *) __attribute__((stdcall));
 *     void (*copy)(struct _cef_frame_t *) __attribute__((stdcall));
 *     void (*paste)(struct _cef_frame_t *) __attribute__((stdcall));
 *     void (*paste_and_match_style)(struct _cef_frame_t *) __attribute__((stdcall));
 *     void (*del)(struct _cef_frame_t *) __attribute__((stdcall));
 *     void (*select_all)(struct _cef_frame_t *) __attribute__((stdcall));
 *     void (*view_source)(struct _cef_frame_t *) __attribute__((stdcall));
 *     void (*get_source)(struct _cef_frame_t *, struct _cef_string_visitor_t *) __attribute__((stdcall));
 *     void (*get_text)(struct _cef_frame_t *, struct _cef_string_visitor_t *) __attribute__((stdcall));
 *     void (*load_request)(struct _cef_frame_t *, struct _cef_request_t *) __attribute__((stdcall));
 *     void (*load_url)(struct _cef_frame_t *, const cef_string_t *) __attribute__((stdcall));
 *     void (*execute_java_script)(struct _cef_frame_t *, const cef_string_t *, const cef_string_t *, int) __attribute__((stdcall));
 *     int (*is_main)(struct _cef_frame_t *) __attribute__((stdcall));
 *     int (*is_focused)(struct _cef_frame_t *) __attribute__((stdcall));
 *     cef_string_userfree_t (*get_name)(struct _cef_frame_t *) __attribute__((stdcall));
 *     cef_string_userfree_t (*get_identifier)(struct _cef_frame_t *) __attribute__((stdcall));
 *     struct _cef_frame_t *(*get_parent)(struct _cef_frame_t *) __attribute__((stdcall));
 *     cef_string_userfree_t (*get_url)(struct _cef_frame_t *) __attribute__((stdcall));
 *     struct _cef_browser_t *(*get_browser)(struct _cef_frame_t *) __attribute__((stdcall));
 *     struct _cef_v8_context_t *(*get_v8_context)(struct _cef_frame_t *) __attribute__((stdcall));
 *     void (*visit_dom)(struct _cef_frame_t *, struct _cef_domvisitor_t *) __attribute__((stdcall));
 *     struct _cef_urlrequest_t *(*create_urlrequest)(struct _cef_frame_t *, struct _cef_request_t *, struct _cef_urlrequest_client_t *) __attribute__((stdcall));
 *     void (*send_process_message)(struct _cef_frame_t *, cef_process_id_t, struct _cef_process_message_t *) __attribute__((stdcall));
 * } cef_frame_t
 * }
 */
public class cef_frame_t extends _cef_frame_t {

    cef_frame_t() {
        // Should not be called directly
    }
}

