// Generated by jextract

package com.tiji.silcef.natives;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * typedef cef_string_utf16_t cef_string_t
 * }
 */
public class cef_string_t extends _cef_string_utf16_t {

    cef_string_t() {
        // Should not be called directly
    }
}

