// Generated by jextract

package com.tiji.silcef.natives;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * typedef struct _cef_base_scoped_t {
 *     size_t size;
 *     void (*del)(struct _cef_base_scoped_t *) __attribute__((stdcall));
 * } cef_base_scoped_t
 * }
 */
public class cef_base_scoped_t extends _cef_base_scoped_t {

    cef_base_scoped_t() {
        // Should not be called directly
    }
}

