// Generated by jextract

package com.tiji.silcef.natives;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * typedef struct _cef_menu_model_t {
 *     cef_base_ref_counted_t base;
 *     int (*is_sub_menu)(struct _cef_menu_model_t *) __attribute__((stdcall));
 *     int (*clear)(struct _cef_menu_model_t *) __attribute__((stdcall));
 *     size_t (*get_count)(struct _cef_menu_model_t *) __attribute__((stdcall));
 *     int (*add_separator)(struct _cef_menu_model_t *) __attribute__((stdcall));
 *     int (*add_item)(struct _cef_menu_model_t *, int, const cef_string_t *) __attribute__((stdcall));
 *     int (*add_check_item)(struct _cef_menu_model_t *, int, const cef_string_t *) __attribute__((stdcall));
 *     int (*add_radio_item)(struct _cef_menu_model_t *, int, const cef_string_t *, int) __attribute__((stdcall));
 *     struct _cef_menu_model_t *(*add_sub_menu)(struct _cef_menu_model_t *, int, const cef_string_t *) __attribute__((stdcall));
 *     int (*insert_separator_at)(struct _cef_menu_model_t *, size_t) __attribute__((stdcall));
 *     int (*insert_item_at)(struct _cef_menu_model_t *, size_t, int, const cef_string_t *) __attribute__((stdcall));
 *     int (*insert_check_item_at)(struct _cef_menu_model_t *, size_t, int, const cef_string_t *) __attribute__((stdcall));
 *     int (*insert_radio_item_at)(struct _cef_menu_model_t *, size_t, int, const cef_string_t *, int) __attribute__((stdcall));
 *     struct _cef_menu_model_t *(*insert_sub_menu_at)(struct _cef_menu_model_t *, size_t, int, const cef_string_t *) __attribute__((stdcall));
 *     int (*remove)(struct _cef_menu_model_t *, int) __attribute__((stdcall));
 *     int (*remove_at)(struct _cef_menu_model_t *, size_t) __attribute__((stdcall));
 *     int (*get_index_of)(struct _cef_menu_model_t *, int) __attribute__((stdcall));
 *     int (*get_command_id_at)(struct _cef_menu_model_t *, size_t) __attribute__((stdcall));
 *     int (*set_command_id_at)(struct _cef_menu_model_t *, size_t, int) __attribute__((stdcall));
 *     cef_string_userfree_t (*get_label)(struct _cef_menu_model_t *, int) __attribute__((stdcall));
 *     cef_string_userfree_t (*get_label_at)(struct _cef_menu_model_t *, size_t) __attribute__((stdcall));
 *     int (*set_label)(struct _cef_menu_model_t *, int, const cef_string_t *) __attribute__((stdcall));
 *     int (*set_label_at)(struct _cef_menu_model_t *, size_t, const cef_string_t *) __attribute__((stdcall));
 *     cef_menu_item_type_t (*get_type)(struct _cef_menu_model_t *, int) __attribute__((stdcall));
 *     cef_menu_item_type_t (*get_type_at)(struct _cef_menu_model_t *, size_t) __attribute__((stdcall));
 *     int (*get_group_id)(struct _cef_menu_model_t *, int) __attribute__((stdcall));
 *     int (*get_group_id_at)(struct _cef_menu_model_t *, size_t) __attribute__((stdcall));
 *     int (*set_group_id)(struct _cef_menu_model_t *, int, int) __attribute__((stdcall));
 *     int (*set_group_id_at)(struct _cef_menu_model_t *, size_t, int) __attribute__((stdcall));
 *     struct _cef_menu_model_t *(*get_sub_menu)(struct _cef_menu_model_t *, int) __attribute__((stdcall));
 *     struct _cef_menu_model_t *(*get_sub_menu_at)(struct _cef_menu_model_t *, size_t) __attribute__((stdcall));
 *     int (*is_visible)(struct _cef_menu_model_t *, int) __attribute__((stdcall));
 *     int (*is_visible_at)(struct _cef_menu_model_t *, size_t) __attribute__((stdcall));
 *     int (*set_visible)(struct _cef_menu_model_t *, int, int) __attribute__((stdcall));
 *     int (*set_visible_at)(struct _cef_menu_model_t *, size_t, int) __attribute__((stdcall));
 *     int (*is_enabled)(struct _cef_menu_model_t *, int) __attribute__((stdcall));
 *     int (*is_enabled_at)(struct _cef_menu_model_t *, size_t) __attribute__((stdcall));
 *     int (*set_enabled)(struct _cef_menu_model_t *, int, int) __attribute__((stdcall));
 *     int (*set_enabled_at)(struct _cef_menu_model_t *, size_t, int) __attribute__((stdcall));
 *     int (*is_checked)(struct _cef_menu_model_t *, int) __attribute__((stdcall));
 *     int (*is_checked_at)(struct _cef_menu_model_t *, size_t) __attribute__((stdcall));
 *     int (*set_checked)(struct _cef_menu_model_t *, int, int) __attribute__((stdcall));
 *     int (*set_checked_at)(struct _cef_menu_model_t *, size_t, int) __attribute__((stdcall));
 *     int (*has_accelerator)(struct _cef_menu_model_t *, int) __attribute__((stdcall));
 *     int (*has_accelerator_at)(struct _cef_menu_model_t *, size_t) __attribute__((stdcall));
 *     int (*set_accelerator)(struct _cef_menu_model_t *, int, int, int, int, int) __attribute__((stdcall));
 *     int (*set_accelerator_at)(struct _cef_menu_model_t *, size_t, int, int, int, int) __attribute__((stdcall));
 *     int (*remove_accelerator)(struct _cef_menu_model_t *, int) __attribute__((stdcall));
 *     int (*remove_accelerator_at)(struct _cef_menu_model_t *, size_t) __attribute__((stdcall));
 *     int (*get_accelerator)(struct _cef_menu_model_t *, int, int *, int *, int *, int *) __attribute__((stdcall));
 *     int (*get_accelerator_at)(struct _cef_menu_model_t *, size_t, int *, int *, int *, int *) __attribute__((stdcall));
 *     int (*set_color)(struct _cef_menu_model_t *, int, cef_menu_color_type_t, cef_color_t) __attribute__((stdcall));
 *     int (*set_color_at)(struct _cef_menu_model_t *, int, cef_menu_color_type_t, cef_color_t) __attribute__((stdcall));
 *     int (*get_color)(struct _cef_menu_model_t *, int, cef_menu_color_type_t, cef_color_t *) __attribute__((stdcall));
 *     int (*get_color_at)(struct _cef_menu_model_t *, int, cef_menu_color_type_t, cef_color_t *) __attribute__((stdcall));
 *     int (*set_font_list)(struct _cef_menu_model_t *, int, const cef_string_t *) __attribute__((stdcall));
 *     int (*set_font_list_at)(struct _cef_menu_model_t *, int, const cef_string_t *) __attribute__((stdcall));
 * } cef_menu_model_t
 * }
 */
public class cef_menu_model_t extends _cef_menu_model_t {

    cef_menu_model_t() {
        // Should not be called directly
    }
}

