// Generated by jextract

package com.tiji.silcef.natives;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * typedef struct _cef_v8_accessor_t {
 *     cef_base_ref_counted_t base;
 *     int (*get)(struct _cef_v8_accessor_t *, const cef_string_t *, struct _cef_v8_value_t *, struct _cef_v8_value_t **, cef_string_t *) __attribute__((stdcall));
 *     int (*set)(struct _cef_v8_accessor_t *, const cef_string_t *, struct _cef_v8_value_t *, struct _cef_v8_value_t *, cef_string_t *) __attribute__((stdcall));
 * } cef_v8_accessor_t
 * }
 */
public class cef_v8_accessor_t extends _cef_v8_accessor_t {

    cef_v8_accessor_t() {
        // Should not be called directly
    }
}

