// Generated by jextract

package com.tiji.silcef.natives;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * typedef struct _cef_audio_handler_t {
 *     cef_base_ref_counted_t base;
 *     int (*get_audio_parameters)(struct _cef_audio_handler_t *, struct _cef_browser_t *, cef_audio_parameters_t *) __attribute__((stdcall));
 *     void (*on_audio_stream_started)(struct _cef_audio_handler_t *, struct _cef_browser_t *, const cef_audio_parameters_t *, int) __attribute__((stdcall));
 *     void (*on_audio_stream_packet)(struct _cef_audio_handler_t *, struct _cef_browser_t *, const float **, int, int64_t) __attribute__((stdcall));
 *     void (*on_audio_stream_stopped)(struct _cef_audio_handler_t *, struct _cef_browser_t *) __attribute__((stdcall));
 *     void (*on_audio_stream_error)(struct _cef_audio_handler_t *, struct _cef_browser_t *, const cef_string_t *) __attribute__((stdcall));
 * } cef_audio_handler_t
 * }
 */
public class cef_audio_handler_t extends _cef_audio_handler_t {

    cef_audio_handler_t() {
        // Should not be called directly
    }
}

