// Generated by jextract

package com.tiji.silcef.natives;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct IClientSecurityVtbl {
 *     HRESULT (*QueryInterface)(IClientSecurity *, const IID *const, void **) __attribute__((stdcall));
 *     ULONG (*AddRef)(IClientSecurity *) __attribute__((stdcall));
 *     ULONG (*Release)(IClientSecurity *) __attribute__((stdcall));
 *     HRESULT (*QueryBlanket)(IClientSecurity *, IUnknown *, DWORD *, DWORD *, OLECHAR **, DWORD *, DWORD *, void **, DWORD *) __attribute__((stdcall));
 *     HRESULT (*SetBlanket)(IClientSecurity *, IUnknown *, DWORD, DWORD, OLECHAR *, DWORD, DWORD, void *, DWORD) __attribute__((stdcall));
 *     HRESULT (*CopyProxy)(IClientSecurity *, IUnknown *, IUnknown **) __attribute__((stdcall));
 * }
 * }
 */
public class IClientSecurityVtbl {

    IClientSecurityVtbl() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        cef_render_handler_capi_h.C_POINTER.withName("QueryInterface"),
        cef_render_handler_capi_h.C_POINTER.withName("AddRef"),
        cef_render_handler_capi_h.C_POINTER.withName("Release"),
        cef_render_handler_capi_h.C_POINTER.withName("QueryBlanket"),
        cef_render_handler_capi_h.C_POINTER.withName("SetBlanket"),
        cef_render_handler_capi_h.C_POINTER.withName("CopyProxy")
    ).withName("IClientSecurityVtbl");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    /**
     * {@snippet lang=c :
     * HRESULT (*QueryInterface)(IClientSecurity *, const IID *const, void **) __attribute__((stdcall))
     * }
     */
    public final static class QueryInterface {

        private QueryInterface() {
            // Should not be called directly
        }

        /**
         * The function pointer signature, expressed as a functional interface
         */
        public interface Function {
            int apply(MemorySegment _x0, MemorySegment _x1, MemorySegment _x2);
        }

        private static final FunctionDescriptor $DESC = FunctionDescriptor.of(
            cef_render_handler_capi_h.C_LONG,
            cef_render_handler_capi_h.C_POINTER,
            cef_render_handler_capi_h.C_POINTER,
            cef_render_handler_capi_h.C_POINTER
        );

        /**
         * The descriptor of this function pointer
         */
        public static FunctionDescriptor descriptor() {
            return $DESC;
        }

        private static final MethodHandle UP$MH = cef_render_handler_capi_h.upcallHandle(QueryInterface.Function.class, "apply", $DESC);

        /**
         * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
         * The lifetime of the returned segment is managed by {@code arena}
         */
        public static MemorySegment allocate(QueryInterface.Function fi, Arena arena) {
            return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
        }

        private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

        /**
         * Invoke the upcall stub {@code funcPtr}, with given parameters
         */
        public static int invoke(MemorySegment funcPtr, MemorySegment _x0, MemorySegment _x1, MemorySegment _x2) {
            try {
                return (int) DOWN$MH.invokeExact(funcPtr, _x0, _x1, _x2);
            } catch (Error | RuntimeException ex) {
                throw ex;
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        }
    }

    private static final AddressLayout QueryInterface$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("QueryInterface"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * HRESULT (*QueryInterface)(IClientSecurity *, const IID *const, void **) __attribute__((stdcall))
     * }
     */
    public static final AddressLayout QueryInterface$layout() {
        return QueryInterface$LAYOUT;
    }

    private static final long QueryInterface$OFFSET = $LAYOUT.byteOffset(groupElement("QueryInterface"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * HRESULT (*QueryInterface)(IClientSecurity *, const IID *const, void **) __attribute__((stdcall))
     * }
     */
    public static final long QueryInterface$offset() {
        return QueryInterface$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * HRESULT (*QueryInterface)(IClientSecurity *, const IID *const, void **) __attribute__((stdcall))
     * }
     */
    public static MemorySegment QueryInterface(MemorySegment struct) {
        return struct.get(QueryInterface$LAYOUT, QueryInterface$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * HRESULT (*QueryInterface)(IClientSecurity *, const IID *const, void **) __attribute__((stdcall))
     * }
     */
    public static void QueryInterface(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(QueryInterface$LAYOUT, QueryInterface$OFFSET, fieldValue);
    }

    /**
     * {@snippet lang=c :
     * ULONG (*AddRef)(IClientSecurity *) __attribute__((stdcall))
     * }
     */
    public final static class AddRef {

        private AddRef() {
            // Should not be called directly
        }

        /**
         * The function pointer signature, expressed as a functional interface
         */
        public interface Function {
            int apply(MemorySegment _x0);
        }

        private static final FunctionDescriptor $DESC = FunctionDescriptor.of(
            cef_render_handler_capi_h.C_LONG,
            cef_render_handler_capi_h.C_POINTER
        );

        /**
         * The descriptor of this function pointer
         */
        public static FunctionDescriptor descriptor() {
            return $DESC;
        }

        private static final MethodHandle UP$MH = cef_render_handler_capi_h.upcallHandle(AddRef.Function.class, "apply", $DESC);

        /**
         * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
         * The lifetime of the returned segment is managed by {@code arena}
         */
        public static MemorySegment allocate(AddRef.Function fi, Arena arena) {
            return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
        }

        private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

        /**
         * Invoke the upcall stub {@code funcPtr}, with given parameters
         */
        public static int invoke(MemorySegment funcPtr, MemorySegment _x0) {
            try {
                return (int) DOWN$MH.invokeExact(funcPtr, _x0);
            } catch (Error | RuntimeException ex) {
                throw ex;
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        }
    }

    private static final AddressLayout AddRef$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("AddRef"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * ULONG (*AddRef)(IClientSecurity *) __attribute__((stdcall))
     * }
     */
    public static final AddressLayout AddRef$layout() {
        return AddRef$LAYOUT;
    }

    private static final long AddRef$OFFSET = $LAYOUT.byteOffset(groupElement("AddRef"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * ULONG (*AddRef)(IClientSecurity *) __attribute__((stdcall))
     * }
     */
    public static final long AddRef$offset() {
        return AddRef$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * ULONG (*AddRef)(IClientSecurity *) __attribute__((stdcall))
     * }
     */
    public static MemorySegment AddRef(MemorySegment struct) {
        return struct.get(AddRef$LAYOUT, AddRef$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * ULONG (*AddRef)(IClientSecurity *) __attribute__((stdcall))
     * }
     */
    public static void AddRef(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(AddRef$LAYOUT, AddRef$OFFSET, fieldValue);
    }

    /**
     * {@snippet lang=c :
     * ULONG (*Release)(IClientSecurity *) __attribute__((stdcall))
     * }
     */
    public final static class Release {

        private Release() {
            // Should not be called directly
        }

        /**
         * The function pointer signature, expressed as a functional interface
         */
        public interface Function {
            int apply(MemorySegment _x0);
        }

        private static final FunctionDescriptor $DESC = FunctionDescriptor.of(
            cef_render_handler_capi_h.C_LONG,
            cef_render_handler_capi_h.C_POINTER
        );

        /**
         * The descriptor of this function pointer
         */
        public static FunctionDescriptor descriptor() {
            return $DESC;
        }

        private static final MethodHandle UP$MH = cef_render_handler_capi_h.upcallHandle(Release.Function.class, "apply", $DESC);

        /**
         * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
         * The lifetime of the returned segment is managed by {@code arena}
         */
        public static MemorySegment allocate(Release.Function fi, Arena arena) {
            return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
        }

        private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

        /**
         * Invoke the upcall stub {@code funcPtr}, with given parameters
         */
        public static int invoke(MemorySegment funcPtr, MemorySegment _x0) {
            try {
                return (int) DOWN$MH.invokeExact(funcPtr, _x0);
            } catch (Error | RuntimeException ex) {
                throw ex;
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        }
    }

    private static final AddressLayout Release$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("Release"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * ULONG (*Release)(IClientSecurity *) __attribute__((stdcall))
     * }
     */
    public static final AddressLayout Release$layout() {
        return Release$LAYOUT;
    }

    private static final long Release$OFFSET = $LAYOUT.byteOffset(groupElement("Release"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * ULONG (*Release)(IClientSecurity *) __attribute__((stdcall))
     * }
     */
    public static final long Release$offset() {
        return Release$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * ULONG (*Release)(IClientSecurity *) __attribute__((stdcall))
     * }
     */
    public static MemorySegment Release(MemorySegment struct) {
        return struct.get(Release$LAYOUT, Release$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * ULONG (*Release)(IClientSecurity *) __attribute__((stdcall))
     * }
     */
    public static void Release(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(Release$LAYOUT, Release$OFFSET, fieldValue);
    }

    /**
     * {@snippet lang=c :
     * HRESULT (*QueryBlanket)(IClientSecurity *, IUnknown *, DWORD *, DWORD *, OLECHAR **, DWORD *, DWORD *, void **, DWORD *) __attribute__((stdcall))
     * }
     */
    public final static class QueryBlanket {

        private QueryBlanket() {
            // Should not be called directly
        }

        /**
         * The function pointer signature, expressed as a functional interface
         */
        public interface Function {
            int apply(MemorySegment _x0, MemorySegment _x1, MemorySegment _x2, MemorySegment _x3, MemorySegment _x4, MemorySegment _x5, MemorySegment _x6, MemorySegment _x7, MemorySegment _x8);
        }

        private static final FunctionDescriptor $DESC = FunctionDescriptor.of(
            cef_render_handler_capi_h.C_LONG,
            cef_render_handler_capi_h.C_POINTER,
            cef_render_handler_capi_h.C_POINTER,
            cef_render_handler_capi_h.C_POINTER,
            cef_render_handler_capi_h.C_POINTER,
            cef_render_handler_capi_h.C_POINTER,
            cef_render_handler_capi_h.C_POINTER,
            cef_render_handler_capi_h.C_POINTER,
            cef_render_handler_capi_h.C_POINTER,
            cef_render_handler_capi_h.C_POINTER
        );

        /**
         * The descriptor of this function pointer
         */
        public static FunctionDescriptor descriptor() {
            return $DESC;
        }

        private static final MethodHandle UP$MH = cef_render_handler_capi_h.upcallHandle(QueryBlanket.Function.class, "apply", $DESC);

        /**
         * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
         * The lifetime of the returned segment is managed by {@code arena}
         */
        public static MemorySegment allocate(QueryBlanket.Function fi, Arena arena) {
            return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
        }

        private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

        /**
         * Invoke the upcall stub {@code funcPtr}, with given parameters
         */
        public static int invoke(MemorySegment funcPtr, MemorySegment _x0, MemorySegment _x1, MemorySegment _x2, MemorySegment _x3, MemorySegment _x4, MemorySegment _x5, MemorySegment _x6, MemorySegment _x7, MemorySegment _x8) {
            try {
                return (int) DOWN$MH.invokeExact(funcPtr, _x0, _x1, _x2, _x3, _x4, _x5, _x6, _x7, _x8);
            } catch (Error | RuntimeException ex) {
                throw ex;
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        }
    }

    private static final AddressLayout QueryBlanket$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("QueryBlanket"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * HRESULT (*QueryBlanket)(IClientSecurity *, IUnknown *, DWORD *, DWORD *, OLECHAR **, DWORD *, DWORD *, void **, DWORD *) __attribute__((stdcall))
     * }
     */
    public static final AddressLayout QueryBlanket$layout() {
        return QueryBlanket$LAYOUT;
    }

    private static final long QueryBlanket$OFFSET = $LAYOUT.byteOffset(groupElement("QueryBlanket"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * HRESULT (*QueryBlanket)(IClientSecurity *, IUnknown *, DWORD *, DWORD *, OLECHAR **, DWORD *, DWORD *, void **, DWORD *) __attribute__((stdcall))
     * }
     */
    public static final long QueryBlanket$offset() {
        return QueryBlanket$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * HRESULT (*QueryBlanket)(IClientSecurity *, IUnknown *, DWORD *, DWORD *, OLECHAR **, DWORD *, DWORD *, void **, DWORD *) __attribute__((stdcall))
     * }
     */
    public static MemorySegment QueryBlanket(MemorySegment struct) {
        return struct.get(QueryBlanket$LAYOUT, QueryBlanket$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * HRESULT (*QueryBlanket)(IClientSecurity *, IUnknown *, DWORD *, DWORD *, OLECHAR **, DWORD *, DWORD *, void **, DWORD *) __attribute__((stdcall))
     * }
     */
    public static void QueryBlanket(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(QueryBlanket$LAYOUT, QueryBlanket$OFFSET, fieldValue);
    }

    /**
     * {@snippet lang=c :
     * HRESULT (*SetBlanket)(IClientSecurity *, IUnknown *, DWORD, DWORD, OLECHAR *, DWORD, DWORD, void *, DWORD) __attribute__((stdcall))
     * }
     */
    public final static class SetBlanket {

        private SetBlanket() {
            // Should not be called directly
        }

        /**
         * The function pointer signature, expressed as a functional interface
         */
        public interface Function {
            int apply(MemorySegment _x0, MemorySegment _x1, int _x2, int _x3, MemorySegment _x4, int _x5, int _x6, MemorySegment _x7, int _x8);
        }

        private static final FunctionDescriptor $DESC = FunctionDescriptor.of(
            cef_render_handler_capi_h.C_LONG,
            cef_render_handler_capi_h.C_POINTER,
            cef_render_handler_capi_h.C_POINTER,
            cef_render_handler_capi_h.C_LONG,
            cef_render_handler_capi_h.C_LONG,
            cef_render_handler_capi_h.C_POINTER,
            cef_render_handler_capi_h.C_LONG,
            cef_render_handler_capi_h.C_LONG,
            cef_render_handler_capi_h.C_POINTER,
            cef_render_handler_capi_h.C_LONG
        );

        /**
         * The descriptor of this function pointer
         */
        public static FunctionDescriptor descriptor() {
            return $DESC;
        }

        private static final MethodHandle UP$MH = cef_render_handler_capi_h.upcallHandle(SetBlanket.Function.class, "apply", $DESC);

        /**
         * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
         * The lifetime of the returned segment is managed by {@code arena}
         */
        public static MemorySegment allocate(SetBlanket.Function fi, Arena arena) {
            return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
        }

        private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

        /**
         * Invoke the upcall stub {@code funcPtr}, with given parameters
         */
        public static int invoke(MemorySegment funcPtr, MemorySegment _x0, MemorySegment _x1, int _x2, int _x3, MemorySegment _x4, int _x5, int _x6, MemorySegment _x7, int _x8) {
            try {
                return (int) DOWN$MH.invokeExact(funcPtr, _x0, _x1, _x2, _x3, _x4, _x5, _x6, _x7, _x8);
            } catch (Error | RuntimeException ex) {
                throw ex;
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        }
    }

    private static final AddressLayout SetBlanket$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("SetBlanket"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * HRESULT (*SetBlanket)(IClientSecurity *, IUnknown *, DWORD, DWORD, OLECHAR *, DWORD, DWORD, void *, DWORD) __attribute__((stdcall))
     * }
     */
    public static final AddressLayout SetBlanket$layout() {
        return SetBlanket$LAYOUT;
    }

    private static final long SetBlanket$OFFSET = $LAYOUT.byteOffset(groupElement("SetBlanket"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * HRESULT (*SetBlanket)(IClientSecurity *, IUnknown *, DWORD, DWORD, OLECHAR *, DWORD, DWORD, void *, DWORD) __attribute__((stdcall))
     * }
     */
    public static final long SetBlanket$offset() {
        return SetBlanket$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * HRESULT (*SetBlanket)(IClientSecurity *, IUnknown *, DWORD, DWORD, OLECHAR *, DWORD, DWORD, void *, DWORD) __attribute__((stdcall))
     * }
     */
    public static MemorySegment SetBlanket(MemorySegment struct) {
        return struct.get(SetBlanket$LAYOUT, SetBlanket$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * HRESULT (*SetBlanket)(IClientSecurity *, IUnknown *, DWORD, DWORD, OLECHAR *, DWORD, DWORD, void *, DWORD) __attribute__((stdcall))
     * }
     */
    public static void SetBlanket(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(SetBlanket$LAYOUT, SetBlanket$OFFSET, fieldValue);
    }

    /**
     * {@snippet lang=c :
     * HRESULT (*CopyProxy)(IClientSecurity *, IUnknown *, IUnknown **) __attribute__((stdcall))
     * }
     */
    public final static class CopyProxy {

        private CopyProxy() {
            // Should not be called directly
        }

        /**
         * The function pointer signature, expressed as a functional interface
         */
        public interface Function {
            int apply(MemorySegment _x0, MemorySegment _x1, MemorySegment _x2);
        }

        private static final FunctionDescriptor $DESC = FunctionDescriptor.of(
            cef_render_handler_capi_h.C_LONG,
            cef_render_handler_capi_h.C_POINTER,
            cef_render_handler_capi_h.C_POINTER,
            cef_render_handler_capi_h.C_POINTER
        );

        /**
         * The descriptor of this function pointer
         */
        public static FunctionDescriptor descriptor() {
            return $DESC;
        }

        private static final MethodHandle UP$MH = cef_render_handler_capi_h.upcallHandle(CopyProxy.Function.class, "apply", $DESC);

        /**
         * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
         * The lifetime of the returned segment is managed by {@code arena}
         */
        public static MemorySegment allocate(CopyProxy.Function fi, Arena arena) {
            return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
        }

        private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

        /**
         * Invoke the upcall stub {@code funcPtr}, with given parameters
         */
        public static int invoke(MemorySegment funcPtr, MemorySegment _x0, MemorySegment _x1, MemorySegment _x2) {
            try {
                return (int) DOWN$MH.invokeExact(funcPtr, _x0, _x1, _x2);
            } catch (Error | RuntimeException ex) {
                throw ex;
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        }
    }

    private static final AddressLayout CopyProxy$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("CopyProxy"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * HRESULT (*CopyProxy)(IClientSecurity *, IUnknown *, IUnknown **) __attribute__((stdcall))
     * }
     */
    public static final AddressLayout CopyProxy$layout() {
        return CopyProxy$LAYOUT;
    }

    private static final long CopyProxy$OFFSET = $LAYOUT.byteOffset(groupElement("CopyProxy"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * HRESULT (*CopyProxy)(IClientSecurity *, IUnknown *, IUnknown **) __attribute__((stdcall))
     * }
     */
    public static final long CopyProxy$offset() {
        return CopyProxy$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * HRESULT (*CopyProxy)(IClientSecurity *, IUnknown *, IUnknown **) __attribute__((stdcall))
     * }
     */
    public static MemorySegment CopyProxy(MemorySegment struct) {
        return struct.get(CopyProxy$LAYOUT, CopyProxy$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * HRESULT (*CopyProxy)(IClientSecurity *, IUnknown *, IUnknown **) __attribute__((stdcall))
     * }
     */
    public static void CopyProxy(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(CopyProxy$LAYOUT, CopyProxy$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

