// Generated by jextract

package com.tiji.silcef.natives;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct ICreateTypeInfoVtbl {
 *     HRESULT (*QueryInterface)(ICreateTypeInfo *, const IID *const, void **) __attribute__((stdcall));
 *     ULONG (*AddRef)(ICreateTypeInfo *) __attribute__((stdcall));
 *     ULONG (*Release)(ICreateTypeInfo *) __attribute__((stdcall));
 *     HRESULT (*SetGuid)(ICreateTypeInfo *, const GUID *const) __attribute__((stdcall));
 *     HRESULT (*SetTypeFlags)(ICreateTypeInfo *, UINT) __attribute__((stdcall));
 *     HRESULT (*SetDocString)(ICreateTypeInfo *, LPOLESTR) __attribute__((stdcall));
 *     HRESULT (*SetHelpContext)(ICreateTypeInfo *, DWORD) __attribute__((stdcall));
 *     HRESULT (*SetVersion)(ICreateTypeInfo *, WORD, WORD) __attribute__((stdcall));
 *     HRESULT (*AddRefTypeInfo)(ICreateTypeInfo *, ITypeInfo *, HREFTYPE *) __attribute__((stdcall));
 *     HRESULT (*AddFuncDesc)(ICreateTypeInfo *, UINT, FUNCDESC *) __attribute__((stdcall));
 *     HRESULT (*AddImplType)(ICreateTypeInfo *, UINT, HREFTYPE) __attribute__((stdcall));
 *     HRESULT (*SetImplTypeFlags)(ICreateTypeInfo *, UINT, INT) __attribute__((stdcall));
 *     HRESULT (*SetAlignment)(ICreateTypeInfo *, WORD) __attribute__((stdcall));
 *     HRESULT (*SetSchema)(ICreateTypeInfo *, LPOLESTR) __attribute__((stdcall));
 *     HRESULT (*AddVarDesc)(ICreateTypeInfo *, UINT, VARDESC *) __attribute__((stdcall));
 *     HRESULT (*SetFuncAndParamNames)(ICreateTypeInfo *, UINT, LPOLESTR *, UINT) __attribute__((stdcall));
 *     HRESULT (*SetVarName)(ICreateTypeInfo *, UINT, LPOLESTR) __attribute__((stdcall));
 *     HRESULT (*SetTypeDescAlias)(ICreateTypeInfo *, TYPEDESC *) __attribute__((stdcall));
 *     HRESULT (*DefineFuncAsDllEntry)(ICreateTypeInfo *, UINT, LPOLESTR, LPOLESTR) __attribute__((stdcall));
 *     HRESULT (*SetFuncDocString)(ICreateTypeInfo *, UINT, LPOLESTR) __attribute__((stdcall));
 *     HRESULT (*SetVarDocString)(ICreateTypeInfo *, UINT, LPOLESTR) __attribute__((stdcall));
 *     HRESULT (*SetFuncHelpContext)(ICreateTypeInfo *, UINT, DWORD) __attribute__((stdcall));
 *     HRESULT (*SetVarHelpContext)(ICreateTypeInfo *, UINT, DWORD) __attribute__((stdcall));
 *     HRESULT (*SetMops)(ICreateTypeInfo *, UINT, BSTR) __attribute__((stdcall));
 *     HRESULT (*SetTypeIdldesc)(ICreateTypeInfo *, IDLDESC *) __attribute__((stdcall));
 *     HRESULT (*LayOut)(ICreateTypeInfo *) __attribute__((stdcall));
 * }
 * }
 */
public class ICreateTypeInfoVtbl {

    ICreateTypeInfoVtbl() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        cef_render_handler_capi_h.C_POINTER.withName("QueryInterface"),
        cef_render_handler_capi_h.C_POINTER.withName("AddRef"),
        cef_render_handler_capi_h.C_POINTER.withName("Release"),
        cef_render_handler_capi_h.C_POINTER.withName("SetGuid"),
        cef_render_handler_capi_h.C_POINTER.withName("SetTypeFlags"),
        cef_render_handler_capi_h.C_POINTER.withName("SetDocString"),
        cef_render_handler_capi_h.C_POINTER.withName("SetHelpContext"),
        cef_render_handler_capi_h.C_POINTER.withName("SetVersion"),
        cef_render_handler_capi_h.C_POINTER.withName("AddRefTypeInfo"),
        cef_render_handler_capi_h.C_POINTER.withName("AddFuncDesc"),
        cef_render_handler_capi_h.C_POINTER.withName("AddImplType"),
        cef_render_handler_capi_h.C_POINTER.withName("SetImplTypeFlags"),
        cef_render_handler_capi_h.C_POINTER.withName("SetAlignment"),
        cef_render_handler_capi_h.C_POINTER.withName("SetSchema"),
        cef_render_handler_capi_h.C_POINTER.withName("AddVarDesc"),
        cef_render_handler_capi_h.C_POINTER.withName("SetFuncAndParamNames"),
        cef_render_handler_capi_h.C_POINTER.withName("SetVarName"),
        cef_render_handler_capi_h.C_POINTER.withName("SetTypeDescAlias"),
        cef_render_handler_capi_h.C_POINTER.withName("DefineFuncAsDllEntry"),
        cef_render_handler_capi_h.C_POINTER.withName("SetFuncDocString"),
        cef_render_handler_capi_h.C_POINTER.withName("SetVarDocString"),
        cef_render_handler_capi_h.C_POINTER.withName("SetFuncHelpContext"),
        cef_render_handler_capi_h.C_POINTER.withName("SetVarHelpContext"),
        cef_render_handler_capi_h.C_POINTER.withName("SetMops"),
        cef_render_handler_capi_h.C_POINTER.withName("SetTypeIdldesc"),
        cef_render_handler_capi_h.C_POINTER.withName("LayOut")
    ).withName("ICreateTypeInfoVtbl");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    /**
     * {@snippet lang=c :
     * HRESULT (*QueryInterface)(ICreateTypeInfo *, const IID *const, void **) __attribute__((stdcall))
     * }
     */
    public final static class QueryInterface {

        private QueryInterface() {
            // Should not be called directly
        }

        /**
         * The function pointer signature, expressed as a functional interface
         */
        public interface Function {
            int apply(MemorySegment _x0, MemorySegment _x1, MemorySegment _x2);
        }

        private static final FunctionDescriptor $DESC = FunctionDescriptor.of(
            cef_render_handler_capi_h.C_LONG,
            cef_render_handler_capi_h.C_POINTER,
            cef_render_handler_capi_h.C_POINTER,
            cef_render_handler_capi_h.C_POINTER
        );

        /**
         * The descriptor of this function pointer
         */
        public static FunctionDescriptor descriptor() {
            return $DESC;
        }

        private static final MethodHandle UP$MH = cef_render_handler_capi_h.upcallHandle(QueryInterface.Function.class, "apply", $DESC);

        /**
         * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
         * The lifetime of the returned segment is managed by {@code arena}
         */
        public static MemorySegment allocate(QueryInterface.Function fi, Arena arena) {
            return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
        }

        private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

        /**
         * Invoke the upcall stub {@code funcPtr}, with given parameters
         */
        public static int invoke(MemorySegment funcPtr, MemorySegment _x0, MemorySegment _x1, MemorySegment _x2) {
            try {
                return (int) DOWN$MH.invokeExact(funcPtr, _x0, _x1, _x2);
            } catch (Error | RuntimeException ex) {
                throw ex;
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        }
    }

    private static final AddressLayout QueryInterface$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("QueryInterface"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * HRESULT (*QueryInterface)(ICreateTypeInfo *, const IID *const, void **) __attribute__((stdcall))
     * }
     */
    public static final AddressLayout QueryInterface$layout() {
        return QueryInterface$LAYOUT;
    }

    private static final long QueryInterface$OFFSET = $LAYOUT.byteOffset(groupElement("QueryInterface"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * HRESULT (*QueryInterface)(ICreateTypeInfo *, const IID *const, void **) __attribute__((stdcall))
     * }
     */
    public static final long QueryInterface$offset() {
        return QueryInterface$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * HRESULT (*QueryInterface)(ICreateTypeInfo *, const IID *const, void **) __attribute__((stdcall))
     * }
     */
    public static MemorySegment QueryInterface(MemorySegment struct) {
        return struct.get(QueryInterface$LAYOUT, QueryInterface$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * HRESULT (*QueryInterface)(ICreateTypeInfo *, const IID *const, void **) __attribute__((stdcall))
     * }
     */
    public static void QueryInterface(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(QueryInterface$LAYOUT, QueryInterface$OFFSET, fieldValue);
    }

    /**
     * {@snippet lang=c :
     * ULONG (*AddRef)(ICreateTypeInfo *) __attribute__((stdcall))
     * }
     */
    public final static class AddRef {

        private AddRef() {
            // Should not be called directly
        }

        /**
         * The function pointer signature, expressed as a functional interface
         */
        public interface Function {
            int apply(MemorySegment _x0);
        }

        private static final FunctionDescriptor $DESC = FunctionDescriptor.of(
            cef_render_handler_capi_h.C_LONG,
            cef_render_handler_capi_h.C_POINTER
        );

        /**
         * The descriptor of this function pointer
         */
        public static FunctionDescriptor descriptor() {
            return $DESC;
        }

        private static final MethodHandle UP$MH = cef_render_handler_capi_h.upcallHandle(AddRef.Function.class, "apply", $DESC);

        /**
         * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
         * The lifetime of the returned segment is managed by {@code arena}
         */
        public static MemorySegment allocate(AddRef.Function fi, Arena arena) {
            return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
        }

        private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

        /**
         * Invoke the upcall stub {@code funcPtr}, with given parameters
         */
        public static int invoke(MemorySegment funcPtr, MemorySegment _x0) {
            try {
                return (int) DOWN$MH.invokeExact(funcPtr, _x0);
            } catch (Error | RuntimeException ex) {
                throw ex;
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        }
    }

    private static final AddressLayout AddRef$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("AddRef"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * ULONG (*AddRef)(ICreateTypeInfo *) __attribute__((stdcall))
     * }
     */
    public static final AddressLayout AddRef$layout() {
        return AddRef$LAYOUT;
    }

    private static final long AddRef$OFFSET = $LAYOUT.byteOffset(groupElement("AddRef"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * ULONG (*AddRef)(ICreateTypeInfo *) __attribute__((stdcall))
     * }
     */
    public static final long AddRef$offset() {
        return AddRef$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * ULONG (*AddRef)(ICreateTypeInfo *) __attribute__((stdcall))
     * }
     */
    public static MemorySegment AddRef(MemorySegment struct) {
        return struct.get(AddRef$LAYOUT, AddRef$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * ULONG (*AddRef)(ICreateTypeInfo *) __attribute__((stdcall))
     * }
     */
    public static void AddRef(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(AddRef$LAYOUT, AddRef$OFFSET, fieldValue);
    }

    /**
     * {@snippet lang=c :
     * ULONG (*Release)(ICreateTypeInfo *) __attribute__((stdcall))
     * }
     */
    public final static class Release {

        private Release() {
            // Should not be called directly
        }

        /**
         * The function pointer signature, expressed as a functional interface
         */
        public interface Function {
            int apply(MemorySegment _x0);
        }

        private static final FunctionDescriptor $DESC = FunctionDescriptor.of(
            cef_render_handler_capi_h.C_LONG,
            cef_render_handler_capi_h.C_POINTER
        );

        /**
         * The descriptor of this function pointer
         */
        public static FunctionDescriptor descriptor() {
            return $DESC;
        }

        private static final MethodHandle UP$MH = cef_render_handler_capi_h.upcallHandle(Release.Function.class, "apply", $DESC);

        /**
         * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
         * The lifetime of the returned segment is managed by {@code arena}
         */
        public static MemorySegment allocate(Release.Function fi, Arena arena) {
            return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
        }

        private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

        /**
         * Invoke the upcall stub {@code funcPtr}, with given parameters
         */
        public static int invoke(MemorySegment funcPtr, MemorySegment _x0) {
            try {
                return (int) DOWN$MH.invokeExact(funcPtr, _x0);
            } catch (Error | RuntimeException ex) {
                throw ex;
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        }
    }

    private static final AddressLayout Release$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("Release"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * ULONG (*Release)(ICreateTypeInfo *) __attribute__((stdcall))
     * }
     */
    public static final AddressLayout Release$layout() {
        return Release$LAYOUT;
    }

    private static final long Release$OFFSET = $LAYOUT.byteOffset(groupElement("Release"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * ULONG (*Release)(ICreateTypeInfo *) __attribute__((stdcall))
     * }
     */
    public static final long Release$offset() {
        return Release$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * ULONG (*Release)(ICreateTypeInfo *) __attribute__((stdcall))
     * }
     */
    public static MemorySegment Release(MemorySegment struct) {
        return struct.get(Release$LAYOUT, Release$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * ULONG (*Release)(ICreateTypeInfo *) __attribute__((stdcall))
     * }
     */
    public static void Release(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(Release$LAYOUT, Release$OFFSET, fieldValue);
    }

    /**
     * {@snippet lang=c :
     * HRESULT (*SetGuid)(ICreateTypeInfo *, const GUID *const) __attribute__((stdcall))
     * }
     */
    public final static class SetGuid {

        private SetGuid() {
            // Should not be called directly
        }

        /**
         * The function pointer signature, expressed as a functional interface
         */
        public interface Function {
            int apply(MemorySegment _x0, MemorySegment _x1);
        }

        private static final FunctionDescriptor $DESC = FunctionDescriptor.of(
            cef_render_handler_capi_h.C_LONG,
            cef_render_handler_capi_h.C_POINTER,
            cef_render_handler_capi_h.C_POINTER
        );

        /**
         * The descriptor of this function pointer
         */
        public static FunctionDescriptor descriptor() {
            return $DESC;
        }

        private static final MethodHandle UP$MH = cef_render_handler_capi_h.upcallHandle(SetGuid.Function.class, "apply", $DESC);

        /**
         * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
         * The lifetime of the returned segment is managed by {@code arena}
         */
        public static MemorySegment allocate(SetGuid.Function fi, Arena arena) {
            return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
        }

        private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

        /**
         * Invoke the upcall stub {@code funcPtr}, with given parameters
         */
        public static int invoke(MemorySegment funcPtr, MemorySegment _x0, MemorySegment _x1) {
            try {
                return (int) DOWN$MH.invokeExact(funcPtr, _x0, _x1);
            } catch (Error | RuntimeException ex) {
                throw ex;
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        }
    }

    private static final AddressLayout SetGuid$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("SetGuid"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * HRESULT (*SetGuid)(ICreateTypeInfo *, const GUID *const) __attribute__((stdcall))
     * }
     */
    public static final AddressLayout SetGuid$layout() {
        return SetGuid$LAYOUT;
    }

    private static final long SetGuid$OFFSET = $LAYOUT.byteOffset(groupElement("SetGuid"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * HRESULT (*SetGuid)(ICreateTypeInfo *, const GUID *const) __attribute__((stdcall))
     * }
     */
    public static final long SetGuid$offset() {
        return SetGuid$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * HRESULT (*SetGuid)(ICreateTypeInfo *, const GUID *const) __attribute__((stdcall))
     * }
     */
    public static MemorySegment SetGuid(MemorySegment struct) {
        return struct.get(SetGuid$LAYOUT, SetGuid$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * HRESULT (*SetGuid)(ICreateTypeInfo *, const GUID *const) __attribute__((stdcall))
     * }
     */
    public static void SetGuid(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(SetGuid$LAYOUT, SetGuid$OFFSET, fieldValue);
    }

    /**
     * {@snippet lang=c :
     * HRESULT (*SetTypeFlags)(ICreateTypeInfo *, UINT) __attribute__((stdcall))
     * }
     */
    public final static class SetTypeFlags {

        private SetTypeFlags() {
            // Should not be called directly
        }

        /**
         * The function pointer signature, expressed as a functional interface
         */
        public interface Function {
            int apply(MemorySegment _x0, int _x1);
        }

        private static final FunctionDescriptor $DESC = FunctionDescriptor.of(
            cef_render_handler_capi_h.C_LONG,
            cef_render_handler_capi_h.C_POINTER,
            cef_render_handler_capi_h.C_INT
        );

        /**
         * The descriptor of this function pointer
         */
        public static FunctionDescriptor descriptor() {
            return $DESC;
        }

        private static final MethodHandle UP$MH = cef_render_handler_capi_h.upcallHandle(SetTypeFlags.Function.class, "apply", $DESC);

        /**
         * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
         * The lifetime of the returned segment is managed by {@code arena}
         */
        public static MemorySegment allocate(SetTypeFlags.Function fi, Arena arena) {
            return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
        }

        private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

        /**
         * Invoke the upcall stub {@code funcPtr}, with given parameters
         */
        public static int invoke(MemorySegment funcPtr, MemorySegment _x0, int _x1) {
            try {
                return (int) DOWN$MH.invokeExact(funcPtr, _x0, _x1);
            } catch (Error | RuntimeException ex) {
                throw ex;
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        }
    }

    private static final AddressLayout SetTypeFlags$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("SetTypeFlags"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * HRESULT (*SetTypeFlags)(ICreateTypeInfo *, UINT) __attribute__((stdcall))
     * }
     */
    public static final AddressLayout SetTypeFlags$layout() {
        return SetTypeFlags$LAYOUT;
    }

    private static final long SetTypeFlags$OFFSET = $LAYOUT.byteOffset(groupElement("SetTypeFlags"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * HRESULT (*SetTypeFlags)(ICreateTypeInfo *, UINT) __attribute__((stdcall))
     * }
     */
    public static final long SetTypeFlags$offset() {
        return SetTypeFlags$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * HRESULT (*SetTypeFlags)(ICreateTypeInfo *, UINT) __attribute__((stdcall))
     * }
     */
    public static MemorySegment SetTypeFlags(MemorySegment struct) {
        return struct.get(SetTypeFlags$LAYOUT, SetTypeFlags$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * HRESULT (*SetTypeFlags)(ICreateTypeInfo *, UINT) __attribute__((stdcall))
     * }
     */
    public static void SetTypeFlags(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(SetTypeFlags$LAYOUT, SetTypeFlags$OFFSET, fieldValue);
    }

    /**
     * {@snippet lang=c :
     * HRESULT (*SetDocString)(ICreateTypeInfo *, LPOLESTR) __attribute__((stdcall))
     * }
     */
    public final static class SetDocString {

        private SetDocString() {
            // Should not be called directly
        }

        /**
         * The function pointer signature, expressed as a functional interface
         */
        public interface Function {
            int apply(MemorySegment _x0, MemorySegment _x1);
        }

        private static final FunctionDescriptor $DESC = FunctionDescriptor.of(
            cef_render_handler_capi_h.C_LONG,
            cef_render_handler_capi_h.C_POINTER,
            cef_render_handler_capi_h.C_POINTER
        );

        /**
         * The descriptor of this function pointer
         */
        public static FunctionDescriptor descriptor() {
            return $DESC;
        }

        private static final MethodHandle UP$MH = cef_render_handler_capi_h.upcallHandle(SetDocString.Function.class, "apply", $DESC);

        /**
         * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
         * The lifetime of the returned segment is managed by {@code arena}
         */
        public static MemorySegment allocate(SetDocString.Function fi, Arena arena) {
            return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
        }

        private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

        /**
         * Invoke the upcall stub {@code funcPtr}, with given parameters
         */
        public static int invoke(MemorySegment funcPtr, MemorySegment _x0, MemorySegment _x1) {
            try {
                return (int) DOWN$MH.invokeExact(funcPtr, _x0, _x1);
            } catch (Error | RuntimeException ex) {
                throw ex;
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        }
    }

    private static final AddressLayout SetDocString$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("SetDocString"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * HRESULT (*SetDocString)(ICreateTypeInfo *, LPOLESTR) __attribute__((stdcall))
     * }
     */
    public static final AddressLayout SetDocString$layout() {
        return SetDocString$LAYOUT;
    }

    private static final long SetDocString$OFFSET = $LAYOUT.byteOffset(groupElement("SetDocString"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * HRESULT (*SetDocString)(ICreateTypeInfo *, LPOLESTR) __attribute__((stdcall))
     * }
     */
    public static final long SetDocString$offset() {
        return SetDocString$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * HRESULT (*SetDocString)(ICreateTypeInfo *, LPOLESTR) __attribute__((stdcall))
     * }
     */
    public static MemorySegment SetDocString(MemorySegment struct) {
        return struct.get(SetDocString$LAYOUT, SetDocString$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * HRESULT (*SetDocString)(ICreateTypeInfo *, LPOLESTR) __attribute__((stdcall))
     * }
     */
    public static void SetDocString(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(SetDocString$LAYOUT, SetDocString$OFFSET, fieldValue);
    }

    /**
     * {@snippet lang=c :
     * HRESULT (*SetHelpContext)(ICreateTypeInfo *, DWORD) __attribute__((stdcall))
     * }
     */
    public final static class SetHelpContext {

        private SetHelpContext() {
            // Should not be called directly
        }

        /**
         * The function pointer signature, expressed as a functional interface
         */
        public interface Function {
            int apply(MemorySegment _x0, int _x1);
        }

        private static final FunctionDescriptor $DESC = FunctionDescriptor.of(
            cef_render_handler_capi_h.C_LONG,
            cef_render_handler_capi_h.C_POINTER,
            cef_render_handler_capi_h.C_LONG
        );

        /**
         * The descriptor of this function pointer
         */
        public static FunctionDescriptor descriptor() {
            return $DESC;
        }

        private static final MethodHandle UP$MH = cef_render_handler_capi_h.upcallHandle(SetHelpContext.Function.class, "apply", $DESC);

        /**
         * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
         * The lifetime of the returned segment is managed by {@code arena}
         */
        public static MemorySegment allocate(SetHelpContext.Function fi, Arena arena) {
            return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
        }

        private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

        /**
         * Invoke the upcall stub {@code funcPtr}, with given parameters
         */
        public static int invoke(MemorySegment funcPtr, MemorySegment _x0, int _x1) {
            try {
                return (int) DOWN$MH.invokeExact(funcPtr, _x0, _x1);
            } catch (Error | RuntimeException ex) {
                throw ex;
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        }
    }

    private static final AddressLayout SetHelpContext$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("SetHelpContext"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * HRESULT (*SetHelpContext)(ICreateTypeInfo *, DWORD) __attribute__((stdcall))
     * }
     */
    public static final AddressLayout SetHelpContext$layout() {
        return SetHelpContext$LAYOUT;
    }

    private static final long SetHelpContext$OFFSET = $LAYOUT.byteOffset(groupElement("SetHelpContext"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * HRESULT (*SetHelpContext)(ICreateTypeInfo *, DWORD) __attribute__((stdcall))
     * }
     */
    public static final long SetHelpContext$offset() {
        return SetHelpContext$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * HRESULT (*SetHelpContext)(ICreateTypeInfo *, DWORD) __attribute__((stdcall))
     * }
     */
    public static MemorySegment SetHelpContext(MemorySegment struct) {
        return struct.get(SetHelpContext$LAYOUT, SetHelpContext$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * HRESULT (*SetHelpContext)(ICreateTypeInfo *, DWORD) __attribute__((stdcall))
     * }
     */
    public static void SetHelpContext(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(SetHelpContext$LAYOUT, SetHelpContext$OFFSET, fieldValue);
    }

    /**
     * {@snippet lang=c :
     * HRESULT (*SetVersion)(ICreateTypeInfo *, WORD, WORD) __attribute__((stdcall))
     * }
     */
    public final static class SetVersion {

        private SetVersion() {
            // Should not be called directly
        }

        /**
         * The function pointer signature, expressed as a functional interface
         */
        public interface Function {
            int apply(MemorySegment _x0, short _x1, short _x2);
        }

        private static final FunctionDescriptor $DESC = FunctionDescriptor.of(
            cef_render_handler_capi_h.C_LONG,
            cef_render_handler_capi_h.C_POINTER,
            cef_render_handler_capi_h.C_SHORT,
            cef_render_handler_capi_h.C_SHORT
        );

        /**
         * The descriptor of this function pointer
         */
        public static FunctionDescriptor descriptor() {
            return $DESC;
        }

        private static final MethodHandle UP$MH = cef_render_handler_capi_h.upcallHandle(SetVersion.Function.class, "apply", $DESC);

        /**
         * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
         * The lifetime of the returned segment is managed by {@code arena}
         */
        public static MemorySegment allocate(SetVersion.Function fi, Arena arena) {
            return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
        }

        private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

        /**
         * Invoke the upcall stub {@code funcPtr}, with given parameters
         */
        public static int invoke(MemorySegment funcPtr, MemorySegment _x0, short _x1, short _x2) {
            try {
                return (int) DOWN$MH.invokeExact(funcPtr, _x0, _x1, _x2);
            } catch (Error | RuntimeException ex) {
                throw ex;
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        }
    }

    private static final AddressLayout SetVersion$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("SetVersion"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * HRESULT (*SetVersion)(ICreateTypeInfo *, WORD, WORD) __attribute__((stdcall))
     * }
     */
    public static final AddressLayout SetVersion$layout() {
        return SetVersion$LAYOUT;
    }

    private static final long SetVersion$OFFSET = $LAYOUT.byteOffset(groupElement("SetVersion"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * HRESULT (*SetVersion)(ICreateTypeInfo *, WORD, WORD) __attribute__((stdcall))
     * }
     */
    public static final long SetVersion$offset() {
        return SetVersion$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * HRESULT (*SetVersion)(ICreateTypeInfo *, WORD, WORD) __attribute__((stdcall))
     * }
     */
    public static MemorySegment SetVersion(MemorySegment struct) {
        return struct.get(SetVersion$LAYOUT, SetVersion$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * HRESULT (*SetVersion)(ICreateTypeInfo *, WORD, WORD) __attribute__((stdcall))
     * }
     */
    public static void SetVersion(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(SetVersion$LAYOUT, SetVersion$OFFSET, fieldValue);
    }

    /**
     * {@snippet lang=c :
     * HRESULT (*AddRefTypeInfo)(ICreateTypeInfo *, ITypeInfo *, HREFTYPE *) __attribute__((stdcall))
     * }
     */
    public final static class AddRefTypeInfo {

        private AddRefTypeInfo() {
            // Should not be called directly
        }

        /**
         * The function pointer signature, expressed as a functional interface
         */
        public interface Function {
            int apply(MemorySegment _x0, MemorySegment _x1, MemorySegment _x2);
        }

        private static final FunctionDescriptor $DESC = FunctionDescriptor.of(
            cef_render_handler_capi_h.C_LONG,
            cef_render_handler_capi_h.C_POINTER,
            cef_render_handler_capi_h.C_POINTER,
            cef_render_handler_capi_h.C_POINTER
        );

        /**
         * The descriptor of this function pointer
         */
        public static FunctionDescriptor descriptor() {
            return $DESC;
        }

        private static final MethodHandle UP$MH = cef_render_handler_capi_h.upcallHandle(AddRefTypeInfo.Function.class, "apply", $DESC);

        /**
         * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
         * The lifetime of the returned segment is managed by {@code arena}
         */
        public static MemorySegment allocate(AddRefTypeInfo.Function fi, Arena arena) {
            return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
        }

        private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

        /**
         * Invoke the upcall stub {@code funcPtr}, with given parameters
         */
        public static int invoke(MemorySegment funcPtr, MemorySegment _x0, MemorySegment _x1, MemorySegment _x2) {
            try {
                return (int) DOWN$MH.invokeExact(funcPtr, _x0, _x1, _x2);
            } catch (Error | RuntimeException ex) {
                throw ex;
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        }
    }

    private static final AddressLayout AddRefTypeInfo$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("AddRefTypeInfo"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * HRESULT (*AddRefTypeInfo)(ICreateTypeInfo *, ITypeInfo *, HREFTYPE *) __attribute__((stdcall))
     * }
     */
    public static final AddressLayout AddRefTypeInfo$layout() {
        return AddRefTypeInfo$LAYOUT;
    }

    private static final long AddRefTypeInfo$OFFSET = $LAYOUT.byteOffset(groupElement("AddRefTypeInfo"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * HRESULT (*AddRefTypeInfo)(ICreateTypeInfo *, ITypeInfo *, HREFTYPE *) __attribute__((stdcall))
     * }
     */
    public static final long AddRefTypeInfo$offset() {
        return AddRefTypeInfo$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * HRESULT (*AddRefTypeInfo)(ICreateTypeInfo *, ITypeInfo *, HREFTYPE *) __attribute__((stdcall))
     * }
     */
    public static MemorySegment AddRefTypeInfo(MemorySegment struct) {
        return struct.get(AddRefTypeInfo$LAYOUT, AddRefTypeInfo$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * HRESULT (*AddRefTypeInfo)(ICreateTypeInfo *, ITypeInfo *, HREFTYPE *) __attribute__((stdcall))
     * }
     */
    public static void AddRefTypeInfo(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(AddRefTypeInfo$LAYOUT, AddRefTypeInfo$OFFSET, fieldValue);
    }

    /**
     * {@snippet lang=c :
     * HRESULT (*AddFuncDesc)(ICreateTypeInfo *, UINT, FUNCDESC *) __attribute__((stdcall))
     * }
     */
    public final static class AddFuncDesc {

        private AddFuncDesc() {
            // Should not be called directly
        }

        /**
         * The function pointer signature, expressed as a functional interface
         */
        public interface Function {
            int apply(MemorySegment _x0, int _x1, MemorySegment _x2);
        }

        private static final FunctionDescriptor $DESC = FunctionDescriptor.of(
            cef_render_handler_capi_h.C_LONG,
            cef_render_handler_capi_h.C_POINTER,
            cef_render_handler_capi_h.C_INT,
            cef_render_handler_capi_h.C_POINTER
        );

        /**
         * The descriptor of this function pointer
         */
        public static FunctionDescriptor descriptor() {
            return $DESC;
        }

        private static final MethodHandle UP$MH = cef_render_handler_capi_h.upcallHandle(AddFuncDesc.Function.class, "apply", $DESC);

        /**
         * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
         * The lifetime of the returned segment is managed by {@code arena}
         */
        public static MemorySegment allocate(AddFuncDesc.Function fi, Arena arena) {
            return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
        }

        private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

        /**
         * Invoke the upcall stub {@code funcPtr}, with given parameters
         */
        public static int invoke(MemorySegment funcPtr, MemorySegment _x0, int _x1, MemorySegment _x2) {
            try {
                return (int) DOWN$MH.invokeExact(funcPtr, _x0, _x1, _x2);
            } catch (Error | RuntimeException ex) {
                throw ex;
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        }
    }

    private static final AddressLayout AddFuncDesc$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("AddFuncDesc"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * HRESULT (*AddFuncDesc)(ICreateTypeInfo *, UINT, FUNCDESC *) __attribute__((stdcall))
     * }
     */
    public static final AddressLayout AddFuncDesc$layout() {
        return AddFuncDesc$LAYOUT;
    }

    private static final long AddFuncDesc$OFFSET = $LAYOUT.byteOffset(groupElement("AddFuncDesc"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * HRESULT (*AddFuncDesc)(ICreateTypeInfo *, UINT, FUNCDESC *) __attribute__((stdcall))
     * }
     */
    public static final long AddFuncDesc$offset() {
        return AddFuncDesc$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * HRESULT (*AddFuncDesc)(ICreateTypeInfo *, UINT, FUNCDESC *) __attribute__((stdcall))
     * }
     */
    public static MemorySegment AddFuncDesc(MemorySegment struct) {
        return struct.get(AddFuncDesc$LAYOUT, AddFuncDesc$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * HRESULT (*AddFuncDesc)(ICreateTypeInfo *, UINT, FUNCDESC *) __attribute__((stdcall))
     * }
     */
    public static void AddFuncDesc(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(AddFuncDesc$LAYOUT, AddFuncDesc$OFFSET, fieldValue);
    }

    /**
     * {@snippet lang=c :
     * HRESULT (*AddImplType)(ICreateTypeInfo *, UINT, HREFTYPE) __attribute__((stdcall))
     * }
     */
    public final static class AddImplType {

        private AddImplType() {
            // Should not be called directly
        }

        /**
         * The function pointer signature, expressed as a functional interface
         */
        public interface Function {
            int apply(MemorySegment _x0, int _x1, int _x2);
        }

        private static final FunctionDescriptor $DESC = FunctionDescriptor.of(
            cef_render_handler_capi_h.C_LONG,
            cef_render_handler_capi_h.C_POINTER,
            cef_render_handler_capi_h.C_INT,
            cef_render_handler_capi_h.C_LONG
        );

        /**
         * The descriptor of this function pointer
         */
        public static FunctionDescriptor descriptor() {
            return $DESC;
        }

        private static final MethodHandle UP$MH = cef_render_handler_capi_h.upcallHandle(AddImplType.Function.class, "apply", $DESC);

        /**
         * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
         * The lifetime of the returned segment is managed by {@code arena}
         */
        public static MemorySegment allocate(AddImplType.Function fi, Arena arena) {
            return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
        }

        private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

        /**
         * Invoke the upcall stub {@code funcPtr}, with given parameters
         */
        public static int invoke(MemorySegment funcPtr, MemorySegment _x0, int _x1, int _x2) {
            try {
                return (int) DOWN$MH.invokeExact(funcPtr, _x0, _x1, _x2);
            } catch (Error | RuntimeException ex) {
                throw ex;
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        }
    }

    private static final AddressLayout AddImplType$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("AddImplType"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * HRESULT (*AddImplType)(ICreateTypeInfo *, UINT, HREFTYPE) __attribute__((stdcall))
     * }
     */
    public static final AddressLayout AddImplType$layout() {
        return AddImplType$LAYOUT;
    }

    private static final long AddImplType$OFFSET = $LAYOUT.byteOffset(groupElement("AddImplType"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * HRESULT (*AddImplType)(ICreateTypeInfo *, UINT, HREFTYPE) __attribute__((stdcall))
     * }
     */
    public static final long AddImplType$offset() {
        return AddImplType$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * HRESULT (*AddImplType)(ICreateTypeInfo *, UINT, HREFTYPE) __attribute__((stdcall))
     * }
     */
    public static MemorySegment AddImplType(MemorySegment struct) {
        return struct.get(AddImplType$LAYOUT, AddImplType$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * HRESULT (*AddImplType)(ICreateTypeInfo *, UINT, HREFTYPE) __attribute__((stdcall))
     * }
     */
    public static void AddImplType(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(AddImplType$LAYOUT, AddImplType$OFFSET, fieldValue);
    }

    /**
     * {@snippet lang=c :
     * HRESULT (*SetImplTypeFlags)(ICreateTypeInfo *, UINT, INT) __attribute__((stdcall))
     * }
     */
    public final static class SetImplTypeFlags {

        private SetImplTypeFlags() {
            // Should not be called directly
        }

        /**
         * The function pointer signature, expressed as a functional interface
         */
        public interface Function {
            int apply(MemorySegment _x0, int _x1, int _x2);
        }

        private static final FunctionDescriptor $DESC = FunctionDescriptor.of(
            cef_render_handler_capi_h.C_LONG,
            cef_render_handler_capi_h.C_POINTER,
            cef_render_handler_capi_h.C_INT,
            cef_render_handler_capi_h.C_INT
        );

        /**
         * The descriptor of this function pointer
         */
        public static FunctionDescriptor descriptor() {
            return $DESC;
        }

        private static final MethodHandle UP$MH = cef_render_handler_capi_h.upcallHandle(SetImplTypeFlags.Function.class, "apply", $DESC);

        /**
         * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
         * The lifetime of the returned segment is managed by {@code arena}
         */
        public static MemorySegment allocate(SetImplTypeFlags.Function fi, Arena arena) {
            return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
        }

        private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

        /**
         * Invoke the upcall stub {@code funcPtr}, with given parameters
         */
        public static int invoke(MemorySegment funcPtr, MemorySegment _x0, int _x1, int _x2) {
            try {
                return (int) DOWN$MH.invokeExact(funcPtr, _x0, _x1, _x2);
            } catch (Error | RuntimeException ex) {
                throw ex;
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        }
    }

    private static final AddressLayout SetImplTypeFlags$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("SetImplTypeFlags"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * HRESULT (*SetImplTypeFlags)(ICreateTypeInfo *, UINT, INT) __attribute__((stdcall))
     * }
     */
    public static final AddressLayout SetImplTypeFlags$layout() {
        return SetImplTypeFlags$LAYOUT;
    }

    private static final long SetImplTypeFlags$OFFSET = $LAYOUT.byteOffset(groupElement("SetImplTypeFlags"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * HRESULT (*SetImplTypeFlags)(ICreateTypeInfo *, UINT, INT) __attribute__((stdcall))
     * }
     */
    public static final long SetImplTypeFlags$offset() {
        return SetImplTypeFlags$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * HRESULT (*SetImplTypeFlags)(ICreateTypeInfo *, UINT, INT) __attribute__((stdcall))
     * }
     */
    public static MemorySegment SetImplTypeFlags(MemorySegment struct) {
        return struct.get(SetImplTypeFlags$LAYOUT, SetImplTypeFlags$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * HRESULT (*SetImplTypeFlags)(ICreateTypeInfo *, UINT, INT) __attribute__((stdcall))
     * }
     */
    public static void SetImplTypeFlags(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(SetImplTypeFlags$LAYOUT, SetImplTypeFlags$OFFSET, fieldValue);
    }

    /**
     * {@snippet lang=c :
     * HRESULT (*SetAlignment)(ICreateTypeInfo *, WORD) __attribute__((stdcall))
     * }
     */
    public final static class SetAlignment {

        private SetAlignment() {
            // Should not be called directly
        }

        /**
         * The function pointer signature, expressed as a functional interface
         */
        public interface Function {
            int apply(MemorySegment _x0, short _x1);
        }

        private static final FunctionDescriptor $DESC = FunctionDescriptor.of(
            cef_render_handler_capi_h.C_LONG,
            cef_render_handler_capi_h.C_POINTER,
            cef_render_handler_capi_h.C_SHORT
        );

        /**
         * The descriptor of this function pointer
         */
        public static FunctionDescriptor descriptor() {
            return $DESC;
        }

        private static final MethodHandle UP$MH = cef_render_handler_capi_h.upcallHandle(SetAlignment.Function.class, "apply", $DESC);

        /**
         * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
         * The lifetime of the returned segment is managed by {@code arena}
         */
        public static MemorySegment allocate(SetAlignment.Function fi, Arena arena) {
            return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
        }

        private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

        /**
         * Invoke the upcall stub {@code funcPtr}, with given parameters
         */
        public static int invoke(MemorySegment funcPtr, MemorySegment _x0, short _x1) {
            try {
                return (int) DOWN$MH.invokeExact(funcPtr, _x0, _x1);
            } catch (Error | RuntimeException ex) {
                throw ex;
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        }
    }

    private static final AddressLayout SetAlignment$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("SetAlignment"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * HRESULT (*SetAlignment)(ICreateTypeInfo *, WORD) __attribute__((stdcall))
     * }
     */
    public static final AddressLayout SetAlignment$layout() {
        return SetAlignment$LAYOUT;
    }

    private static final long SetAlignment$OFFSET = $LAYOUT.byteOffset(groupElement("SetAlignment"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * HRESULT (*SetAlignment)(ICreateTypeInfo *, WORD) __attribute__((stdcall))
     * }
     */
    public static final long SetAlignment$offset() {
        return SetAlignment$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * HRESULT (*SetAlignment)(ICreateTypeInfo *, WORD) __attribute__((stdcall))
     * }
     */
    public static MemorySegment SetAlignment(MemorySegment struct) {
        return struct.get(SetAlignment$LAYOUT, SetAlignment$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * HRESULT (*SetAlignment)(ICreateTypeInfo *, WORD) __attribute__((stdcall))
     * }
     */
    public static void SetAlignment(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(SetAlignment$LAYOUT, SetAlignment$OFFSET, fieldValue);
    }

    /**
     * {@snippet lang=c :
     * HRESULT (*SetSchema)(ICreateTypeInfo *, LPOLESTR) __attribute__((stdcall))
     * }
     */
    public final static class SetSchema {

        private SetSchema() {
            // Should not be called directly
        }

        /**
         * The function pointer signature, expressed as a functional interface
         */
        public interface Function {
            int apply(MemorySegment _x0, MemorySegment _x1);
        }

        private static final FunctionDescriptor $DESC = FunctionDescriptor.of(
            cef_render_handler_capi_h.C_LONG,
            cef_render_handler_capi_h.C_POINTER,
            cef_render_handler_capi_h.C_POINTER
        );

        /**
         * The descriptor of this function pointer
         */
        public static FunctionDescriptor descriptor() {
            return $DESC;
        }

        private static final MethodHandle UP$MH = cef_render_handler_capi_h.upcallHandle(SetSchema.Function.class, "apply", $DESC);

        /**
         * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
         * The lifetime of the returned segment is managed by {@code arena}
         */
        public static MemorySegment allocate(SetSchema.Function fi, Arena arena) {
            return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
        }

        private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

        /**
         * Invoke the upcall stub {@code funcPtr}, with given parameters
         */
        public static int invoke(MemorySegment funcPtr, MemorySegment _x0, MemorySegment _x1) {
            try {
                return (int) DOWN$MH.invokeExact(funcPtr, _x0, _x1);
            } catch (Error | RuntimeException ex) {
                throw ex;
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        }
    }

    private static final AddressLayout SetSchema$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("SetSchema"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * HRESULT (*SetSchema)(ICreateTypeInfo *, LPOLESTR) __attribute__((stdcall))
     * }
     */
    public static final AddressLayout SetSchema$layout() {
        return SetSchema$LAYOUT;
    }

    private static final long SetSchema$OFFSET = $LAYOUT.byteOffset(groupElement("SetSchema"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * HRESULT (*SetSchema)(ICreateTypeInfo *, LPOLESTR) __attribute__((stdcall))
     * }
     */
    public static final long SetSchema$offset() {
        return SetSchema$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * HRESULT (*SetSchema)(ICreateTypeInfo *, LPOLESTR) __attribute__((stdcall))
     * }
     */
    public static MemorySegment SetSchema(MemorySegment struct) {
        return struct.get(SetSchema$LAYOUT, SetSchema$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * HRESULT (*SetSchema)(ICreateTypeInfo *, LPOLESTR) __attribute__((stdcall))
     * }
     */
    public static void SetSchema(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(SetSchema$LAYOUT, SetSchema$OFFSET, fieldValue);
    }

    /**
     * {@snippet lang=c :
     * HRESULT (*AddVarDesc)(ICreateTypeInfo *, UINT, VARDESC *) __attribute__((stdcall))
     * }
     */
    public final static class AddVarDesc {

        private AddVarDesc() {
            // Should not be called directly
        }

        /**
         * The function pointer signature, expressed as a functional interface
         */
        public interface Function {
            int apply(MemorySegment _x0, int _x1, MemorySegment _x2);
        }

        private static final FunctionDescriptor $DESC = FunctionDescriptor.of(
            cef_render_handler_capi_h.C_LONG,
            cef_render_handler_capi_h.C_POINTER,
            cef_render_handler_capi_h.C_INT,
            cef_render_handler_capi_h.C_POINTER
        );

        /**
         * The descriptor of this function pointer
         */
        public static FunctionDescriptor descriptor() {
            return $DESC;
        }

        private static final MethodHandle UP$MH = cef_render_handler_capi_h.upcallHandle(AddVarDesc.Function.class, "apply", $DESC);

        /**
         * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
         * The lifetime of the returned segment is managed by {@code arena}
         */
        public static MemorySegment allocate(AddVarDesc.Function fi, Arena arena) {
            return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
        }

        private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

        /**
         * Invoke the upcall stub {@code funcPtr}, with given parameters
         */
        public static int invoke(MemorySegment funcPtr, MemorySegment _x0, int _x1, MemorySegment _x2) {
            try {
                return (int) DOWN$MH.invokeExact(funcPtr, _x0, _x1, _x2);
            } catch (Error | RuntimeException ex) {
                throw ex;
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        }
    }

    private static final AddressLayout AddVarDesc$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("AddVarDesc"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * HRESULT (*AddVarDesc)(ICreateTypeInfo *, UINT, VARDESC *) __attribute__((stdcall))
     * }
     */
    public static final AddressLayout AddVarDesc$layout() {
        return AddVarDesc$LAYOUT;
    }

    private static final long AddVarDesc$OFFSET = $LAYOUT.byteOffset(groupElement("AddVarDesc"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * HRESULT (*AddVarDesc)(ICreateTypeInfo *, UINT, VARDESC *) __attribute__((stdcall))
     * }
     */
    public static final long AddVarDesc$offset() {
        return AddVarDesc$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * HRESULT (*AddVarDesc)(ICreateTypeInfo *, UINT, VARDESC *) __attribute__((stdcall))
     * }
     */
    public static MemorySegment AddVarDesc(MemorySegment struct) {
        return struct.get(AddVarDesc$LAYOUT, AddVarDesc$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * HRESULT (*AddVarDesc)(ICreateTypeInfo *, UINT, VARDESC *) __attribute__((stdcall))
     * }
     */
    public static void AddVarDesc(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(AddVarDesc$LAYOUT, AddVarDesc$OFFSET, fieldValue);
    }

    /**
     * {@snippet lang=c :
     * HRESULT (*SetFuncAndParamNames)(ICreateTypeInfo *, UINT, LPOLESTR *, UINT) __attribute__((stdcall))
     * }
     */
    public final static class SetFuncAndParamNames {

        private SetFuncAndParamNames() {
            // Should not be called directly
        }

        /**
         * The function pointer signature, expressed as a functional interface
         */
        public interface Function {
            int apply(MemorySegment _x0, int _x1, MemorySegment _x2, int _x3);
        }

        private static final FunctionDescriptor $DESC = FunctionDescriptor.of(
            cef_render_handler_capi_h.C_LONG,
            cef_render_handler_capi_h.C_POINTER,
            cef_render_handler_capi_h.C_INT,
            cef_render_handler_capi_h.C_POINTER,
            cef_render_handler_capi_h.C_INT
        );

        /**
         * The descriptor of this function pointer
         */
        public static FunctionDescriptor descriptor() {
            return $DESC;
        }

        private static final MethodHandle UP$MH = cef_render_handler_capi_h.upcallHandle(SetFuncAndParamNames.Function.class, "apply", $DESC);

        /**
         * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
         * The lifetime of the returned segment is managed by {@code arena}
         */
        public static MemorySegment allocate(SetFuncAndParamNames.Function fi, Arena arena) {
            return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
        }

        private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

        /**
         * Invoke the upcall stub {@code funcPtr}, with given parameters
         */
        public static int invoke(MemorySegment funcPtr, MemorySegment _x0, int _x1, MemorySegment _x2, int _x3) {
            try {
                return (int) DOWN$MH.invokeExact(funcPtr, _x0, _x1, _x2, _x3);
            } catch (Error | RuntimeException ex) {
                throw ex;
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        }
    }

    private static final AddressLayout SetFuncAndParamNames$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("SetFuncAndParamNames"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * HRESULT (*SetFuncAndParamNames)(ICreateTypeInfo *, UINT, LPOLESTR *, UINT) __attribute__((stdcall))
     * }
     */
    public static final AddressLayout SetFuncAndParamNames$layout() {
        return SetFuncAndParamNames$LAYOUT;
    }

    private static final long SetFuncAndParamNames$OFFSET = $LAYOUT.byteOffset(groupElement("SetFuncAndParamNames"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * HRESULT (*SetFuncAndParamNames)(ICreateTypeInfo *, UINT, LPOLESTR *, UINT) __attribute__((stdcall))
     * }
     */
    public static final long SetFuncAndParamNames$offset() {
        return SetFuncAndParamNames$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * HRESULT (*SetFuncAndParamNames)(ICreateTypeInfo *, UINT, LPOLESTR *, UINT) __attribute__((stdcall))
     * }
     */
    public static MemorySegment SetFuncAndParamNames(MemorySegment struct) {
        return struct.get(SetFuncAndParamNames$LAYOUT, SetFuncAndParamNames$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * HRESULT (*SetFuncAndParamNames)(ICreateTypeInfo *, UINT, LPOLESTR *, UINT) __attribute__((stdcall))
     * }
     */
    public static void SetFuncAndParamNames(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(SetFuncAndParamNames$LAYOUT, SetFuncAndParamNames$OFFSET, fieldValue);
    }

    /**
     * {@snippet lang=c :
     * HRESULT (*SetVarName)(ICreateTypeInfo *, UINT, LPOLESTR) __attribute__((stdcall))
     * }
     */
    public final static class SetVarName {

        private SetVarName() {
            // Should not be called directly
        }

        /**
         * The function pointer signature, expressed as a functional interface
         */
        public interface Function {
            int apply(MemorySegment _x0, int _x1, MemorySegment _x2);
        }

        private static final FunctionDescriptor $DESC = FunctionDescriptor.of(
            cef_render_handler_capi_h.C_LONG,
            cef_render_handler_capi_h.C_POINTER,
            cef_render_handler_capi_h.C_INT,
            cef_render_handler_capi_h.C_POINTER
        );

        /**
         * The descriptor of this function pointer
         */
        public static FunctionDescriptor descriptor() {
            return $DESC;
        }

        private static final MethodHandle UP$MH = cef_render_handler_capi_h.upcallHandle(SetVarName.Function.class, "apply", $DESC);

        /**
         * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
         * The lifetime of the returned segment is managed by {@code arena}
         */
        public static MemorySegment allocate(SetVarName.Function fi, Arena arena) {
            return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
        }

        private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

        /**
         * Invoke the upcall stub {@code funcPtr}, with given parameters
         */
        public static int invoke(MemorySegment funcPtr, MemorySegment _x0, int _x1, MemorySegment _x2) {
            try {
                return (int) DOWN$MH.invokeExact(funcPtr, _x0, _x1, _x2);
            } catch (Error | RuntimeException ex) {
                throw ex;
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        }
    }

    private static final AddressLayout SetVarName$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("SetVarName"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * HRESULT (*SetVarName)(ICreateTypeInfo *, UINT, LPOLESTR) __attribute__((stdcall))
     * }
     */
    public static final AddressLayout SetVarName$layout() {
        return SetVarName$LAYOUT;
    }

    private static final long SetVarName$OFFSET = $LAYOUT.byteOffset(groupElement("SetVarName"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * HRESULT (*SetVarName)(ICreateTypeInfo *, UINT, LPOLESTR) __attribute__((stdcall))
     * }
     */
    public static final long SetVarName$offset() {
        return SetVarName$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * HRESULT (*SetVarName)(ICreateTypeInfo *, UINT, LPOLESTR) __attribute__((stdcall))
     * }
     */
    public static MemorySegment SetVarName(MemorySegment struct) {
        return struct.get(SetVarName$LAYOUT, SetVarName$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * HRESULT (*SetVarName)(ICreateTypeInfo *, UINT, LPOLESTR) __attribute__((stdcall))
     * }
     */
    public static void SetVarName(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(SetVarName$LAYOUT, SetVarName$OFFSET, fieldValue);
    }

    /**
     * {@snippet lang=c :
     * HRESULT (*SetTypeDescAlias)(ICreateTypeInfo *, TYPEDESC *) __attribute__((stdcall))
     * }
     */
    public final static class SetTypeDescAlias {

        private SetTypeDescAlias() {
            // Should not be called directly
        }

        /**
         * The function pointer signature, expressed as a functional interface
         */
        public interface Function {
            int apply(MemorySegment _x0, MemorySegment _x1);
        }

        private static final FunctionDescriptor $DESC = FunctionDescriptor.of(
            cef_render_handler_capi_h.C_LONG,
            cef_render_handler_capi_h.C_POINTER,
            cef_render_handler_capi_h.C_POINTER
        );

        /**
         * The descriptor of this function pointer
         */
        public static FunctionDescriptor descriptor() {
            return $DESC;
        }

        private static final MethodHandle UP$MH = cef_render_handler_capi_h.upcallHandle(SetTypeDescAlias.Function.class, "apply", $DESC);

        /**
         * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
         * The lifetime of the returned segment is managed by {@code arena}
         */
        public static MemorySegment allocate(SetTypeDescAlias.Function fi, Arena arena) {
            return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
        }

        private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

        /**
         * Invoke the upcall stub {@code funcPtr}, with given parameters
         */
        public static int invoke(MemorySegment funcPtr, MemorySegment _x0, MemorySegment _x1) {
            try {
                return (int) DOWN$MH.invokeExact(funcPtr, _x0, _x1);
            } catch (Error | RuntimeException ex) {
                throw ex;
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        }
    }

    private static final AddressLayout SetTypeDescAlias$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("SetTypeDescAlias"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * HRESULT (*SetTypeDescAlias)(ICreateTypeInfo *, TYPEDESC *) __attribute__((stdcall))
     * }
     */
    public static final AddressLayout SetTypeDescAlias$layout() {
        return SetTypeDescAlias$LAYOUT;
    }

    private static final long SetTypeDescAlias$OFFSET = $LAYOUT.byteOffset(groupElement("SetTypeDescAlias"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * HRESULT (*SetTypeDescAlias)(ICreateTypeInfo *, TYPEDESC *) __attribute__((stdcall))
     * }
     */
    public static final long SetTypeDescAlias$offset() {
        return SetTypeDescAlias$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * HRESULT (*SetTypeDescAlias)(ICreateTypeInfo *, TYPEDESC *) __attribute__((stdcall))
     * }
     */
    public static MemorySegment SetTypeDescAlias(MemorySegment struct) {
        return struct.get(SetTypeDescAlias$LAYOUT, SetTypeDescAlias$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * HRESULT (*SetTypeDescAlias)(ICreateTypeInfo *, TYPEDESC *) __attribute__((stdcall))
     * }
     */
    public static void SetTypeDescAlias(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(SetTypeDescAlias$LAYOUT, SetTypeDescAlias$OFFSET, fieldValue);
    }

    /**
     * {@snippet lang=c :
     * HRESULT (*DefineFuncAsDllEntry)(ICreateTypeInfo *, UINT, LPOLESTR, LPOLESTR) __attribute__((stdcall))
     * }
     */
    public final static class DefineFuncAsDllEntry {

        private DefineFuncAsDllEntry() {
            // Should not be called directly
        }

        /**
         * The function pointer signature, expressed as a functional interface
         */
        public interface Function {
            int apply(MemorySegment _x0, int _x1, MemorySegment _x2, MemorySegment _x3);
        }

        private static final FunctionDescriptor $DESC = FunctionDescriptor.of(
            cef_render_handler_capi_h.C_LONG,
            cef_render_handler_capi_h.C_POINTER,
            cef_render_handler_capi_h.C_INT,
            cef_render_handler_capi_h.C_POINTER,
            cef_render_handler_capi_h.C_POINTER
        );

        /**
         * The descriptor of this function pointer
         */
        public static FunctionDescriptor descriptor() {
            return $DESC;
        }

        private static final MethodHandle UP$MH = cef_render_handler_capi_h.upcallHandle(DefineFuncAsDllEntry.Function.class, "apply", $DESC);

        /**
         * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
         * The lifetime of the returned segment is managed by {@code arena}
         */
        public static MemorySegment allocate(DefineFuncAsDllEntry.Function fi, Arena arena) {
            return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
        }

        private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

        /**
         * Invoke the upcall stub {@code funcPtr}, with given parameters
         */
        public static int invoke(MemorySegment funcPtr, MemorySegment _x0, int _x1, MemorySegment _x2, MemorySegment _x3) {
            try {
                return (int) DOWN$MH.invokeExact(funcPtr, _x0, _x1, _x2, _x3);
            } catch (Error | RuntimeException ex) {
                throw ex;
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        }
    }

    private static final AddressLayout DefineFuncAsDllEntry$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("DefineFuncAsDllEntry"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * HRESULT (*DefineFuncAsDllEntry)(ICreateTypeInfo *, UINT, LPOLESTR, LPOLESTR) __attribute__((stdcall))
     * }
     */
    public static final AddressLayout DefineFuncAsDllEntry$layout() {
        return DefineFuncAsDllEntry$LAYOUT;
    }

    private static final long DefineFuncAsDllEntry$OFFSET = $LAYOUT.byteOffset(groupElement("DefineFuncAsDllEntry"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * HRESULT (*DefineFuncAsDllEntry)(ICreateTypeInfo *, UINT, LPOLESTR, LPOLESTR) __attribute__((stdcall))
     * }
     */
    public static final long DefineFuncAsDllEntry$offset() {
        return DefineFuncAsDllEntry$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * HRESULT (*DefineFuncAsDllEntry)(ICreateTypeInfo *, UINT, LPOLESTR, LPOLESTR) __attribute__((stdcall))
     * }
     */
    public static MemorySegment DefineFuncAsDllEntry(MemorySegment struct) {
        return struct.get(DefineFuncAsDllEntry$LAYOUT, DefineFuncAsDllEntry$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * HRESULT (*DefineFuncAsDllEntry)(ICreateTypeInfo *, UINT, LPOLESTR, LPOLESTR) __attribute__((stdcall))
     * }
     */
    public static void DefineFuncAsDllEntry(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(DefineFuncAsDllEntry$LAYOUT, DefineFuncAsDllEntry$OFFSET, fieldValue);
    }

    /**
     * {@snippet lang=c :
     * HRESULT (*SetFuncDocString)(ICreateTypeInfo *, UINT, LPOLESTR) __attribute__((stdcall))
     * }
     */
    public final static class SetFuncDocString {

        private SetFuncDocString() {
            // Should not be called directly
        }

        /**
         * The function pointer signature, expressed as a functional interface
         */
        public interface Function {
            int apply(MemorySegment _x0, int _x1, MemorySegment _x2);
        }

        private static final FunctionDescriptor $DESC = FunctionDescriptor.of(
            cef_render_handler_capi_h.C_LONG,
            cef_render_handler_capi_h.C_POINTER,
            cef_render_handler_capi_h.C_INT,
            cef_render_handler_capi_h.C_POINTER
        );

        /**
         * The descriptor of this function pointer
         */
        public static FunctionDescriptor descriptor() {
            return $DESC;
        }

        private static final MethodHandle UP$MH = cef_render_handler_capi_h.upcallHandle(SetFuncDocString.Function.class, "apply", $DESC);

        /**
         * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
         * The lifetime of the returned segment is managed by {@code arena}
         */
        public static MemorySegment allocate(SetFuncDocString.Function fi, Arena arena) {
            return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
        }

        private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

        /**
         * Invoke the upcall stub {@code funcPtr}, with given parameters
         */
        public static int invoke(MemorySegment funcPtr, MemorySegment _x0, int _x1, MemorySegment _x2) {
            try {
                return (int) DOWN$MH.invokeExact(funcPtr, _x0, _x1, _x2);
            } catch (Error | RuntimeException ex) {
                throw ex;
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        }
    }

    private static final AddressLayout SetFuncDocString$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("SetFuncDocString"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * HRESULT (*SetFuncDocString)(ICreateTypeInfo *, UINT, LPOLESTR) __attribute__((stdcall))
     * }
     */
    public static final AddressLayout SetFuncDocString$layout() {
        return SetFuncDocString$LAYOUT;
    }

    private static final long SetFuncDocString$OFFSET = $LAYOUT.byteOffset(groupElement("SetFuncDocString"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * HRESULT (*SetFuncDocString)(ICreateTypeInfo *, UINT, LPOLESTR) __attribute__((stdcall))
     * }
     */
    public static final long SetFuncDocString$offset() {
        return SetFuncDocString$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * HRESULT (*SetFuncDocString)(ICreateTypeInfo *, UINT, LPOLESTR) __attribute__((stdcall))
     * }
     */
    public static MemorySegment SetFuncDocString(MemorySegment struct) {
        return struct.get(SetFuncDocString$LAYOUT, SetFuncDocString$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * HRESULT (*SetFuncDocString)(ICreateTypeInfo *, UINT, LPOLESTR) __attribute__((stdcall))
     * }
     */
    public static void SetFuncDocString(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(SetFuncDocString$LAYOUT, SetFuncDocString$OFFSET, fieldValue);
    }

    /**
     * {@snippet lang=c :
     * HRESULT (*SetVarDocString)(ICreateTypeInfo *, UINT, LPOLESTR) __attribute__((stdcall))
     * }
     */
    public final static class SetVarDocString {

        private SetVarDocString() {
            // Should not be called directly
        }

        /**
         * The function pointer signature, expressed as a functional interface
         */
        public interface Function {
            int apply(MemorySegment _x0, int _x1, MemorySegment _x2);
        }

        private static final FunctionDescriptor $DESC = FunctionDescriptor.of(
            cef_render_handler_capi_h.C_LONG,
            cef_render_handler_capi_h.C_POINTER,
            cef_render_handler_capi_h.C_INT,
            cef_render_handler_capi_h.C_POINTER
        );

        /**
         * The descriptor of this function pointer
         */
        public static FunctionDescriptor descriptor() {
            return $DESC;
        }

        private static final MethodHandle UP$MH = cef_render_handler_capi_h.upcallHandle(SetVarDocString.Function.class, "apply", $DESC);

        /**
         * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
         * The lifetime of the returned segment is managed by {@code arena}
         */
        public static MemorySegment allocate(SetVarDocString.Function fi, Arena arena) {
            return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
        }

        private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

        /**
         * Invoke the upcall stub {@code funcPtr}, with given parameters
         */
        public static int invoke(MemorySegment funcPtr, MemorySegment _x0, int _x1, MemorySegment _x2) {
            try {
                return (int) DOWN$MH.invokeExact(funcPtr, _x0, _x1, _x2);
            } catch (Error | RuntimeException ex) {
                throw ex;
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        }
    }

    private static final AddressLayout SetVarDocString$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("SetVarDocString"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * HRESULT (*SetVarDocString)(ICreateTypeInfo *, UINT, LPOLESTR) __attribute__((stdcall))
     * }
     */
    public static final AddressLayout SetVarDocString$layout() {
        return SetVarDocString$LAYOUT;
    }

    private static final long SetVarDocString$OFFSET = $LAYOUT.byteOffset(groupElement("SetVarDocString"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * HRESULT (*SetVarDocString)(ICreateTypeInfo *, UINT, LPOLESTR) __attribute__((stdcall))
     * }
     */
    public static final long SetVarDocString$offset() {
        return SetVarDocString$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * HRESULT (*SetVarDocString)(ICreateTypeInfo *, UINT, LPOLESTR) __attribute__((stdcall))
     * }
     */
    public static MemorySegment SetVarDocString(MemorySegment struct) {
        return struct.get(SetVarDocString$LAYOUT, SetVarDocString$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * HRESULT (*SetVarDocString)(ICreateTypeInfo *, UINT, LPOLESTR) __attribute__((stdcall))
     * }
     */
    public static void SetVarDocString(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(SetVarDocString$LAYOUT, SetVarDocString$OFFSET, fieldValue);
    }

    /**
     * {@snippet lang=c :
     * HRESULT (*SetFuncHelpContext)(ICreateTypeInfo *, UINT, DWORD) __attribute__((stdcall))
     * }
     */
    public final static class SetFuncHelpContext {

        private SetFuncHelpContext() {
            // Should not be called directly
        }

        /**
         * The function pointer signature, expressed as a functional interface
         */
        public interface Function {
            int apply(MemorySegment _x0, int _x1, int _x2);
        }

        private static final FunctionDescriptor $DESC = FunctionDescriptor.of(
            cef_render_handler_capi_h.C_LONG,
            cef_render_handler_capi_h.C_POINTER,
            cef_render_handler_capi_h.C_INT,
            cef_render_handler_capi_h.C_LONG
        );

        /**
         * The descriptor of this function pointer
         */
        public static FunctionDescriptor descriptor() {
            return $DESC;
        }

        private static final MethodHandle UP$MH = cef_render_handler_capi_h.upcallHandle(SetFuncHelpContext.Function.class, "apply", $DESC);

        /**
         * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
         * The lifetime of the returned segment is managed by {@code arena}
         */
        public static MemorySegment allocate(SetFuncHelpContext.Function fi, Arena arena) {
            return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
        }

        private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

        /**
         * Invoke the upcall stub {@code funcPtr}, with given parameters
         */
        public static int invoke(MemorySegment funcPtr, MemorySegment _x0, int _x1, int _x2) {
            try {
                return (int) DOWN$MH.invokeExact(funcPtr, _x0, _x1, _x2);
            } catch (Error | RuntimeException ex) {
                throw ex;
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        }
    }

    private static final AddressLayout SetFuncHelpContext$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("SetFuncHelpContext"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * HRESULT (*SetFuncHelpContext)(ICreateTypeInfo *, UINT, DWORD) __attribute__((stdcall))
     * }
     */
    public static final AddressLayout SetFuncHelpContext$layout() {
        return SetFuncHelpContext$LAYOUT;
    }

    private static final long SetFuncHelpContext$OFFSET = $LAYOUT.byteOffset(groupElement("SetFuncHelpContext"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * HRESULT (*SetFuncHelpContext)(ICreateTypeInfo *, UINT, DWORD) __attribute__((stdcall))
     * }
     */
    public static final long SetFuncHelpContext$offset() {
        return SetFuncHelpContext$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * HRESULT (*SetFuncHelpContext)(ICreateTypeInfo *, UINT, DWORD) __attribute__((stdcall))
     * }
     */
    public static MemorySegment SetFuncHelpContext(MemorySegment struct) {
        return struct.get(SetFuncHelpContext$LAYOUT, SetFuncHelpContext$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * HRESULT (*SetFuncHelpContext)(ICreateTypeInfo *, UINT, DWORD) __attribute__((stdcall))
     * }
     */
    public static void SetFuncHelpContext(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(SetFuncHelpContext$LAYOUT, SetFuncHelpContext$OFFSET, fieldValue);
    }

    /**
     * {@snippet lang=c :
     * HRESULT (*SetVarHelpContext)(ICreateTypeInfo *, UINT, DWORD) __attribute__((stdcall))
     * }
     */
    public final static class SetVarHelpContext {

        private SetVarHelpContext() {
            // Should not be called directly
        }

        /**
         * The function pointer signature, expressed as a functional interface
         */
        public interface Function {
            int apply(MemorySegment _x0, int _x1, int _x2);
        }

        private static final FunctionDescriptor $DESC = FunctionDescriptor.of(
            cef_render_handler_capi_h.C_LONG,
            cef_render_handler_capi_h.C_POINTER,
            cef_render_handler_capi_h.C_INT,
            cef_render_handler_capi_h.C_LONG
        );

        /**
         * The descriptor of this function pointer
         */
        public static FunctionDescriptor descriptor() {
            return $DESC;
        }

        private static final MethodHandle UP$MH = cef_render_handler_capi_h.upcallHandle(SetVarHelpContext.Function.class, "apply", $DESC);

        /**
         * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
         * The lifetime of the returned segment is managed by {@code arena}
         */
        public static MemorySegment allocate(SetVarHelpContext.Function fi, Arena arena) {
            return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
        }

        private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

        /**
         * Invoke the upcall stub {@code funcPtr}, with given parameters
         */
        public static int invoke(MemorySegment funcPtr, MemorySegment _x0, int _x1, int _x2) {
            try {
                return (int) DOWN$MH.invokeExact(funcPtr, _x0, _x1, _x2);
            } catch (Error | RuntimeException ex) {
                throw ex;
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        }
    }

    private static final AddressLayout SetVarHelpContext$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("SetVarHelpContext"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * HRESULT (*SetVarHelpContext)(ICreateTypeInfo *, UINT, DWORD) __attribute__((stdcall))
     * }
     */
    public static final AddressLayout SetVarHelpContext$layout() {
        return SetVarHelpContext$LAYOUT;
    }

    private static final long SetVarHelpContext$OFFSET = $LAYOUT.byteOffset(groupElement("SetVarHelpContext"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * HRESULT (*SetVarHelpContext)(ICreateTypeInfo *, UINT, DWORD) __attribute__((stdcall))
     * }
     */
    public static final long SetVarHelpContext$offset() {
        return SetVarHelpContext$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * HRESULT (*SetVarHelpContext)(ICreateTypeInfo *, UINT, DWORD) __attribute__((stdcall))
     * }
     */
    public static MemorySegment SetVarHelpContext(MemorySegment struct) {
        return struct.get(SetVarHelpContext$LAYOUT, SetVarHelpContext$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * HRESULT (*SetVarHelpContext)(ICreateTypeInfo *, UINT, DWORD) __attribute__((stdcall))
     * }
     */
    public static void SetVarHelpContext(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(SetVarHelpContext$LAYOUT, SetVarHelpContext$OFFSET, fieldValue);
    }

    /**
     * {@snippet lang=c :
     * HRESULT (*SetMops)(ICreateTypeInfo *, UINT, BSTR) __attribute__((stdcall))
     * }
     */
    public final static class SetMops {

        private SetMops() {
            // Should not be called directly
        }

        /**
         * The function pointer signature, expressed as a functional interface
         */
        public interface Function {
            int apply(MemorySegment _x0, int _x1, MemorySegment _x2);
        }

        private static final FunctionDescriptor $DESC = FunctionDescriptor.of(
            cef_render_handler_capi_h.C_LONG,
            cef_render_handler_capi_h.C_POINTER,
            cef_render_handler_capi_h.C_INT,
            cef_render_handler_capi_h.C_POINTER
        );

        /**
         * The descriptor of this function pointer
         */
        public static FunctionDescriptor descriptor() {
            return $DESC;
        }

        private static final MethodHandle UP$MH = cef_render_handler_capi_h.upcallHandle(SetMops.Function.class, "apply", $DESC);

        /**
         * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
         * The lifetime of the returned segment is managed by {@code arena}
         */
        public static MemorySegment allocate(SetMops.Function fi, Arena arena) {
            return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
        }

        private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

        /**
         * Invoke the upcall stub {@code funcPtr}, with given parameters
         */
        public static int invoke(MemorySegment funcPtr, MemorySegment _x0, int _x1, MemorySegment _x2) {
            try {
                return (int) DOWN$MH.invokeExact(funcPtr, _x0, _x1, _x2);
            } catch (Error | RuntimeException ex) {
                throw ex;
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        }
    }

    private static final AddressLayout SetMops$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("SetMops"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * HRESULT (*SetMops)(ICreateTypeInfo *, UINT, BSTR) __attribute__((stdcall))
     * }
     */
    public static final AddressLayout SetMops$layout() {
        return SetMops$LAYOUT;
    }

    private static final long SetMops$OFFSET = $LAYOUT.byteOffset(groupElement("SetMops"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * HRESULT (*SetMops)(ICreateTypeInfo *, UINT, BSTR) __attribute__((stdcall))
     * }
     */
    public static final long SetMops$offset() {
        return SetMops$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * HRESULT (*SetMops)(ICreateTypeInfo *, UINT, BSTR) __attribute__((stdcall))
     * }
     */
    public static MemorySegment SetMops(MemorySegment struct) {
        return struct.get(SetMops$LAYOUT, SetMops$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * HRESULT (*SetMops)(ICreateTypeInfo *, UINT, BSTR) __attribute__((stdcall))
     * }
     */
    public static void SetMops(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(SetMops$LAYOUT, SetMops$OFFSET, fieldValue);
    }

    /**
     * {@snippet lang=c :
     * HRESULT (*SetTypeIdldesc)(ICreateTypeInfo *, IDLDESC *) __attribute__((stdcall))
     * }
     */
    public final static class SetTypeIdldesc {

        private SetTypeIdldesc() {
            // Should not be called directly
        }

        /**
         * The function pointer signature, expressed as a functional interface
         */
        public interface Function {
            int apply(MemorySegment _x0, MemorySegment _x1);
        }

        private static final FunctionDescriptor $DESC = FunctionDescriptor.of(
            cef_render_handler_capi_h.C_LONG,
            cef_render_handler_capi_h.C_POINTER,
            cef_render_handler_capi_h.C_POINTER
        );

        /**
         * The descriptor of this function pointer
         */
        public static FunctionDescriptor descriptor() {
            return $DESC;
        }

        private static final MethodHandle UP$MH = cef_render_handler_capi_h.upcallHandle(SetTypeIdldesc.Function.class, "apply", $DESC);

        /**
         * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
         * The lifetime of the returned segment is managed by {@code arena}
         */
        public static MemorySegment allocate(SetTypeIdldesc.Function fi, Arena arena) {
            return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
        }

        private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

        /**
         * Invoke the upcall stub {@code funcPtr}, with given parameters
         */
        public static int invoke(MemorySegment funcPtr, MemorySegment _x0, MemorySegment _x1) {
            try {
                return (int) DOWN$MH.invokeExact(funcPtr, _x0, _x1);
            } catch (Error | RuntimeException ex) {
                throw ex;
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        }
    }

    private static final AddressLayout SetTypeIdldesc$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("SetTypeIdldesc"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * HRESULT (*SetTypeIdldesc)(ICreateTypeInfo *, IDLDESC *) __attribute__((stdcall))
     * }
     */
    public static final AddressLayout SetTypeIdldesc$layout() {
        return SetTypeIdldesc$LAYOUT;
    }

    private static final long SetTypeIdldesc$OFFSET = $LAYOUT.byteOffset(groupElement("SetTypeIdldesc"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * HRESULT (*SetTypeIdldesc)(ICreateTypeInfo *, IDLDESC *) __attribute__((stdcall))
     * }
     */
    public static final long SetTypeIdldesc$offset() {
        return SetTypeIdldesc$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * HRESULT (*SetTypeIdldesc)(ICreateTypeInfo *, IDLDESC *) __attribute__((stdcall))
     * }
     */
    public static MemorySegment SetTypeIdldesc(MemorySegment struct) {
        return struct.get(SetTypeIdldesc$LAYOUT, SetTypeIdldesc$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * HRESULT (*SetTypeIdldesc)(ICreateTypeInfo *, IDLDESC *) __attribute__((stdcall))
     * }
     */
    public static void SetTypeIdldesc(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(SetTypeIdldesc$LAYOUT, SetTypeIdldesc$OFFSET, fieldValue);
    }

    /**
     * {@snippet lang=c :
     * HRESULT (*LayOut)(ICreateTypeInfo *) __attribute__((stdcall))
     * }
     */
    public final static class LayOut {

        private LayOut() {
            // Should not be called directly
        }

        /**
         * The function pointer signature, expressed as a functional interface
         */
        public interface Function {
            int apply(MemorySegment _x0);
        }

        private static final FunctionDescriptor $DESC = FunctionDescriptor.of(
            cef_render_handler_capi_h.C_LONG,
            cef_render_handler_capi_h.C_POINTER
        );

        /**
         * The descriptor of this function pointer
         */
        public static FunctionDescriptor descriptor() {
            return $DESC;
        }

        private static final MethodHandle UP$MH = cef_render_handler_capi_h.upcallHandle(LayOut.Function.class, "apply", $DESC);

        /**
         * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
         * The lifetime of the returned segment is managed by {@code arena}
         */
        public static MemorySegment allocate(LayOut.Function fi, Arena arena) {
            return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
        }

        private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

        /**
         * Invoke the upcall stub {@code funcPtr}, with given parameters
         */
        public static int invoke(MemorySegment funcPtr, MemorySegment _x0) {
            try {
                return (int) DOWN$MH.invokeExact(funcPtr, _x0);
            } catch (Error | RuntimeException ex) {
                throw ex;
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        }
    }

    private static final AddressLayout LayOut$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("LayOut"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * HRESULT (*LayOut)(ICreateTypeInfo *) __attribute__((stdcall))
     * }
     */
    public static final AddressLayout LayOut$layout() {
        return LayOut$LAYOUT;
    }

    private static final long LayOut$OFFSET = $LAYOUT.byteOffset(groupElement("LayOut"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * HRESULT (*LayOut)(ICreateTypeInfo *) __attribute__((stdcall))
     * }
     */
    public static final long LayOut$offset() {
        return LayOut$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * HRESULT (*LayOut)(ICreateTypeInfo *) __attribute__((stdcall))
     * }
     */
    public static MemorySegment LayOut(MemorySegment struct) {
        return struct.get(LayOut$LAYOUT, LayOut$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * HRESULT (*LayOut)(ICreateTypeInfo *) __attribute__((stdcall))
     * }
     */
    public static void LayOut(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(LayOut$LAYOUT, LayOut$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

