// Generated by jextract

package com.tiji.silcef.natives;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * typedef struct tagTOUCHPAD_PARAMETERS_V2 {
 *     BOOL button1Supported : 1;
 *     BOOL button2Supported : 1;
 *     BOOL button3Supported : 1;
 *     BOOL Reserved3 : 29;
 * } TOUCHPAD_PARAMETERS_V2
 * }
 */
public class TOUCHPAD_PARAMETERS_V2 extends tagTOUCHPAD_PARAMETERS_V2 {

    TOUCHPAD_PARAMETERS_V2() {
        // Should not be called directly
    }
}

